### ISSUE TITLE
PlayerTeleportEvent Error

### ISSUE THREAD

**Issue by HaNiTLG** [konsolas/AAC-Issues#1007]
When a player is death, than I will get this error in the console: https://hastebin.com/izeginohif.vbs
`[19:47:40 ERROR]: Could not pass event PlayerTeleportEvent to AAC v3.3.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:541) [spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.claymc.bedwars.listener.DeathListener$1.run(DeathListener.java:56) [BedWars.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.IllegalStateException: Must be called from the main thread
        at me.konsolas.aac.aN.a(aN.java:68) ~[?:?]
        at me.konsolas.aac.bP.a(bP.java:88) ~[?:?]
        at me.konsolas.aac.aN.a(aN.java:76) ~[?:?]
        at me.konsolas.aac.aN.a(aN.java:21) ~[?:?]
        at me.konsolas.aac.aF.a(aF.java:111) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        ... 12 more`

My codeline from PlayerDeathEvent of BedWars is just [public void run() {] > p.teleport(....); 

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.2

**ProtocolLib version**: 4.3.0

**Plugin list**: BedWars, Multiverse, AAC, ProtocolLib, PermissionSystem, ViaVersion

### Special environment information
**ViaVersion version**: Yes

**ProtocolSupport version**: Yes

**ViaBackwards version**: No

**BungeeCord plugins**: No

**Comment by Janmm14** [comment]
Your teleportation code seems to run asynchroniously aka not on the main server thread - just as the issue describes.
AAC enforces the unwritten rule of the bukkit api (everything except sending messages is not threadsafe by default) for teleports because otherwise there is no good option to not potentially cause a crash of minecraft while retrieving neccessary information from nms.

**Comment by konsolas** [comment]
See above.
