### ISSUE TITLE
Bukkit CommandMap error on command execution

### ISSUE THREAD

**Issue by SAMMIEPLAYS** [konsolas/AAC-Issues#1012]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

```
[00:11:13 INFO]: [CONSOLE] ThatOneClone_ in world is suspected for Killaura (Normal) (ping = 415, tps = 19.96)
[00:11:19 WARN]: [AAC] Task #8548 for AAC v3.3.2 generated an exception
java.lang.NullPointerException
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
        at me.konsolas.aac.p.a(p.java:2) ~[?:?]
        at me.konsolas.aac.m.run(m.java:7) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

### Core information
**Server version**: https://gyazo.com/05c967b8a4655a045745f584538d921c

**AAC version**: 3.3.2

**ProtocolLib version**: 4.2.0

**Plugin list**: 
My /pl is blocked etc, if you really need it lemme know

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration

_Edit by staff: Please add your configuration_

**Comment by ItzSomebody** [comment]
To save @Janmm14 some time, please tell which version of AAC you have. Latest is ambiguous.

Note: AAC 3.3.3 shows as 3.3.2 in console

**Comment by SAMMIEPLAYS** [comment]
3.3.2 :)

**Comment by w-o-a-h** [comment]
try aac 3.3.3

**Comment by Janmm14** [comment]
@SAMMIEPLAYS
Likely its
- either an error caused by other plugins doing harmful stuff with bukkit's command registry
-  your aac threshold config contains some strange stuff
or its something strange happening inside aac.

**Comment by konsolas** [comment]
what's your config?

**Comment by Janmm14** [comment]
closed due to inactivity
