### ISSUE TITLE
Issues with JDK9

### ISSUE THREAD

**Issue by jiongjionger** [konsolas/AAC-Issues#1021]
### Issue description

```
[14:48:58 INFO]: [AAC] Enabling AAC v3.3.4
[14:48:59 ERROR]: Error occurred while enabling AAC v3.3.4 (Is it up to date?)
java.lang.NoClassDefFoundError: sun/misc/SharedSecrets
        at me.konsolas.iaac.ep.e(Unknown Source) ~[?:?]
        at me.konsolas.iaac.c.<clinit>(c.java) ~[?:?]
        at me.konsolas.aac.AAC.onEnable(AAC.java:16) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[paper-1.11.2.jar:git-Paper-unknown]
```
### Core information
**Server version**: 1.11.2

**AAC version**: 3.3.4

**Comment by jiangdashao** [comment]
Plz delete the assist info

**Comment by Janmm14** [comment]
Will likely take some time until this will be fixed.
