### ISSUE TITLE
pwp error..

### ISSUE THREAD

**Issue by gnsl701016** [konsolas/AAC-Issues#1022]
```
[19:52:59 WARN]: [AAC] Task #39 for AAC v3.3.4 generated an exception
java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.resize(Unknown Source) ~[?:1.8.0_144]
        at java.util.HashMap.putVal(Unknown Source) ~[?:1.8.0_144]
        at java.util.HashMap.put(Unknown Source) ~[?:1.8.0_144]
        at java.util.HashSet.add(Unknown Source) ~[?:1.8.0_144]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.createRegisteredListeners(PerWorldPluginLoader.java:55) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:527) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at me.konsolas.aac.t.b(t.java:179) ~[?:?]
        at me.konsolas.aac.aa.run(aa.java:19) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by Janmm14** [comment]
He has usetps disabled.

**Comment by gnsl701016** [comment]
i already restarted server. but it is not solved

**Comment by konsolas** [comment]
Can't reproduce this one with PWP
