### ISSUE TITLE
NPE@x.a:89 from ar.a:234 (Task)

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#1023]
```
13.10 14:46:44 [Server] WARN [AAC] Task #33 for AAC v3.3.4 generated an exception
13.10 14:46:44 [Server] INFO java.lang.NullPointerException
13.10 14:46:44 [Server] INFO at me.konsolas.aac.x.a(x.java:89) ~[?:?]
13.10 14:46:44 [Server] INFO at me.konsolas.aac.ar.a(ar.java:234) ~[?:?]
13.10 14:46:44 [Server] INFO at me.konsolas.aac.ar.a(ar.java:314) ~[?:?]
13.10 14:46:44 [Server] INFO at me.konsolas.aac.t.lambda$new$0(t.java:117) ~[?:?]
13.10 14:46:44 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
13.10 14:46:44 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
13.10 14:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
13.10 14:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
13.10 14:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
13.10 14:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
```
### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.4

Happening on GommeHD.net

**Comment by marint94** [comment]
Same for me

**Comment by disqetow** [comment]
Yes It on 1.8.8,In the console

**Comment by Janmm14** [comment]
Similar issue in 1025:
```java
[19:04:00 WARN]: [AAC] Task #598 for AAC v3.3.4 generated an exception
java.lang.NullPointerException
        at me.konsolas.aac.x.a(x.java:89) ~[?:?]
        at me.konsolas.aac.ar.a(ar.java:234) ~[?:?]
        at me.konsolas.aac.t.a(t.java:104) ~[?:?]
        at me.konsolas.aac.N.lambda$new$2(N.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

**Comment by konsolas** [comment]
-b1
