### ISSUE TITLE
Cannot measure distance between worlds @c3.a:62 from y.a:143 (Task)

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#1027]
Reported at https://www.spigotmc.org/threads/aac-advanced-anti-cheat-hack-kill-aura-blocker-paid.63195/page-434#post-2710210
```
[15:27:40 WARN]: [AAC] Task #4956 for AAC v3.3.4 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between nspawn and world
at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
at me.konsolas.aac.c3.a(c3.java:62) ~[?:?]
at me.konsolas.aac.y.a(y.java:143) ~[?:?]
at me.konsolas.aac.c_.lambda$new$2(c_.java:109) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
```

**Comment by marint94** [comment]
Same error

`[15:08:39] [Server thread/WARN]: [AAC] Task #43 for AAC v3.3.4 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between World18 and World18_the_end
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
	at me.konsolas.aac.c3.a(c3.java:62) ~[?:?]
	at me.konsolas.aac.y.a(y.java:143) ~[?:?]
	at me.konsolas.aac.c_.lambda$new$2(c_.java:109) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [craftbukkit.jar:git-PaperSpigot-"8b18730"]`

**Comment by Hamata6** [comment]
Same error for me. In my case it happens when a player falls out of my islandworld of skyblock. Then he will be teleported to the spawn which is another world. Then this error shows up.
