### ISSUE TITLE
Error: KillauraEntity

### ISSUE THREAD

**Issue by Henriks9** [konsolas/AAC-Issues#1044]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: AACAdditionPro 3.3.1/AAC 3.3.4-b1

**ProtocolLib version**: ProtocolLib v4.2.0

**Plugin list**: AAC/ProtocolLib/ AACAdditionPro

### Special environment information
**ViaVersion version**: insert NO

**ProtocolSupport version**: insert (or N/A)

**ViaBackwards version**: insert (or N/A)

**BungeeCord plugins**: insert (or N/A)

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

Error beim KillauraEntity

[20:42:10] [Craft Scheduler Thread - 0/WARN]: Exception in thread "Craft Scheduler Thread - 0" 
[20:42:10] [Craft Scheduler Thread - 0/WARN]: org.apache.commons.lang.UnhandledException: Plugin AACAdditionPro v3.3.1 generated an exception while executing task 1021
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at de.photon.AACAdditionPro.J.lambda$null$0(J.java)
	at java.util.ArrayList.removeIf(ArrayList.java:1405)
	at de.photon.AACAdditionPro.J.lambda$onJoin$2(J.java)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Rerd** [comment]
You should put this in the [AACAdditionPro Issue Tracker](https://github.com/Photon-GitHub/AACAdditionPro/issues) because it is an issue with AACAdditionPro which is the problem.

**Comment by konsolas** [comment]
See above
