### ISSUE TITLE
 Could not pass event EntityDamageByEntityEvent AAC 3.3.4

### ISSUE THREAD

**Issue by Xm4g1kZzXj0k3** [konsolas/AAC-Issues#1048]
Error in console:

[21:04:13 ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
	at me.konsolas.aac.bz.<init>(bz.java:78) ~[?:?]
	at me.konsolas.aac.cS.b(cS.java:42) ~[?:?]
	at me.konsolas.aac.y.a(y.java:58) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[prison.jar:git-Spigot-db6de12-07c3001]
	... 26 more
[21:04:13 ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
	at me.konsolas.aac.bz.<init>(bz.java:78) ~[?:?]
	at me.konsolas.aac.cS.b(cS.java:42) ~[?:?]
	at me.konsolas.aac.y.a(y.java:58) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[prison.jar:git-Spigot-db6de12-07c3001]
	... 26 more
[21:04:13 ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
	at me.konsolas.aac.bz.<init>(bz.java:78) ~[?:?]
	at me.konsolas.aac.cS.b(cS.java:42) ~[?:?]
	at me.konsolas.aac.y.a(y.java:58) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[prison.jar:git-Spigot-db6de12-07c3001]
	... 26 more
[21:04:15 ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
	at me.konsolas.aac.bz.<init>(bz.java:78) ~[?:?]
	at me.konsolas.aac.cS.b(cS.java:42) ~[?:?]
	at me.konsolas.aac.y.a(y.java:58) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[prison.jar:git-Spigot-db6de12-07c3001]
	... 26 more
[21:04:15 INFO]: Xm4g1kZzXj0k3 issued server command: /npc help 7
[21:04:15 ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [prison.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [prison.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [prison.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
	at me.konsolas.aac.bz.<init>(bz.java:78) ~[?:?]
	at me.konsolas.aac.cS.b(cS.java:42) ~[?:?]
	at me.konsolas.aac.y.a(y.java:58) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[prison.jar:git-Spigot-db6de12-07c3001]
	... 26 more

Server version: (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
AAC version: 3.3.4
ProtocolLib version: 4.2.1

**Comment by CeIebrimbor** [comment]
Try this: http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

When does this occur? Spam or only right at player join?

**Comment by Janmm14** [comment]
Old protocollib version. ProtocolLib 3.x is not supported.

**Comment by CeIebrimbor** [comment]
Did someone lie about their version being used? xD

**Comment by Janmm14** [comment]
Maybe not a lie, but two ProtocolLib jars in the plugins folder or something like that

**Comment by Xm4g1kZzXj0k3** [comment]
Hi!
Not spam or when player join... This error occur random... During next day
i find when plugin give me this error..
Thanks.

Il 28 Ott 2017 00:29, "Celebrimbor" <notifications@github.com> ha scritto:
