### ISSUE TITLE
I have error

### ISSUE THREAD

**Issue by sokrates1231** [konsolas/AAC-Issues#1065]
[13:27:44] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1112) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:860) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:748) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1382) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
	at me.konsolas.aac.cr.<init>(cr.java:86) ~[?:?]
	at me.konsolas.aac.V.b(V.java:17) ~[?:?]
	at me.konsolas.aac.t.a(t.java:186) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit.jar:git-PaperSpigot-"4c7641d"]
	... 27 more

**Comment by Janmm14** [comment]
Your ProtocolLib version is ancient.
