### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to AAC

### ISSUE THREAD

**Issue by smartmadio** [konsolas/AAC-Issues#1094]
### Issue description
```
[19:40:09] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityMonster.damageEntity(EntityMonster.java:48) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityGuardian.damageEntity(SourceFile:454) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1585) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchFieldError: ENTITY_SWEEP_ATTACK
	at me.konsolas.aac.z.b(z.java:48) ~[?:?]
	at me.konsolas.aac.bq.a(bq.java:150) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Server1.jar:git-Spigot-de459a2-9a98afb]
	... 25 more
[19:40:10] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityMonster.damageEntity(EntityMonster.java:48) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityGuardian.damageEntity(SourceFile:454) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1585) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Server1.jar:git-Spigot-de459a2-9a98afb]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchFieldError: ENTITY_SWEEP_ATTACK
	at me.konsolas.aac.z.b(z.java:48) ~[?:?]
	at me.konsolas.aac.bq.a(bq.java:150) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Server1.jar:git-Spigot-de459a2-9a98afb]
	... 25 more
```

### Core information
**Server version**: 1.10.2
**AAC version**: 3.3.5
**ProtocolLib version**: 4.2.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: 1.2.0
**ProtocolSupport version**:  N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**:  N/A

### Configuration
 I‘m using default config.

**Comment by CeIebrimbor** [comment]
Use...
http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by smartmadio** [comment]
I'v changed to use http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/,still have the same problem.

**Comment by CeIebrimbor** [comment]
Hmmmmm...one last try. 1.10 might be unique and fall into the 4.3.0 category.

http://ci.dmulloy2.net/job/ProtocolLib/373/

**Comment by smartmadio** [comment]
Still the same problem with ProtocolLib 4.3.0.

**Comment by Janmm14** [comment]
That field is not related to ProtocolLib and 1.9 + 1.10 servers suffer from this field being added in 1.11.2
