### ISSUE TITLE
CME@LinkedHashMap@AsyncChatEv@cf.a:6@cg.next:2 AAC v3.3.5

### ISSUE THREAD

**Issue by mckite** [konsolas/AAC-Issues#1118]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.5

**ProtocolLib version**:  4.3.0
(When Using 3.7 , more Error)

**Plugin list**: ProcotolLib, Massivelag, ect

### Special environment information
**ViaVersion version**:N

**ProtocolSupport version**: 4.23dev

**ViaBackwards version**: iN

**BungeeCord plugins**: N
### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".
```
[13:00:07 ERROR]: Could not pass event AsyncPlayerChatEvent to AAC v3.3.5
org.bukkit.event.EventException
        at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:79) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_152]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_152]
Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_152]
        at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_152]
        at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_152]
        at me.konsolas.aac.cf.a(cf.java:6) ~[?:?]
        at me.konsolas.aac.cg.next(cg.java:2) ~[?:?]
        at me.konsolas.aac.t.a(t.java:1) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor807.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
        at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:62)~[?:?]
        ... 11 more
```

**Comment by Janmm14** [comment]
Btw: You are supposed to delete the explanation text
