### ISSUE TITLE
Problem AAC

### ISSUE THREAD

**Issue by Trooox** [konsolas/AAC-Issues#1128]
```java
Error occurred while enabling AAC v3.3.7 (Is it up to date?)
java.lang.NullPointerException: null
at me.konsolas.iaac.c.<init>(c.java) ~[?:?]
at me.konsolas.iaac.b.b(b.java) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
at me.konsolas.aac.AAC.onEnable(AAC.java:50) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by Janmm14** [comment]
first idea: update java to latest java 8

**Comment by Trooox** [comment]
Hummmm All my plugins run with java 8 :/

**Comment by Janmm14** [comment]
well updating to the latest version of java 8 (i think its 8u152) is no problem but might solve this issue, as it looks like it is obfuscation-related

**Comment by Trooox** [comment]
Hello, I can't upgdate my Java because is not my machine ^^

**Comment by Trooox** [comment]
But before this bug I install AAC and he worked, that why I don't understand ...

**Comment by Janmm14** [comment]
Maybe try redowmloading and ask the owner to update java.
