### ISSUE TITLE
AAC not starting with latest 1.12.2

### ISSUE THREAD

**Issue by DaveDevil** [konsolas/AAC-Issues#1131]
AAC 3.3.7-b2
ProtocolLib v4.3.0
mc 1.12.2-R0.1-SNAPSHOT git-Spigot-b66ad9e-b5a10a9

AAC not enabling with this error:

```
[Server thread/ERROR]: Error occurred while enabling AAC v3.3.7 (Is it up to date?)
java.lang.NoClassDefFoundError: me/konsolas/iaac/b
	at me.konsolas.aac.AAC.onEnable(AAC.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: me.konsolas.iaac.b
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:146) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-b66ad9e-b5a10a9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 12 more
```

**Comment by Janmm14** [comment]
Try redownloading AAC and maybe check with a zip program that there is a file `b.class` in the folder `me/konsolas/iaac`

**Comment by DaveDevil** [comment]
no files in that folder on latest downloaded from spigot

http://prntscr.com/htzhmb

**Comment by Janmm14** [comment]
Oops, I'm sorry.
I had a different folder in my mind. That folder is always empty, oops.

**Comment by konsolas** [comment]
This is a file corruption error - please redownload AAC from spigot.

**Comment by DaveDevil** [comment]
I redownloaded it 4 times, still the same error, downloaded from different PCs

**Comment by Janmm14** [comment]
Java version?

**Comment by DaveDevil** [comment]
java version "1.8.0_151"

**Comment by konsolas** [comment]
This seems to be an isolated issue - @DaveDevil are you sure there aren't any antivirus programs modifying the file on download, perhaps?
