### ISSUE TITLE
CME@ah.onPacketReceiving:63 (PacketPlayInFlying$PacketPlayInPosition)

### ISSUE THREAD

**Issue by Pwnzeye** [konsolas/AAC-Issues#1238]
https://hastebin.com/edululoteq.lua

**Comment by Janmm14** [comment]
In case hastebin goes down again:
```
[23:19:31] [Netty Epoll Server IO #1/ERROR]: [AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_161]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1471) ~[?:1.8.0_161]
	at me.konsolas.aac.ah.onPacketReceiving(ah.java:63) ~[AAC(1).jar:3.3.11]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib(1).jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib(1).jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib(1).jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib(1).jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib(1).jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib(1).jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:543) [ProtocolLib(1).jar:4.4.0-SNAPSHOT-b390]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [latest.jar:git-Paper-1335]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [latest.jar:git-Paper-1335]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [latest.jar:git-Paper-1335]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [latest.jar:git-Paper-1335]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [latest.jar:git-Paper-1335]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:275) [ProtocolLib(1).jar:4.4.0-SNAPSHOT-b390]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [latest.jar:git-Paper-1335]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [latest.jar:git-Paper-1335]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [latest.jar:git-Paper-1335]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [latest.jar:git-Paper-1335]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [latest.jar:git-Paper-1335]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [latest.jar:git-Paper-1335]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [latest.jar:git-Paper-1335]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [latest.jar:git-Paper-1335]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [latest.jar:git-Paper-1335]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [latest.jar:git-Paper-1335]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [latest.jar:git-Paper-1335]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [latest.jar:git-Paper-1335]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[23:19:31] [Netty Epoll Server IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition@2300e0b7[
    x=861.0972415024205
    y=71.7531999805212
    z=462.6697436863107
    yaw=0.0
    pitch=0.0
    f=false
    hasPos=true
    hasLook=false
  ]
```
