### ISSUE TITLE
IllegalArgumentException@bf.a:12: Register object without watcher object

### ISSUE THREAD

**Issue by MatinDark** [konsolas/AAC-Issues#1240]
```
[17:27:05 WARN]: [AAC] Task #31585 for AAC v3.3.11 generated an exception
java.lang.IllegalArgumentException: You cannot register objects without a watcher object!
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:396) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:406) ~[ProtocolLib.jar:4.3.0]
        at me.konsolas.aac.bf.a(bf.java:12) ~[AAC.jar:3.3.11]
        at me.konsolas.aac.co.a(co.java:7) ~[AAC.jar:3.3.11]
        at me.konsolas.aac.co.a(co.java:14) ~[AAC.jar:3.3.11]
        at me.konsolas.aac.ah.lambda$onPacketSending$0(ah.java:74) ~[AAC.jar:3.3.11]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
```
### Core information
**Server version**: Paper Spigot 1.12.2

**AAC version**: 3.3.11

**ProtocolLib version**: 4.3.0

**Plugin list**: insert

### Special environment information
**ViaVersion version**: 1.3.0 (or N/A)

**ProtocolSupport version**: No (or N/A)

**ViaBackwards version**: No (or N/A)

**BungeeCord plugins**: Viaversion , premium vanish (or N/A)

**Comment by Janmm14** [comment]
btw. `latest` is no valid version because it can change

**Comment by MatinDark** [comment]
Updated

**Comment by DracarysPro** [comment]
Same
