### ISSUE TITLE
AAC v3.3.11 WrappedDataWatcher Problem

### ISSUE THREAD

**Issue by Blueeyestar** [konsolas/AAC-Issues#1249]
**since the new version I have this error generated in seconds clock !!!**

```
[39;0m> [K[33;1m[15:04:18 WARN]: [AAC] Task #7833274 for AAC v3.3.11 generated an exception java.lang.IllegalArgumentException: You cannot register objects without a watcher object!
 at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:396) ~[?:?]
 at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:406) ~[?:?]
 at me.konsolas.aac.bf.a(bf.java:12) ~[?:?] at me.konsolas.aac.co.a(co.java:7) ~[?:?]
 at me.konsolas.aac.co.a(co.java:14) ~[?:?] at me.konsolas.aac.ah.lambda$onPacketSending$0(ah.java:74) ~[?:?]
 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[minecraft_server.jar:git-Paper-1248] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [minecraft_server.jar:git-Paper-1248]
 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [minecraft_server.jar:git-Paper-1248]
 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [minecraft_server.jar:git-Paper-1248]
 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [minecraft_server.jar:git-Paper-1248]
 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [minecraft_server.jar:git-Paper-1248]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
 [39;0m> [K[33;1m[15:04:45 WARN]: [CommandWatcher] Plugin CommandWatcher v0.5 generated an exception while executing task 46
 java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
 at me.mcluke300.commandlistener.MetricsLite.postPlugin(MetricsLite.java:234) ~[?:?]
 at me.mcluke300.commandlistener.MetricsLite.access$4(MetricsLite.java:225) ~[?:?]
 at me.mcluke300.commandlistener.MetricsLite$1.run(MetricsLite.java:143) ~[?:?]
 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[minecraft_server.jar:git-Paper-1248]
 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [minecraft_server.jar:git-Paper-1248]
 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [minecraft_server.jar:git-Paper-1248]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by konsolas** [comment]
of #1240

**Comment by Janmm14** [comment]
second error not from aac
