### ISSUE TITLE
NPE@bs.a:4

### ISSUE THREAD

**Issue by PatoTheBest** [konsolas/AAC-Issues#1293]
### Issue description

```
java.lang.NullPointerException
        at me.konsolas.aac.bs.a(bs.java:4)
        at me.konsolas.aac.br.a(br.java:186)
        at me.konsolas.aac.bb.b(bb.java:152)
        at me.konsolas.aac.bb.a(bb.java:103)
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor361.execute(Unknown:-1)
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:618)
        at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126)
        at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839)
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
        at java.lang.Thread.run(Thread.java:748)
```
Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: 1.12

**AAC version**: 3.3.12

**ProtocolLib version**:  ¿v4.3.0

**Plugin list**: 
Loaded Plugins
[
  "CleanroomGenerator v1.0.0",
  "LuckPerms v3.4.15",
  "ProjectileDamage v0.1",
  "BukkitBugSnag v1.1.3",
  "Craftconomy3 v3.3.1-d99cf63-trv200",
  "Vault v1.5.6-b49",
  "ProtocolSupport v4.26.dev",
  "ProtocolLib v4.3.0",
  "MassiveCore v2.13.0-SNAPSHOT",
  "SkyWars v1.0-SNAPSHOT",
  "AAC v3.3.12",
  "MassiveCombat v2.13.0-SNAPSHOT",
  "ChatControl v7.6.13",
  "SkyWarsAddon v1.0",
  "ConditionalCommands v1.4",
  "AACAdditionPro v3.10.0"
]

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: v4.26.dev

**ViaBackwards version**: N/A

**BungeeCord plugins**:  ViaVersion

### Configuration

Celebrimbor's optimized config

**Comment by Janmm14** [comment]
Just noting the first li e of the issue seems to be missing, shouldn't affect fixing however.
