### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by PeachesMLG** [konsolas/AAC-Issues#1366]
Hi, Im getting spammed errors in the console due to some classes not running:

[CODE]Caused by: java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
[21:03:37 WARN]:        at me.konsolas.aac.u.<init>(u.java:6)
[21:03:37 WARN]:        ... 12 more
[21:03:38 WARN]: java.lang.reflect.InvocationTargetException
[21:03:38 WARN]:        at sun.reflect.GeneratedConstructorAccessor97.newInstance(Unknown Source)
[21:03:38 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:03:38 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:03:38 WARN]:        at me.konsolas.aac.N.b(N.java:94)
[21:03:38 WARN]:        at me.konsolas.aac.aM.lambda$new$0(aM.java:4)
[21:03:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[21:03:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[21:03:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785)
[21:03:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[21:03:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
[21:03:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618)
[21:03:38 WARN]:        at java.lang.Thread.run(Unknown Source)
[21:03:38 WARN]: Caused by: java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
[21:03:38 WARN]:        at me.konsolas.aac.u.<init>(u.java:6)
[21:03:38 WARN]:        ... 12 more[/CODE]

Running PaperSpigot 1.8.8

**Comment by Janmm14** [comment]
Do not use ancient ProtocolLib version. Update to 4.2.0 for 1.8-1.10 servers.
