### ISSUE TITLE
NPE@X.b:3@aF.a:116 - Compatibility with NPC

### ISSUE THREAD

**Issue by Xuwznln** [konsolas/AAC-Issues#1383]
### Issue description
```
[19:09:14] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.14
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[spigot.jar:git-Paper-1421]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-Paper-1421]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Paper-1421]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [spigot.jar:git-Paper-1421]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [spigot.jar:git-Paper-1421]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) [spigot.jar:git-Paper-1421]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:581) [spigot.jar:git-Paper-1421]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:484) [spigot.jar:git-Paper-1421]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:613) [spigot.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1369) [spigot.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:887) [spigot.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [spigot.jar:git-Paper-1421]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:204) [spigot.jar:git-Paper-1421]
	at org.mcmonkey.sentinel.SentinelTrait.punch(SentinelTrait.java:805) [sentinel-1.4.5.jar:?]
	at org.mcmonkey.sentinel.SentinelTrait.tryAttack(SentinelTrait.java:1357) [sentinel-1.4.5.jar:?]
	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1871) [sentinel-1.4.5.jar:?]
	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:2007) [sentinel-1.4.5.jar:?]
	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:425) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:156) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [spigot.jar:git-Paper-1421]
	at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1036) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.util.NMS.tick(NMS.java:298) [citizens-2.0.22-SNAPSHOT.jar:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [citizens-2.0.22-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) [spigot.jar:git-Paper-1421]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [spigot.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [spigot.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [spigot.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [spigot.jar:git-Paper-1421]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-Paper-1421]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at me.konsolas.aac.X.b(X.java:3) ~[?:?]
	at me.konsolas.aac.aF.a(aF.java:116) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1475.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[spigot.jar:git-Paper-1421]
	... 31 more
```

### Core information
**Server version**: 1.12.2 paper

**AAC version**: 3.3.14

**ProtocolLib version**: 4.3.0

**Plugin list**: Citizen Sentinel AAC

### Special environment information
**ProtocolSupport version**: Build Number 229

### Configuration
Celebrimbor's config

**Comment by xion87** [comment]
The error is fixed but AAC is checking citizens NPC
[04-08-2018 12:02:40.263] BOT_Veltta failed Knockback: didn't move away from his attacker when hit [ping:1 tps:19.91] VL:25

**Comment by Janmm14** [comment]
In that case give them bypass permissions.

**Comment by xion87** [comment]
how?

**Comment by Janmm14** [comment]
Well, maybe the plugins allows that. Or other plugins do allow that. AAC does not check for citizens / sentinel. (Wolud be advertised and such a problem wouldn't exist.
