### ISSUE TITLE
Cannot measure distance between worlds@bR.a:122 v3.3.15

### ISSUE THREAD

**Issue by variationtime** [konsolas/AAC-Issues#1421]
### Core information
**Server version**: 1.8.9

**AAC version**: 3.3.15

**ProtocolLib version**: 4.4.0-SNAPSHOT-b403

**Plugin list**: custom plugins and AAC, ViaVersion, ProtocolLib

**ViaVersion version**: 1.4.0

use Celembrimbor config.

The problem on the minigames server (like skywars), when the player right in the middle of the game get teleported to the waiting lobby, in another world, so it's breaks our games plugins and game in general.

[AAC] Task #29 for AAC v3.3.15 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between West and lobby
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[lwt-17.jar:git-Spigot-21fe707-e1ebe52]
	at me.konsolas.aac.bR.a(bR.java:122) ~[?:?]
	at me.konsolas.aac.cF.b(cF.java:137) ~[?:?]
	at me.konsolas.aac.cF.lambda$null$4(cF.java:31) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_151]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_151]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_151]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_151]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_151]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_151]
	at me.konsolas.aac.cF.lambda$new$5(cF.java:16) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[lwt-17.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [lwt-17.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [lwt-17.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [lwt-17.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [lwt-17.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [lwt-17.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by variationtime** [comment]
any help?
