### ISSUE TITLE
Error trying to add locations of different worlds@I.a:97@I.a:108@PlayerInteractEvent

### ISSUE THREAD

**Issue by MatinDark** [konsolas/AAC-Issues#1422]
```
[00:31:19] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AAC v3.4.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1500]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1500]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1500]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1500]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1500]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1500]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:485) ~[patched_1.12.2.jar:git-Paper-1500]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:992) ~[patched_1.12.2.jar:git-Paper-1500]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1500]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1500]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1500]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1500]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) [patched_1.12.2.jar:git-Paper-1500]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1500]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [patched_1.12.2.jar:git-Paper-1500]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1500]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: Cannot add Locations of differing worlds
	at org.bukkit.Location.subtract(Location.java:373) ~[patched_1.12.2.jar:git-Paper-1500]
	at me.konsolas.aac.I.a(I.java:97) ~[AAC.jar:3.4.0]
	at me.konsolas.aac.I.a(I.java:108) ~[AAC.jar:3.4.0]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor422.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1500]
	... 18 more
```
### Core information
**Server version**: PaperSpigot 1.12.2

**AAC version**: 3.4.0

**ProtocolLib version**: Lastest Stable Build

**Plugin list**: Request Via Discord (#Matin_Dark#7189)

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: (N/A)

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: Request Via Discord (#Matin_Dark#7189)

**Comment by Janmm14** [comment]
Slightly differnet stack from issue 1423 
```
 ERROR Could not pass event PlayerInteractEvent to AAC v3.4.0
23.07 17:44:01 [Server] INFO org.bukkit.event.EventException: null
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:460) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
23.07 17:44:01 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151] 23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
23.07 17:44:01 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot add Locations of differing worlds
23.07 17:44:01 [Server] INFO at org.bukkit.Location.subtract(Location.java:373) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at me.konsolas.aac.I.a(I.java:97) ~[?:?] 23.07 17:44:01 [Server] INFO at me.konsolas.aac.I.a(I.java:108) ~[?:?]
23.07 17:44:01 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor413.execute(Unknown Source) ~[?:?]
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper-1488.jar:git-Paper-1488]
```

**Comment by cuervito** [comment]
hello, I get the same, error, how do you fix friend?

**Comment by konsolas** [comment]
in favor of #1479
