### ISSUE TITLE
Error spamming my console

### ISSUE THREAD

**Issue by PeachesMLG** [konsolas/AAC-Issues#1506]
> [17:00:21 ERROR]: Could not pass event PlayerViolationEvent to AAC v3.5.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at me.konsolas.aac.c9.a(c9.java:3) [AAC.jar:3.5.0]
at me.konsolas.aac.h.a(h.java:13) [AAC.jar:3.5.0]
at me.konsolas.aac.o.b(o.java:12) [AAC.jar:3.5.0]
at me.konsolas.aac.cr.a(cr.java:26) [AAC.jar:3.5.0]
at sun.reflect.GeneratedMethodAccessor548.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:594) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:507) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:626) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1160) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:871) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:794) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:812) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:507) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1013) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1089) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1371) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: com.gmail.nossr50.api.AbilityAPI.isBleeding(Lorg/bukkit/entity/LivingEntity;)Z
at me.konsolas.aac.f.a(f.java:4) ~[?:?]
at sun.reflect.GeneratedMethodAccessor480.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
... 39 more
> [17:00:21 INFO]: CarbajosaPvP issued server command: /f show jihadis
> [17:00:21 ERROR]: Could not pass event PlayerViolationEvent to AAC v3.5.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at me.konsolas.aac.c9.a(c9.java:3) [AAC.jar:3.5.0]
at me.konsolas.aac.h.a(h.java:13) [AAC.jar:3.5.0]
at me.konsolas.aac.o.b(o.java:12) [AAC.jar:3.5.0]
at me.konsolas.aac.cr.a(cr.java:26) [AAC.jar:3.5.0]
at sun.reflect.GeneratedMethodAccessor548.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:594) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:507) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:626) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1160) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:871) [BeerSpigot.jar:gi

### Core information
**Server version**: 1.8.8 (BEER SPIGOT PREMIUM)

**AACversion**: 
Latest(3.5.0)

**ProtocolLib version**: 
4.3.0

**Comment by Janmm14** [comment]
I guess you might want to update MCMMO
