### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by LogGits** [konsolas/AAC-Issues#1556]
### Issue description
Yeah idk what happened i just got this in console randomly, so i thought i'd report it.
```
ERROR 26/11/2018 10:40:15
10:40:15Could not pass event BlurredBlockBreakEvent to AAC v3.6.4
Console 26/11/2018 10:40:15
10:40:15org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-456]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-456]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-456]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-456]
at net.poweredbyhate.wildtp.TeleportGoneWild.n0tAGreifClam(TeleportGoneWild.java:250) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild.chekar(TeleportGoneWild.java:204) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild$1$1.call(TeleportGoneWild.java:162) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild$1$1.call(TeleportGoneWild.java:158) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftFuture.run(CraftFuture.java:85) ~[patched_1.13.2.jar:git-Paper-456]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-456]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@36af0146
at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at me.konsolas.aac.bL.b(bL.java:50) ~[?:?]
at me.konsolas.aac.bL.a(bL.java:2) ~[?:?]
at me.konsolas.aac.cL.a(cL.java:153) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1072.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-456]
... 14 more
```

### Core information
**Server version**:  paperspigot 1.13.2 build 456

**AAC version**: 3.6.4

**ProtocolLib version**: v4.4.0

Using cele's config but i dont think that plays a factor.

**Comment by Janmm14** [comment]
This exception actually could cause teleportgonewild plugin to **not** fail finding a suitable teleport position, because aac did not rejected the event.

If wild teleport does still work for you because of this error of course.

**Comment by LogGits** [comment]
Error occurs when going through a water portal. This is the plugin: https://www.spigotmc.org/resources/wilderness-tp-cyber-monday-sale-250-off-the-one-true-wild-tp.22853/
