### ISSUE TITLE
Server freeze

### ISSUE THREAD

**Issue by tetratec** [konsolas/AAC-Issues#1584]
### Issue description

The server freezes and stops letting players

[14:39:43] [Server thread/INFO]: karimd lost connection: §eSpeed
[14:39:43] [Server thread/WARN]: handleDisconnection() called twice
[14:40:14] [Thread-150/WARN]: Exception in thread "Thread-150"
[14:40:14] [Thread-150/WARN]: java.lang.ClassCastException: java.lang.reflect.Method cannot be cast to java.lang.String
[14:40:14] [Thread-150/WARN]: 	at me.konsolas.aac.dq.a(Unknown Source)
[14:40:14] [Thread-150/WARN]: 	at me.konsolas.aac.dq.d(Unknown Source)
[14:40:14] [Thread-150/WARN]: 	at me.konsolas.aac.dq.a(Unknown Source)
[14:40:14] [Thread-150/WARN]: 	at me.konsolas.aac.dq.run(Unknown Source)

**jstack server process**: https://gist.github.com/tetratec/9ae05f3ab03f22fcd47dddc46ac07f65

### Core information
**Server version**: git-PaperSpigot-"4c7641d" (MC: 1.8.8)

**AAC version**: 3.6.4

**ProtocolLib version**: v4.3.0

### Special environment information
**ViaVersion version**: 1.6.0

**ProtocolSupport version**: No

**ViaBackwards version**: No

**BungeeCord plugins**: LiteAnnouncer

**Comment by Janmm14** [comment]
1. Do you use OpenJDK or OracleJDK on your server? (Try with oracle jdk if you use openjdk)
2. Did you buy AAC?
3. Do you have a profiler or something similar attached at the time of the error?

This error is caused by the obfuscation. 

Either it detected some unauthorized modification or it is a bug.

It blocked all netty threads. A temporary

**Comment by tetratec** [comment]
> 1. Do you use OpenJDK or OracleJDK on your server? (Try with oracle jdk if you use openjdk)
> 2. Did you buy AAC?
> 3. Do you have a profiler or something similar attached at the time of the error?
> 
> This error is caused by the obfuscation.
> 
> Either it detected some unauthorized modification or it is a bug.
> 
> It blocked all netty threads. A temporary woraround could be to inrease netty threads in spigot config.

1. I use OracleJDK Java HotSpot (TM) 64-Bit VM Server (build 25.181-b13, mixed mode)
2. yes
3. no, I used jstack to get detailed information about threads

Now in spigot.yml netty-threads: 4

**Comment by tetratec** [comment]
https://gist.github.com/tetratec/18eb081a2a578d5664394d85b87948c7

**Comment by tetratec** [comment]
```[14:10:27 WARN]: [AAC] Task #35 for AAC v3.6.4 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.cB
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_181]
        at me.konsolas.aac.cC.a(cC.java:175) ~[?:?]
        at me.konsolas.aac.b1.lambda$new$0(b1.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[14:10:28 WARN]: java.lang.reflect.InvocationTargetException
[14:10:28 WARN]:        at sun.reflect.GeneratedConstructorAccessor36.newInstance(Unknown Source)
[14:10:28 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:10:28 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:10:28 WARN]:        at me.konsolas.aac.cC.a(cC.java:122)
[14:10:28 WARN]:        at me.konsolas.aac.b1.lambda$new$0(b1.java:21)
[14:10:28 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[14:10:28 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[14:10:28 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[14:10:28 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[14:10:28 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[14:10:28 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[14:10:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[14:10:28 WARN]: Caused by: java.lang.NullPointerException
[14:10:28 WARN]:        at me.konsolas.aac.cw.a(Unknown Source)
[14:10:28 WARN]:        at me.konsolas.aac.c2.<init>(c2.java:12)
[14:10:28 WARN]:        ... 12 more```

**Comment by Janmm14** [comment]
I'M sorry I cannot help you here. I suggest you try to redownload aac

**Comment by tetratec** [comment]
It does not help

**Comment by TrinityThiemo** [comment]
After a few months, this issue is still here.
`[14:33:40] [Thread-37/WARN]: Exception in thread "Thread-37" 
[14:33:40] [Thread-37/WARN]: java.lang.ClassCastException: java.lang.reflect.Method cannot be cast to java.lang.String
[14:33:40] [Thread-37/WARN]:     at me.konsolas.aac.b4.a(Unknown Source)
[14:33:40] [Thread-37/WARN]:     at me.konsolas.aac.b4.d(Unknown Source)
[14:33:40] [Thread-37/WARN]:     at me.konsolas.aac.b4.a(Unknown Source)
[14:33:40] [Thread-37/WARN]:     at me.konsolas.aac.b4.run(Unknown Source)`

Complete freeze of the whole server.
