### ISSUE TITLE
Warn

### ISSUE THREAD

**Issue by DenisJ9798** [konsolas/AAC-Issues#1622]
[14:24:52 WARN]: Exception in thread "Thread-46" java.lang.ClassCastException: java.lang.reflect.Method cannot be cast to java.lang.String
[14:24:52 WARN]:        at me.konsolas.aac.cS.a(Unknown Source)
[14:24:52 WARN]:        at me.konsolas.aac.cS.d(Unknown Source)
[14:24:52 WARN]:        at me.konsolas.aac.cS.a(Unknown Source)
[14:24:52 WARN]:        at me.konsolas.aac.cS.run(Unknown Source)

**Comment by CeIebrimbor** [comment]
The entire report template was tossed...try again.

**Comment by DenisJ9798** [comment]
I didn't understand

**Comment by Janmm14** [comment]
When you create an issue, the text field is pre-filled with a template.
You are not meant to just delete that text...

Apart from that, this error could possibly be fixed by updating java or using a newer version of AAC.

**Comment by DenisJ9798** [comment]
> When you create an issue, the text field is pre-filled with a template.
> You are not meant to just delete that text...
> 
> Apart from that, this error could possibly be fixed by updating java or using a newer version of AAC.

Update java to what version?

**Comment by Janmm14** [comment]
Newest java 8
