### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#1652]
I got 3 servers, two in Hetzner DC, one in OVH. Can't run AAC on any of them.
Error:

```
[00:52:42] [Server thread/INFO]: [AAC] Enabling AAC v4.0.3
[00:52:43] [Server thread/WARN]: [AAC] No internet connection
[00:52:43] [Server thread/WARN]: [AAC] Server will start in 20 seconds.
[00:53:04] [Server thread/INFO]: [AAC] Enabled: [combat.Criticals, combat.Hitbox, combat.FastBow, combat.FightSpeed, combat.Regen, combat.FastUse, combat.Killaura, movement.Timer, movement.Phase, movement.Move, movement.NoFall, movement.Derp, world.BadPackets, world.FastBreak, world.FastPlace, world.Interact]
[00:53:15] [Craft Scheduler Thread - 16/ERROR]: [AAC] Network interference detected.
[00:53:15] [Craft Scheduler Thread - 16/INFO]: [AAC] Disabling AAC v4.0.3[00:53:15] [Craft Scheduler Thread - 16/INFO]: [AAC] Saving log file...
[00:53:15] [AAC Logging I/O Thread/INFO]: [AAC] Thread AAC-LogWriter exiting
[00:53:15] [Craft Scheduler Thread - 16/WARN]: [AAC] Plugin AAC v4.0.3 generated an exception while executing task 73
java.lang.NullPointerException: null
	at me.konsolas.aac.aF.run(Native Method) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[ClassicMC.jar:git-Paper-453]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[ClassicMC.jar:git-Paper-453]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[ClassicMC.jar:git-Paper-453]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by konsolas** [comment]
4.0.4

**Comment by Baterka** [comment]
Still not fixed

**Comment by Janmm14** [comment]
@Baterka Please create a new issue and post your log in that new issue
