### ISSUE TITLE
NPE on /gamemode

### ISSUE THREAD

**Issue by SlimeDog** [konsolas/AAC-Issues#1653]
### Issue description
Only one player on test server. Changed gamemode. Could not reproduce, but NPE should be caught.
```
[15:47:30] [Server thread/INFO]: PLAYER_ID_ELIDED issued server command: /gamemode survival
[15:47:30] [Server thread/WARN]: [AAC] Task #58 for AAC v4.0.4 generated an exception
java.lang.NullPointerException: null
        at me.konsolas.aac.bt.lambda$tick$3(bt.java:90) ~[?:?]
        at me.konsolas.aac.bt.lambda$forAllPlayers$2(bt.java:32) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at me.konsolas.aac.bt.a(bt.java:68) ~[?:?]
        at me.konsolas.aac.bt.a(bt.java:20) ~[?:?]
        at me.konsolas.aac.df.a(Native Method) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar-2019-07-26-2053:git-Spigot-1981d55-3e7b386]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar-2019-07-26-2053:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1021) [spigot-1.14.4.jar-2019-07-26-2053:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar-2019-07-26-2053:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:969) [spigot-1.14.4.jar-2019-07-26-2053:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:814) [spigot-1.14.4.jar-2019-07-26-2053:git-Spigot-1981d55-3e7b386]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Core information
**Server version**: Spigot 1.14.4 (Jenkins 2423) git-Spigot-1981d55-3e7b386 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**AAC version**: 4.0.4

**ProtocolLib version**: 4.5.0-b9

**Plugin list**: 

### Special environment information
**ViaVersion version**: [2.1.3, but 1.14.4 client attached to 1.14.4 server]

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration
Default except
```
fightspeed:
  enabled: false
...
hitbox:
  max_reach: 14.1
```

**Comment by konsolas** [comment]
Fixed in 4.0.7
