### ISSUE TITLE
PlayerMoveEvent high cpu usage

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#1654]
![image](https://user-images.githubusercontent.com/12672902/62009715-b13d3280-b162-11e9-81ab-bd59bcddd9ac.png)

~100 players online
1.8.8 server
AAC 4.0.4
using ViaVersion up to 1.14.4

**Comment by Xayanix** [comment]
+

```
[18:04:14] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AAC v4.0.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Player riding ARMOR_STAND
	at me.konsolas.aac.c8.<init>(c8.java:124) ~[?:?]
	at me.konsolas.aac.br.a(br.java:216) ~[?:?]
	at me.konsolas.aac.df.a(df.java:132) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	... 16 more
```

**Comment by BestMark** [comment]
Try AAC 4.0.5

**Comment by Xayanix** [comment]
Ah, didn't notice update.

**Comment by konsolas** [comment]
It turns out Spigot classifies ARMOR_STAND as a LivingEntity. This I was not expecting.

**Comment by konsolas** [comment]
In relation to performance: Please try AAC 3.0.5. If necessary, you can also set move.async to true which will further reduce load on the main thread.

**Comment by Xayanix** [comment]
![image](https://user-images.githubusercontent.com/12672902/62012698-ee68eb00-b189-11e9-8695-5c6e89f40cf3.png)
Also

**Comment by Xayanix** [comment]
https://pastebin.com/mrKnq8mW

**Comment by Janmm14** [comment]
Do you have move async on? A possible solution to this would be to turn it off.

**Comment by Xayanix** [comment]
Yeah, turned it for a try

**Comment by konsolas** [comment]
4.0.6 fixes that ARMOR_STAND issue and improves move.async. 

I believe performance of the move check is fairly reasonable now, even with move.async off.
