### ISSUE TITLE
Unsupported version 4 and 5

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#1682]
```
[19:21:27] [Server thread/WARN]: [AAC] Task #74 for AAC v4.0.7 generated an exception
java.lang.IllegalArgumentException: Unsupported protocol version: 4
	at me.konsolas.aac.X.a(X.java:32) ~[?:?]
	at me.konsolas.aac.X.a(X.java:4) ~[?:?]
	at me.konsolas.aac.G.<init>(G.java:9) ~[?:?]
	at me.konsolas.aac.cA.b(cA.java:10) ~[?:?]
	at me.konsolas.aac.h.a(h.java:234) ~[?:?]
	at me.konsolas.aac.bZ.a(bZ.java:25) ~[?:?]
	at me.konsolas.aac.b6.a(b6.java:21) ~[?:?]
	at me.konsolas.aac.h.h(h.java:212) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[19:21:27] [Server thread/WARN]: [AAC] Task #74 for AAC v4.0.7 generated an exception
java.lang.IllegalArgumentException: Unsupported protocol version: 4
	at me.konsolas.aac.X.a(X.java:32) ~[?:?]
	at me.konsolas.aac.X.a(X.java:4) ~[?:?]
	at me.konsolas.aac.G.<init>(G.java:9) ~[?:?]
	at me.konsolas.aac.cA.b(cA.java:10) ~[?:?]
	at me.konsolas.aac.h.a(h.java:234) ~[?:?]
	at me.konsolas.aac.bZ.a(bZ.java:25) ~[?:?]
	at me.konsolas.aac.bZ.a(bZ.java:129) ~[?:?]
	at me.konsolas.aac.h.h(h.java:212) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [MegaDrop.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

Logs are spammed with it. Protocol 1.7.x is affected.
Worked fine before this update.

**Comment by BestMark** [comment]
1.7.x is not supported, see https://www.spigotmc.org/resources/aac-advanced-anti-cheat-hack-kill-aura-blocker.6442/
"AAC does not and will never support 1.7 or earlier versioning."

**Comment by Xayanix** [comment]
Sure m8, but server is 1.8.8 and viaversion is supported.
It was fine before this update.

What's the problem with threating 1.7.x version as 1.8.8?
Just stop throwing this exception.

**Comment by Janmm14** [comment]
ViaVersion does not allow 1.7 clients to join 1.8 server.
Generally AAC does not support 1.7, neither client nor server.

I think maybe AAC can change this behaviour to output a huge one-time-warning about unsupported client version and then treat lower client versions as 1.8 and higher client versions than known as 1.14

**Comment by konsolas** [comment]
4.0.8 (unrecognised versions will be treated as 1.8)
