### ISSUE TITLE
Could not pass event PlayerMoveEvent to AAC v4.0.7

### ISSUE THREAD

**Issue by Josha28** [konsolas/AAC-Issues#1687]
### Core information
**Server version**: spigot 1.14

**AAC version**: 4.07 and 4.0.7-b1

**ProtocolLib version**: 4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
Need the full stack trace.

**Comment by Josha28** [comment]
https://pastebin.com/0zDSw9sU

**Comment by konsolas** [comment]
Can you update Spigot to 1.14.4?

**Comment by Trikolon** [comment]
```
[20:43:29] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AAC v4.0.7
java.lang.IllegalArgumentException: Player riding SKELETON_HORSE
        at me.konsolas.aac.J.<init>(J.java:9) ~[?:?]
        at me.konsolas.aac.bU.a(bU.java:158) ~[?:?]
        at me.konsolas.aac.h.a(h.java:241) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor339.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-156]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-156]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-156]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:443) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.PacketPlayInVehicleMove.a(SourceFile:48) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.PacketPlayInVehicleMove.a(SourceFile:9) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-156]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```
Paper 1.14.4, ProtocolLib
AAC 4.0.7-b1

**Comment by Josha28** [comment]
it works for 1.14.4 but i can't really make the server 1.14.4
it needs to be 1.14

**Comment by konsolas** [comment]
AAC doesn't support 1.14
