### ISSUE TITLE
4.0.11-b1 not working

### ISSUE THREAD

**Issue by ehte89** [konsolas/AAC-Issues#1715]
### Issue description

[05:46:52] [Server thread/ERROR]: Could not load 'plugins\AAC-4.0.11-b1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.reload(CraftServer.java:808) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.Bukkit.reload(Bukkit.java:576) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:695) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        ... 14 more
Caused by: java.lang.RuntimeException: Failed to load
        at net.konsolas.jnic.internal.NLDR.load(Unknown Source) ~[?:?]
        at me.konsolas.aac.AAC.<clinit>(AAC.java) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        ... 14 more

### Core information
**Server version**:  1.14.4

**AAC version**: 4.0.11-b1

**ProtocolLib version**: 4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by Janmm14** [comment]
Please download &;install java 64 bit
