### ISSUE TITLE
onPacketSending exception

### ISSUE THREAD

**Issue by LogGits** [konsolas/AAC-Issues#1728]
### Issue description
Random error on console after a use used `/back`
```
[23:21:32] [Server thread/ERROR]: [AAC] Unhandled exception occured in onPacketSending(PacketEvent) for AAC
java.lang.NullPointerException: null
	at me.konsolas.aac.bw.a(bw.java:2) ~[?:?]
	at me.konsolas.aac.aj.a(aj.java:21) ~[?:?]
	at me.konsolas.aac.bb.a(bb.java:22) ~[?:?]
	at me.konsolas.aac.bb.onPacketSending(bb.java:3) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:209) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:172) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1506) ~[?:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1479) ~[?:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerConnection.internalTeleport(PlayerConnection.java:1182) ~[?:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerConnection.teleport(PlayerConnection.java:1147) ~[?:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:725) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:755) ~[patched_1.13.2.jar:git-Paper-639]
	at com.Zrips.CMI.Modules.tp.Teleportations.finalizeTeleport(Teleportations.java:508) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:334) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:299) ~[?:?]
	at com.Zrips.CMI.commands.list.back.perform(back.java:76) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[?:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[?:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-639]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-639]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[23:21:32] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_13_R2.PacketPlayOutPosition@669d220b[
    a=52.392612543472154
    b=59.0
    c=64.21339894933558
    d=272.82898
    e=-3.4914467
    f=[]
    g=6
  ]
```

### Core information
**Server version**: 1.13.2 paper build 639

**AAC version**: 4.1.2

**ProtocolLib version**: ProtocolLib v4.4.0

### Special environment information
**ViaVersion version**: ?? 2.2.0

### Configuration:
**Cele's config**

**Comment by konsolas** [comment]
4.1.4
