### ISSUE TITLE
java.lang.LinkageError: duplicate class definition

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#1753]
Trying AAC v4 for the first time (latest version 4.1.7), but getting the error below.

I'm using Spigot 1.8.8 with latest ViaVersion, ViaRewind, ViaRewind-Legacy-Support, and ProtocolLib. 
Problem still happens without ViaRewind and ViaRewind-Legacy-Support,
Don't have any Java profilers attached.

```[27-08-2019 16:15:23] [Server thread/INFO]: [AAC] Attempting to inject into PlayerConnection
[27-08-2019 16:15:23] [Server thread/ERROR]: Could not load 'plugins/AAC-4.1.7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.konsolas.aac.aW.a(Native Method) ~[?:?]
	at me.konsolas.aac.aW.run(Native Method) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java:26) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at me.konsolas.aac.aW.a(Native Method) ~[?:?]
	at me.konsolas.aac.aW.run(Native Method) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java:26) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	... 6 more
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "net/minecraft/server/v1_8_R3/PlayerConnection"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at me.konsolas.aac.aW.a(Native Method) ~[?:?]
	at me.konsolas.aac.aW.run(Native Method) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java:26) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	... 6 more```

**Comment by konsolas** [comment]
AAC now makes a few modifications to the server on startup. It can't be loaded dynamically - the server needs to be fully restarted.

Could this be the issue?

**Comment by MedicOP** [comment]
@konsolas I never use the reload command if that's what you're asking

**Comment by Janmm14** [comment]
Also not used plugman or sth similar?

**Comment by konsolas** [comment]
Loading AAC with plugman will also break things.

**Comment by MedicOP** [comment]
No I'm not using plugman, literally just starting the server normally.

**Comment by konsolas** [comment]
Are you using a modified version of Spigot? 
Did you have any plugins on the server except AAC and ProtocolLib?
Are you using the recommended version of ProtocolLib for 1.8.8?

**Comment by MedicOP** [comment]
Nope, clean Spigot 1.8.8
Just tried it with only AAC and ProtocolLib and it still happened
Yes. Using the latest version

**Comment by konsolas** [comment]
Well this is very strange. What's the output of `java -version`?

**Comment by MedicOP** [comment]
```# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

**Comment by konsolas** [comment]
Is there any particular reason you're using OpenJDK over oracle's java 8 implementation? I doubt it's the cause but it might be worth a shot.

**Comment by MedicOP** [comment]
No particular reason, that's just what's default in CentOS's yum repository

**Comment by MedicOP** [comment]
Full startup logs with only AAC 4.1.7 and ProtocolLib 4.4.0

```
[28-08-2019 10:10:52] [Server thread/INFO]: Starting minecraft server version 1.8.8
[28-08-2019 10:10:52] [Server thread/INFO]: Loading properties
[28-08-2019 10:10:52] [Server thread/INFO]: Default game type: SURVIVAL
[28-08-2019 10:10:52] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-5073b0f-07c3001 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[28-08-2019 10:10:52] [Server thread/INFO]: Debug logging is disabled
[28-08-2019 10:10:52] [Server thread/INFO]: Server Ping Player Sample Count: 12
[28-08-2019 10:10:52] [Server thread/INFO]: Using 3 threads for Netty based IO
[28-08-2019 10:10:52] [Server thread/INFO]: Generating keypair
[28-08-2019 10:10:52] [Server thread/INFO]: Starting Minecraft server on *:1336
[28-08-2019 10:10:52] [Server thread/INFO]: Using epoll channel type
[28-08-2019 10:10:52] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[28-08-2019 10:10:52] [Server thread/INFO]: [AAC] Attempting to inject into PlayerConnection
[28-08-2019 10:10:53] [Server thread/ERROR]: Could not load 'plugins/AAC-4.1.7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.konsolas.aac.aW.a(Native Method) ~[?:?]
	at me.konsolas.aac.aW.run(Native Method) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java:26) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at me.konsolas.aac.aW.a(Native Method) ~[?:?]
	at me.konsolas.aac.aW.run(Native Method) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java:26) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	... 6 more
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "net/minecraft/server/v1_8_R3/PlayerConnection"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at me.konsolas.aac.aW.a(Native Method) ~[?:?]
	at me.konsolas.aac.aW.run(Native Method) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java:26) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	... 6 more
[28-08-2019 10:10:53] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0
[28-08-2019 10:10:53] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0
[28-08-2019 10:10:53] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[28-08-2019 10:10:53] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[28-08-2019 10:10:53] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[28-08-2019 10:10:53] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[28-08-2019 10:10:53] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[28-08-2019 10:10:53] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[28-08-2019 10:10:53] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[28-08-2019 10:10:53] [Server thread/INFO]: Preparing level "world"
[28-08-2019 10:10:53] [Server thread/ERROR]: Could not set generator for default world 'world': Plugin 'CleanroomGenerator' does not exist
[28-08-2019 10:10:53] [Server thread/INFO]: -------- World Settings For [world] --------
[28-08-2019 10:10:53] [Server thread/INFO]: Anti X-Ray: false
[28-08-2019 10:10:53] [Server thread/INFO]: 	Engine Mode: 1
[28-08-2019 10:10:53] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[28-08-2019 10:10:53] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[28-08-2019 10:10:53] [Server thread/INFO]: Cactus Growth Modifier: 100%
[28-08-2019 10:10:53] [Server thread/INFO]: Cane Growth Modifier: 100%
[28-08-2019 10:10:53] [Server thread/INFO]: Melon Growth Modifier: 100%
[28-08-2019 10:10:53] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[28-08-2019 10:10:53] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[28-08-2019 10:10:53] [Server thread/INFO]: Sapling Growth Modifier: 100%
[28-08-2019 10:10:53] [Server thread/INFO]: Wheat Growth Modifier: 100%
[28-08-2019 10:10:53] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[28-08-2019 10:10:53] [Server thread/INFO]: Entity Activation Range: An 12 / Mo 24 / Mi 4
[28-08-2019 10:10:53] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[28-08-2019 10:10:53] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[28-08-2019 10:10:53] [Server thread/INFO]: Random Lighting Updates: false
[28-08-2019 10:10:53] [Server thread/INFO]: Structure Info Saving: true
[28-08-2019 10:10:53] [Server thread/INFO]: Sending up to 5 chunks per packet
[28-08-2019 10:10:53] [Server thread/INFO]: Max Entity Collisions: 8
[28-08-2019 10:10:53] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[28-08-2019 10:10:53] [Server thread/INFO]: Max TNT Explosions: 100
[28-08-2019 10:10:53] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[28-08-2019 10:10:53] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[28-08-2019 10:10:53] [Server thread/INFO]: Arrow Despawn Rate: 6000
[28-08-2019 10:10:53] [Server thread/INFO]: View Distance: 15
[28-08-2019 10:10:53] [Server thread/INFO]: Item Despawn Rate: 6000
[28-08-2019 10:10:53] [Server thread/INFO]: Item Merge Radius: 0.0
[28-08-2019 10:10:53] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[28-08-2019 10:10:53] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[28-08-2019 10:10:53] [Server thread/INFO]: Chunks to Grow per Tick: 650
[28-08-2019 10:10:53] [Server thread/INFO]: Clear tick list: false
[28-08-2019 10:10:53] [Server thread/INFO]: Experience Merge Radius: 0.0
[28-08-2019 10:10:53] [Server thread/INFO]: Mob Spawn Range: 4
[28-08-2019 10:10:53] [Server thread/INFO]: Preparing start region for level 0 (Seed: 1672200768549092230)
[28-08-2019 10:10:54] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[28-08-2019 10:10:54] [Server thread/INFO]: Done (0.758s)! For help, type "help" or "?"
[28-08-2019 10:10:54] [Server thread/INFO]: Starting GS4 status listener
[28-08-2019 10:10:54] [Query Listener #1/INFO]: Query running on 0.0.0.0:1336
```

**Comment by konsolas** [comment]
This is very strange; I'm not aware of anyone else who is having this issue at the moment.

OpenJDK is the only thing that stands out to me at the moment, so perhaps replacing it with the Oracle JDK will help.

For reference, this is the code that's failing: 
![image](https://user-images.githubusercontent.com/9408210/63864560-f5ad2f80-c9a7-11e9-8fd9-c8eb85f44029.png)

**Comment by MedicOP** [comment]
Just tried it on my local Windows PC, getting the same error. I am using Oracle JDK on this PC.

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)```

I downloaded the latest spigot 1.8.8 from here just to be sure that it is clean https://getbukkit.org/get/hNiHm0tuqAg1Xg7w7zudk63uHr0xo48D

**Comment by MedicOP** [comment]
Also tried a complete fresh install of CraftBukkit 1.8.8 with just AAC and ProtocolLib, still same error.

```
[16:45:21] [Server thread/INFO]: Starting minecraft server version 1.8.8
[16:45:21] [Server thread/INFO]: Loading properties
[16:45:21] [Server thread/INFO]: Default game type: SURVIVAL
[16:45:21] [Server thread/INFO]: Generating keypair
[16:45:21] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:45:21] [Server thread/INFO]: Using default channel type
[16:45:21] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[16:45:21] [Server thread/INFO]: [AAC] Attempting to inject into PlayerConnection
[16:45:22] [Server thread/ERROR]: Could not load 'plugins\AAC-4.1.7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:289) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:251) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.konsolas.aac.aW.a(Native Method) ~[?:?]
	at me.konsolas.aac.aW.run(Native Method) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java:26) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at me.konsolas.aac.aW.a(Native Method) ~[?:?]
	at me.konsolas.aac.aW.run(Native Method) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java:26) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	... 9 more
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "net/minecraft/server/v1_8_R3/PlayerConnection"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_161]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_161]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at me.konsolas.aac.aW.a(Native Method) ~[?:?]
	at me.konsolas.aac.aW.run(Native Method) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java:26) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
	... 9 more
[16:45:22] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0
[16:45:22] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0
[16:45:22] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[16:45:22] [Server thread/INFO]: Preparing level "world"
[16:45:22] [Server thread/INFO]: Preparing start region for level 0 (Seed: -2597172975742174493)
[16:45:23] [Server thread/INFO]: Preparing start region for level 1 (Seed: -2597172975742174493)
[16:45:23] [Server thread/INFO]: Preparing start region for level 2 (Seed: -2597172975742174493)
[16:45:23] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:45:23] [Server thread/INFO]: Done (1.399s)! For help, type "help" or "?"
```

**Comment by Janmm14** [comment]
Did you test it with JUST protocollib and aac?

**Comment by konsolas** [comment]
Here are the exact builds of spigot and protocollib I'm using locally. This is the expected output:

![image](https://user-images.githubusercontent.com/9408210/63932378-fa78ee80-ca4e-11e9-96a4-70e91538e4ae.png)

[1.8.8demo.zip](https://github.com/konsolas/AAC-Issues/files/3555039/1.8.8demo.zip)

**Comment by MedicOP** [comment]
> 
> 
> Did you test it with JUST protocollib and aac?

Yes, look at the full startup logs I posted, only AAC 4.1.7 and ProtocolLib 4.4.0 are shown.

**Comment by MedicOP** [comment]
@konsolas Does it work for you if you use CraftBukkit instead of spigot?

**Comment by konsolas** [comment]
I've never tested with craftbukkit; AAC being a spigot plugin, I've only tested with spigot and paper.

**Comment by MedicOP** [comment]
It seems to happen every time if I use CraftBukkit instead of Spigot, does that tell you anything?

**Comment by MedicOP** [comment]
It seems to happen when using `-Dlog4j.configurationFile=log4j2.xml` with this log4j2.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" packages="net.minecraft,com.mojang">
    <Appenders>
        <Console name="WINDOWS_COMPAT" target="SYSTEM_OUT"></Console>
        <Queue name="TerminalConsole">
            <PatternLayout pattern="[%d{HH:mm:ss} %level]: %msg%n" />
        </Queue>
        <RollingRandomAccessFile name="File" fileName="logs/latest.log" filePattern="logs/serverlog-%i.log.gz">
            <PatternLayout pattern="[%d{HH:mm:ss}] [%t/%level]: %replace{%msg}{\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[m|K]}{}%n" />
            <Policies>
                <SizeBasedTriggeringPolicy size="25 MB"/>
            </Policies>
            <DefaultRolloverStrategy max="4"/>
        </RollingRandomAccessFile>
    </Appenders>
    <Loggers>
        <Root level="info">
            <filters>
                <MarkerFilter marker="NETWORK_PACKETS" onMatch="DENY" onMismatch="NEUTRAL" />
            </filters>
            <AppenderRef ref="WINDOWS_COMPAT"/>
            <AppenderRef ref="File"/>
            <AppenderRef ref="TerminalConsole"/>
        </Root>
    </Loggers>
</Configuration>
```

**Comment by MedicOP** [comment]
Changing packages to only "com.mojang.util" solves the issue

**Comment by MedicOP** [comment]
This is also the reason why it happens with clean CraftBukkit install. If you don't specify a log4j2 file it uses the default inside the server jar. CraftBukkit uses "net.minecraft,com.mojang" while spigot uses "com.mojang.util"

**Comment by Janmm14** [comment]
As far as I know AAC is listed as not compatible with craftbukkit, only spigot is mentioned.
Apparantly your log4j2 file causes log4j2 to search for and load all classes in the specified packages
