### ISSUE TITLE
NoSuchMethodError on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [konsolas/AAC-Issues#1762]
### Issue description
```
[07:38:54] [Server thread/ERROR]: Could not load 'plugins/AAC-4.1.8-b2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: Method me.konsolas.aac.bt.run()V name or signature does not match
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: Method me.konsolas.aac.bt.run()V name or signature does not match
        at java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[?:?]
        at java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[?:?]
        at java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[?:?]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:767) ~[?:?]
        at java.lang.System.load(System.java:1831) ~[?:?]
        at net.konsolas.jnic.internal.NLDR.load(Unknown Source) ~[?:?]
        at me.konsolas.aac.AAC.<clinit>(AAC.java) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        ... 6 more
```

### Core information
**Server version**: Spigot 1.14.4 latest (Jenkins 2459) git-Spigot-065a373-6ed8a18 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**AAC version**: AAC-4.1.8-b2

**ProtocolLib version**: 4.5.0-b16

**Plugin list**: 

### Special environment information
**ViaVersion version**: 2.1.4-b272

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
I've posted a silent update that should resolve this.
