### ISSUE TITLE
AAC not working on macOS

### ISSUE THREAD

**Issue by DebuffPvP** [konsolas/AAC-Issues#1780]
Issue description

**ScreenShot:** https://gyazo.com/83fa7370edaf680d2c0056159c3073e1

Core information

Server version: CraftBukkit version git-TacoSpigot-bf023c7d (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

AAC version: All the 4.0 versions and all the 3.0 versions work fine though

ProtocolLib version: 4.4.0

Plugin list: ProtocolLib, AAC

Special environment information

ViaVersion version: Latest

ProtocolSupport version: No

ViaBackwards version: I use ViaRewind

BungeeCord plugins: No

Configuration

Default

**Comment by voigtman** [comment]
Hi Konsolas - I can confirm, AAC 4.2.1 is not loading on spigot 1.14.4-R0.1SNAPSHOT

Have attempted to use ProtocolLib 4.4.0 and 4.5.0

Only plugins I have installed are ProtocolLib and AAC - I have attempted on both Spigot and paper.

`[01:34:01] [Server thread/ERROR]: Could not load 'plugins/AAC-v4.2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:415) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	... 6 more
Caused by: java.lang.RuntimeException: Failed to load
	at net.konsolas.jnic.internal.NLDR.load(Unknown Source) ~[?:?]
	at me.konsolas.aac.AAC.<clinit>(AAC.java) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:415) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	... 6 more
`

**Comment by Janmm14** [comment]
Operating system?
`java -version` output? (if you have a vserver)
Which AAC version was the newest one which worked?

**Comment by DebuffPvP** [comment]
i'm using AAC 4.2.1 and protocollib 4.4.0 and it doesn't work and with previous 3.0 versions of aac it did

**Comment by DebuffPvP** [comment]
3.6.4-b1 (BETA) was the one that worked last and i recently just tried upgrading to the new aac

**Comment by DebuffPvP** [comment]
3.6.4-b1 (BETA) was the one that worked last and i recently just tried upgrading to the new aac
maybe it doesn't have 1.8.8 compatibility or maybe not compatible with beerspigot 1.8.8

**Comment by konsolas** [comment]
Going to reiterate @Janmm14's request for `java -version` output.

**Comment by voigtman** [comment]
For myself:
System Info: Java 12 (Java HotSpot(TM) 64-Bit Server VM 12.0.2+10)

**Comment by Janmm14** [comment]
And operating system?

**Comment by voigtman** [comment]
For myself: 
System Info: Java 12 (Java HotSpot(TM) 64-Bit Server VM 12.0.2+10) 
Host:  Mac OS X 10.13.6 (x86_64)

**Comment by DebuffPvP** [comment]
never got resolved
