### ISSUE TITLE
Error after Kick: NPE@bZ.b:205 v4.2.1

### ISSUE THREAD

**Issue by ItzJustAverage** [konsolas/AAC-Issues#1811]
### Issue description

Player was kick when mining for kill aura then this error was in console. I do think the player was using an auto miner as the didn't rejoin.

https://gist.github.com/ItzJustAverage/c49fc5723d78b9d1d7acb8f10111ca2c

### Core information
**Server version**: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) 

**AAC version**: 4.2.1

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: 2.1.3

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

### Configuration

Im using Celebrimbor's latest optimized config for aac 4.2.1

**Comment by Janmm14** [comment]
soo, what about posting your error

**Comment by ItzJustAverage** [comment]
sorry about that I was in a rush and didn’t realise i never lasted the error link. I edited the original comment.

**Comment by Janmm14** [comment]
Apparantly also happening with PacketPlayInArmAnimation, reported by HexedHero#0001 on discord

```
[13:00:33] [Netty Epoll Server IO #2/ERROR]: [AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC
java.lang.NullPointerException: null
	at me.konsolas.aac.bZ.b(bZ.java:205) ~[?:?]
	at me.konsolas.aac.V.a(V.java:17) ~[?:?]
	at me.konsolas.aac.V.onPacketReceiving(V.java:24) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:506) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-226]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:245) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.14.4.jar:git-Paper-226]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.14.4.jar:git-Paper-226]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[13:00:33] [Netty Epoll Server IO #2/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayInArmAnimation@63147e19[
    a=MAIN_HAND
  ]
```
