### ISSUE TITLE
NPE@B.a@cx.a:9 on MV change world

### ISSUE THREAD

**Issue by SlimeDog** [konsolas/AAC-Issues#1869]
### Issue description

On player change world:
```
[12:45:16] [Server thread/INFO]: rambeau issued server command: /mvtp rambeau world_whitedog 
[12:45:42] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AAC v4.3.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:441) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1250) ~[?:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.konsolas.aac.B.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.cx.a(cx.java:9) ~[?:?]
        at me.konsolas.aac.bV.a(bV.java:4) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.1.jar-2020-01-07-1824:git-Spigot-492a779-b98e2de]
        ... 19 more
```
This does not usually occur.

### Core information
**Server version**:  1.15.1 (Jenkins 2558)

**AAC version**: 4.3.4

**ProtocolLib version**: 4.5.1-b443

**Plugin list**: Multiverse-Core 4.1.1-b777

### Special environment information
**ViaVersion version**: 2.2.2-b305 but irrelevant since server is latest 1.15.1

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration
Two threshold changes only

**Comment by konsolas** [comment]
AAC5
