### ISSUE TITLE
ExceptionInInitializerError with Spigot build 2568

### ISSUE THREAD

**Issue by SlimeDog** [konsolas/AAC-Issues#1873]
This was not an issue with previous build of Spigot 1.15.1 (Jenkins 2564)

It may be related to [https://hub.spigotmc.org/jira/browse/SPIGOT-5515](https://hub.spigotmc.org/jira/browse/SPIGOT-5515)

### Issue description
```
[21:23:05] [Server thread/ERROR]: Error occurred while enabling AAC v4.3.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at me.konsolas.aac.c2.<clinit>(c2.java:11) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:315) ~[?:?]
        at me.konsolas.aac.bW.a(bW.java:154) ~[?:?]
        at me.konsolas.aac.AAC.onEnable(AAC.java:41) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Material must be an item: PISTON_HEAD
        at org.apache.commons.lang.Validate.isTrue(Validate.java:71) ~[spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:71) ~[spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:58) ~[spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:46) ~[spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:36) ~[spigot-1.15.1.jar-2020-01-14-2045:git-Spigot-037559e-752cf95]
        at me.konsolas.aac.bk.lambda$new$11(bk.java:32) ~[?:?]
        at me.konsolas.aac.bk.<init>(bk.java:43) ~[?:?]
        at me.konsolas.aac.bk.<init>(bk.java:36) ~[?:?]
        at me.konsolas.aac.bk.<clinit>(bk.java:26) ~[?:?]
        ... 13 more
```

### Core information
**Server version**: 1.15.1 (Jenkins 2568)

**AAC version**: 4.3.5

**ProtocolLib version**: 4.5.1-SNAPSHOT-b445

**Plugin list**: irrelevant to this issue

**Comment by SlimeDog** [comment]
Note that the change was reverted in Spigot build 2569. All is well, until the change is reintroduced (at some point).

**Comment by konsolas** [comment]
I don't expect this change to be reintroduced because of how breaking it would be

**Comment by SlimeDog** [comment]
Agreed.
