### ISSUE TITLE
AAC not loading in server.

### ISSUE THREAD

**Issue by Domanyc** [konsolas/AAC-Issues#1875]
Whenever i try to run AAC in my server it never registers in-game and it gives me a message in the console.

i am playing on 1.13.2 with the newest version of AAC and the newest version of protocolib.

[19:38:12] [Server thread/ERROR]: Could not load 'plugins\AAC-4.3.5 (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:332) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:325) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ExceptionInInitializerError
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:60) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
... 6 more
Caused by: java.lang.RuntimeException: Failed to load
at net.konsolas.jnic.internal.NLDR.load(Unknown Source) ~[?:?]
at me.konsolas.aac.AAC.<clinit>(AAC.java) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:60) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
... 6 more

EDIT: I don’t know if this helps but The only version of AAC that works is AAC 3.6.4-b1 (BETA)

**Comment by Janmm14** [comment]
AAC is not compatible with 32bit Java. Also AAC is not compatible with MacOS.

**Comment by Domanyc** [comment]
> AAC is not compatible with 32bit Java. Also AAC is not compatible with MacOS.

im not playing on MacOS and i have 64bit Java. i will try re-installing java to see if that helps but thanks!

**Comment by Domanyc** [comment]
Bump

**Comment by Domanyc** [comment]
Bump

**Comment by konsolas** [comment]
What's the output of `java -version` in a terminal?

**Comment by Domanyc** [comment]
Java version "1.8.0_241"

**Comment by konsolas** [comment]
The command produces much more information than that. Please post all of the output.

**Comment by Domanyc** [comment]
ok sorry.
the full output is:
java version "1.8.0_241"
Java(TM)  SE Runtime Environment  (build 25.241-b07)
Java Hotspot(TM) Client VM (build 25.241-b07, mixed mode, sharing)

**Comment by konsolas** [comment]
Your Java version is 32 bit. 

Please download a 64 bit version of Java.
