### ISSUE TITLE
Logspamer protection does not work

### ISSUE THREAD

**Issue by radek203** [konsolas/AAC-Issues#1901]
```
[12:46:01 ERROR]: Couldn't sign book
java.lang.IndexOutOfBoundsException: null
at io.netty.buffer.EmptyByteBuf.readShort(EmptyByteBuf.java:541) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketDataSerializer.readShort(PacketDataSerializer.java:683) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketDataSerializer.k(PacketDataSerializer.java:262) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2261) [?:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[12:46:01 INFO]: DarkA lost connection: Invalid book data!
```
[AAC] Loading AAC v4.3.6
[ProtocolLib] Enabling ProtocolLib v4.5.1-SNAPSHOT-b445
Spigot: 1.12.2
Cheat: Wurst - LogSpammer

I have the impression that this is combined with my previous issue, also packets: https://github.com/konsolas/AAC-Issues/issues/1876

**Comment by Janmm14** [comment]
AAC has no log spamming protection.

**Comment by radek203** [comment]
@Janmm14 from what I've seen on other servers that have this plugin, it works for the most part, here should work packets protection, but as I say for me, it crashes as in this issue, which I created earlier
