### ISSUE TITLE
IllegalArgumentException on PlayerViolationCommandEvent#getViolationLevel

### ISSUE THREAD

**Issue by Rsl1122** [konsolas/AAC-Issues#1932]
Hello, I got a bug report on my plugin: https://github.com/plan-player-analytics/Plan/issues/1374

with this exception:
```
[02:23:04 ERROR]: Could not pass event PlayerViolationCommandEvent to Plan v5.1 build 474
java.lang.IllegalArgumentException: null
at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_242]
at me.konsolas.aac.e.getViolationLevel(e.java) ~[?:?]
at com.djrapitops.extension.AACHackKickListener.onJoin(AACHackKickListener.java:66) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor518.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-143]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
at me.konsolas.aac.cl.a(cl.java) ~[?:?]
at me.konsolas.aac.Y.run(Y.java) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-143]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
My code related to this exception:
https://github.com/plan-player-analytics/Extension-AAC/blob/ebe34963ae4c5cbe7540a96435794c7f3861b5ac/src/main/java/com/djrapitops/extension/AACHackKickListener.java#L66

I can't unfortunately figure out the source of  the exception, so I'm just asking why this occurs and if this is something that I need to catch.

I adviced the user to update their AAC in case this was an old bug.

### Core information
**Server version**: 1.15.2

**AAC version**: Unknown

**ProtocolLib version**: Unknown

**Plugin list**: Unknown

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by Janmm14** [comment]
I guess either Player or HackType is null.
Woukd be great to add some debug to your code (like a try catch with IllegalArgumentException which prints values of hacktype and player and then rethrows the exception) and let the one with the problem recheck so we get the details which one is null in which case. Also could possibly be related to players who just joined or left the server.

**Comment by konsolas** [comment]
This happens when AAC isn't checking the player in question at that time.

This could be for a number of reasons, including:

- The check corresponding to the requested HackType is disabled
- The player is in creative or spectator mode
- The player has the `AAC.bypass` permission node
- The player has allowFlight set

It seems to me that returning 0 in these cases would make more sense than throwing an exception, so this is probably what will be done in the future

**Comment by konsolas** [comment]
4.3.9
