### ISSUE TITLE
v4.3.9 Failed to read buffer

### ISSUE THREAD

**Issue by cristianrg36** [konsolas/AAC-Issues#1937]
> [00:50:35 INFO]: [AAC] 1.8 detected for itsinkBl4d3
> [00:50:35 INFO]: itsinkBl4d3[/88.6.161.226:53186] logged in with entity id 28411 at ([Skywars]-951.0, 29.0, 402.0)
> [00:50:35 INFO]: ⚠ itsinkBl4d3 Entro a Skywars
> [00:50:36 ERROR]: [AAC] Failed to read buffer
> [00:50:36 INFO]: [AAC] Disabling AAC v4.3.9
> [00:50:36 ERROR]: Could not pass event PluginDisableEvent to PlaceholderAPI v2.8.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:358) [server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [server.jar:git-Spigot-fdc1440-53fac9f]
at me.konsolas.aac.a6.run(a6.java) [AAC-4.3.9.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [server.jar:git-Spigot-fdc1440-53fac9f]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_232]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
Caused by: java.lang.AbstractMethodError: me/clip/placeholderapi/expansion/PlaceholderExpansion.getPlugin()Ljava/lang/String;
at me.clip.placeholderapi.PlaceholderListener.onPluginUnload(PlaceholderListener.java:113) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_232]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_232]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_232]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-fdc1440-53fac9f]
... 11 more
> [00:50:36 INFO]: [AAC] Saving log file...
> [00:50:36 INFO]: [AAC] Thread AAC-LogWriter exiting

**Comment by konsolas** [comment]
Hi, could you join us on discord so we can investigate this further?

**Comment by cristianrg36** [comment]
Can you send the Discord Link pls?

**Comment by konsolas** [comment]
See the front page of this repository
