### ISSUE TITLE
AAC spams the console with multiple packet-related errors.

### ISSUE THREAD

**Issue by Tobyhn** [konsolas/AAC-Issues#1948]
### Issue description

AAC spams the console with multiple packet-related errors.

Example: `[AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC`

I cannot figure out why this is happening as this is a completely fresh install of paperspigot and there are no additional plugins installed besides the required ProtocolLib, EssentialsX, and Vault. I realize this isn't super detailed, but it's all the information I have.

Log: https://pastebin.com/Z10NYbd8

### Core information
**Server version**: 1.15.2 Paper (build 229)

**AAC version**: 4.3.11

**ProtocolLib version**: 4.5.0

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

**Comment by In77** [comment]
same problem

**### Core information**

Server version: 1.15.2 Paper (build 231)

AAC version: 4.3.11

ProtocolLib version: 4.5.0

### **Special environment information**

ViaVersion version: N/A

ProtocolSupport version: N/A

ViaBackwards version: N/A

BungeeCord plugins: N/A

[12:30:15 ERROR]: [AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC
java.lang.NullPointerException: null
        at me.konsolas.aac.T.a(T.java) ~[?:?]
        at me.konsolas.aac.cn.a(cn.java) ~[?:?]
        at me.konsolas.aac.a1.a(a1.java) ~[?:?]
        at me.konsolas.aac.a1.onPacketReceiving(a1.java) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:533) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[PaperClip-1.15.2-b231.jar:git-Paper-231]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[12:30:15 ERROR]: Parameters:
  net.minecraft.server.v1_15_R1.PacketPlayInArmAnimation@1637f3af[
    a=MAIN_HAND
  ]

**Comment by Janmm14** [comment]
4.3.11-b1
