### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by radek203** [konsolas/AAC-Issues#1957]
It was good before, only once did I get this error
PaperSpigot: 1.8.8
AAC: 4.3.12
Config: Latest: OPTIMIZED AAC4 CONFIG BY CELEBRIMBOR
AACPlus: 2.3.2
ConditionalCommands: 1.4-SNAPSHOT
[ProtocolLib] Loading ProtocolLib v4.5.1-SNAPSHOT-b451
```
[08:47:27] [Netty Epoll Server IO #1/ERROR]: [AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC
java.lang.IllegalArgumentException: Option badpackets.쮠燴燁䊠꽦猔䰝旁䏻쌟숣篹柪몟 not found
	at me.konsolas.aac.u.a(u.java) ~[AAC-4.3.12.jar:?]
	at me.konsolas.aac.u.d(u.java) ~[AAC-4.3.12.jar:?]
	at me.konsolas.aac.H.a(H.java) ~[AAC-4.3.12.jar:?]
	at me.konsolas.aac.c1.a(c1.java) ~[AAC-4.3.12.jar:?]
	at me.konsolas.aac.c1.onPacketReceiving(c1.java) ~[AAC-4.3.12.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.5.1-SNAPSHOT-b451]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.5.1-SNAPSHOT-b451]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.5.1-SNAPSHOT-b451]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.5.1-SNAPSHOT-b451]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.5.1-SNAPSHOT-b451]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.5.1-SNAPSHOT-b451]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:533) [ProtocolLib.jar:4.5.1-SNAPSHOT-b451]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-PaperSpigot-"8b18730"]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) [ProtocolLib.jar:4.5.1-SNAPSHOT-b451]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[08:47:27] [Netty Epoll Server IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInEntityAction@1d96e3d6[
    a=10
    animation=START_SNEAKING
    c=0
  ]

```

**Comment by Janmm14** [comment]
If it came only once and restarting fixed it, I'd call this a fluke.

**Comment by radek203** [comment]
Does not change the fact that despite everything occurred :)
