### ISSUE TITLE
Missing configuration option (not in en_US)

### ISSUE THREAD

**Issue by SlimeDog** [konsolas/AAC-Issues#1969]
### Issue description

When player right-clicks an iron door (an illegal action), the following:
```
[17:01:33] [Server thread/ERROR]: [AAC] Missing configuration option ݮ禟❪庩䟸悈ᶚ⅍蓟 for check world.FastPlace
[17:01:33] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to AAC v4.3.12
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at com.rngservers.irondoors.door.DoorManager.canBuild(DoorManager.java:30) ~[?:?]
        at com.rngservers.irondoors.events.Events.onIronDoor(Events.java:31) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor423.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:450) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[?:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Option fastplace.ݮ禟❪庩䟸悈ᶚ⅍蓟 not found
        at me.konsolas.aac.u.a(u.java) ~[?:?]
        at me.konsolas.aac.u.e(u.java) ~[?:?]
        at me.konsolas.aac.J.a(J.java) ~[?:?]
        at me.konsolas.aac.bY.a(bY.java) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        ... 28 more
```

### Core information
**Server version**:  1.15.2 (Jenkins 2693)
```
>version
[17:06:46] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a99063f-c9d7c16 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[17:06:46] [Server thread/INFO]: You are running the latest version
```

**AAC version**: 
```
>version AAC
[17:06:19] [Server thread/INFO]: AAC version 4.3.12
[17:06:19] [Server thread/INFO]: Powerful anti-cheat solution for Spigot servers.
[17:06:19] [Server thread/INFO]: Website: https://www.spigotmc.org/resources/6442/
[17:06:19] [Server thread/INFO]: Author: konsolas
```

**ProtocolLib version**: 
```
>version ProtocolLib
[17:07:11] [Server thread/INFO]: ProtocolLib version 4.6.0-SNAPSHOT-b460
[17:07:11] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[17:07:11] [Server thread/INFO]: Authors: dmulloy2 and comphenix
```

**Plugin list**: 
```
>version Essentials
[17:19:39] [Server thread/INFO]: Essentials version 2.17.2.123
[17:19:39] [Server thread/INFO]: Provides an essential, core set of commands for Bukkit.
[17:19:39] [Server thread/INFO]: Website: http://tiny.cc/EssentialsCommands
[17:19:39] [Server thread/INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam and md678685
```

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

### Configuration

No substantive configuration changes.

**Comment by SlimeDog** [comment]
I rebooted. Issue has not repeated. No changes. :(

**Comment by Janmm14** [comment]
Probably a rare issue of the obfuscation.

**Comment by SlimeDog** [comment]
I guess so, but now an NPE for the same event.
```
[03:56:10] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AAC v4.3.12
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:450) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[?:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.konsolas.aac.h.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.K.a(K.java) ~[?:?]
        at me.konsolas.aac.bY.a(bY.java) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
        ... 19 more
```

**Comment by Janmm14** [comment]
> 
> 
> I guess so, but now an NPE for the same event.
> 
> ```
> [03:56:10] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AAC v4.3.12
> org.bukkit.event.EventException: null
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:450) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[?:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         at java.lang.Thread.run(Thread.java:834) [?:?]
> Caused by: java.lang.NullPointerException
>         at me.konsolas.aac.h.a(Unknown Source) ~[?:?]
>         at me.konsolas.aac.K.a(K.java) ~[?:?]
>         at me.konsolas.aac.bY.a(bY.java) ~[?:?]
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar-2020-06-13-0606:git-Spigot-a99063f-c9d7c16]
>         ... 19 more
> ```

Thats likely a completely different cause.

**Comment by konsolas** [comment]
Probably no similar obfuscation issues in AAC5?
