### ISSUE TITLE
AAC Could not pass event PlayerMoveEvent to AAC v4.3.12

### ISSUE THREAD

**Issue by radek203** [konsolas/AAC-Issues#1975]
(Taco Fork) GuardSpigot 1.8.8
ProtocolLib: #460
(Bungee Fork) Aegis: 8.5.3
```
[19:18:43] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AAC v4.3.12
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(:302) ~[server.jar:git-TacoSpigot-1dc10b3]
	at co.aikar.timings.TimedEventExecutor.execute(:78) ~[server.jar:git-TacoSpigot-1dc10b3]
	at org.bukkit.plugin.RegisteredListener.callEvent(:62) ~[server.jar:git-TacoSpigot-1dc10b3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(:501) [server.jar:git-TacoSpigot-1dc10b3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(:486) [server.jar:git-TacoSpigot-1dc10b3]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(:285) [?:git-TacoSpigot-1dc10b3]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(:126) [server.jar:git-TacoSpigot-1dc10b3]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(:18) [server.jar:git-TacoSpigot-1dc10b3]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(:13) [server.jar:git-TacoSpigot-1dc10b3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(:44) [server.jar:git-TacoSpigot-1dc10b3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(:820) [server.jar:git-TacoSpigot-1dc10b3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(:420) [server.jar:git-TacoSpigot-1dc10b3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(:759) [server.jar:git-TacoSpigot-1dc10b3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(:662) [server.jar:git-TacoSpigot-1dc10b3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_141]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466) ~[?:1.8.0_141]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getActivePotionEffects(:326) ~[server.jar:git-TacoSpigot-1dc10b3]
	at me.konsolas.aac.bO.<init>(bO.java) ~[?:?]
	at me.konsolas.aac.D.a(D.java) ~[?:?]
	at me.konsolas.aac.bY.a(bY.java) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(:300) ~[server.jar:git-TacoSpigot-1dc10b3]
	... 16 more
```

**Comment by Janmm14** [comment]
Another plugin likely edited player potion effects asynchroniously. L9ok for ConcurrentMdoficationExceptions in your logs from another plugin.
