### ISSUE TITLE
Server freezes for more than 30 seconds

### ISSUE THREAD

**Issue by lucaazalim** [konsolas/AAC-Issues#1994]
Sometimes, the server stops responding and stucks for more than 30 seconds. There are no console errors.

While the server was frozen, the Server Thread stacktrace showed something related to AAC:

```
"Server thread" #33 prio=5 os_prio=0 tid=0x00007f9f18779800 nid=0x67d9 waiting on condition [0x00007f9e114b8000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000adbcd960> (a java.util.concurrent.SynchronousQueue$TransferStack)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:877)
        at me.konsolas.aac.a9.a(a9.java)
        at me.konsolas.aac.dz.a(dz.java)
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
        - locked <0x00000000a3e78778> (a org.bukkit.plugin.SimplePluginManager)
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:247)
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:780)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:719)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:621)
        at java.lang.Thread.run(Thread.java:748)
```

### Core information
**Server version**: 1.8.9

**AAC version**: 4.4.0

**ProtocolLib version**: 4.5.0

### Special environment information
**ViaVersion version**: 3.0.1

### Configuration
https://www.diffchecker.com/bx4K5EU3

**Comment by konsolas** [comment]
AAC5 no longer has any synchronousqueues.
