### ISSUE TITLE
AAC 5.0 pre 1.16.4

### ISSUE THREAD

**Issue by dudeman123** [konsolas/AAC-Issues#2016]
### Issue description
###Console Error
[20:59:48] [Server thread/ERROR]: Could not load 'plugins/AAC-5.0.0-pre1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.BootstrapMethodError: call site initialization exception
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.4.jar:git-Paper-260]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.4.jar:git-Paper-260]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.4.jar:git-Paper-260]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-260]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-260]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-260]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-260]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297) ~[?:1.8.0_262]
	at me.konsolas.aac.AAC.<clinit>(AAC.java) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_262]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.4.jar:git-Paper-260]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-260]
	... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:330) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:327) ~[?:1.8.0_262]
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227) ~[?:1.8.0_262]
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209) ~[?:1.8.0_262]
	at java.lang.ClassValue.get(ClassValue.java:115) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:351) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:341) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:291) ~[?:1.8.0_262]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:283) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297) ~[?:1.8.0_262]
	at me.konsolas.aac.AAC.<clinit>(AAC.java) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_262]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.4.jar:git-Paper-260]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-260]
	... 7 more
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting 疒翜ૼ᭒Ꮑ䗽⦬䈖ﴕ暣챦„忄钳ꊱ톸㞤„
	at javax.crypto.Cipher.getInstance(Cipher.java:543) ~[?:1.8.0_262]
	at me.konsolas.aac.id.<clinit>(Unknown Source) ~[?:?]
	at sun.misc.Unsafe.ensureClassInitialized(Native Method) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:330) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:327) ~[?:1.8.0_262]
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227) ~[?:1.8.0_262]
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209) ~[?:1.8.0_262]
	at java.lang.ClassValue.get(ClassValue.java:115) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:351) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:341) ~[?:1.8.0_262]
	at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:291) ~[?:1.8.0_262]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:283) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297) ~[?:1.8.0_262]
	at me.konsolas.aac.AAC.<clinit>(AAC.java) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_262]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.4.jar:git-Paper-260]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-260]
	... 7 more

**_Perhaps don't have unncecessary obfuscation (which isn;t allowed on spigotmc anyways) and use an approach more like spartan, where the checks are very difficult to reverse but the code is somewhat comprehensible_**

### Core information
**Server version**: 1.16.4

**AAC version**: 5.0.0-pre1

**Comment by Janmm14** [comment]
Obfuscation used by konsolas is allowed by spigotmc.
