### ISSUE TITLE
Console errror

### ISSUE THREAD

**Issue by Demonas** [konsolas/AAC-Issues#2029]
### Issue description

```
[13:49:17] [Netty Epoll Server IO #1/ERROR]: [AAC5] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC5
java.lang.NullPointerException: null
	at me.konsolas.aac.aJ.a(aJ.java:217) ~[?:?]
	at me.konsolas.aac.aJ.b(aJ.java:126) ~[?:?]
	at me.konsolas.aac.aJ.a(aJ.java:178) ~[?:?]
	at me.konsolas.aac.aM.a(aM.java:16) ~[?:?]
	at me.konsolas.aac.dp.a(dp.java:42) ~[?:?]
	at me.konsolas.aac.timings.AACListener.onPacketReceiving(AACListener.java:33) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:350) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:315) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:538) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[server.jar:git-Paper-253]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[server.jar:git-Paper-253]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[server.jar:git-Paper-253]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[server.jar:git-Paper-253]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[server.jar:git-Paper-253]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[server.jar:git-Paper-253]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[server.jar:git-Paper-253]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[server.jar:git-Paper-253]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[server.jar:git-Paper-253]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[server.jar:git-Paper-253]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git-Paper-253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git-Paper-253]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[server.jar:git-Paper-253]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[server.jar:git-Paper-253]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[server.jar:git-Paper-253]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[server.jar:git-Paper-253]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[server.jar:git-Paper-253]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
[13:49:17] [Netty Epoll Server IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R2.PacketPlayInVehicleMove@1aa3da3b[
    a=10825.223129493073
    b=62.523255517500004
    c=-34.301303917468026
    d=-79.34021
    e=0.0
  ]
```

### Core information
**Server version**: 1.16.3

**AAC version**: 5.0.0pre7

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ?? no

**ProtocolSupport version**: ?? no

**ViaBackwards version**: ??no

**BungeeCord plugins**: ??no

**Comment by konsolas** [comment]
pre8
