### ISSUE TITLE
Task #11 for AAC5 v5.0.2 generated an exception

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2061]
Caught the following error in the console:

```
[14:33:13] [Server thread/WARN]: [AAC5] Task #11 for AAC5 v5.0.2 generated an exception
java.lang.IllegalArgumentException: velocity
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.setVelocity(CraftEntity.java:425) ~[patched_1.16.4.jar:git-Paper-325]
	at me.konsolas.aac.gE.a(gE.java:178) ~[?:?]
	at me.konsolas.aac.fu.a(fu.java:88) ~[?:?]
	at me.konsolas.aac.bu.a(bu.java:8) ~[?:?]
	at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:1) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-325]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Core information
**Server version**: 1.16.4 (Paper Build 325)

**AAC version**: 5.0.2

**AAC config**: 5.0.1|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 480

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
5.0.3

**Comment by andrewkm** [comment]
Oh thank god, this has been spamming us so much past 24+ hours lol.
