### ISSUE TITLE
Exception and chunk loading

### ISSUE THREAD

**Issue by kamcio96** [konsolas/AAC-Issues#2071]
Exception:
[16:04:40 WARN]: [AAC5] Task #5 for AAC5 v5.0.3 generated an exception
java.lang.NoSuchFieldError: STRIDER
at me.konsolas.aac.e_.b(e_.java:185) ~[?:?]
at me.konsolas.aac.hJ.a(hJ.java:393) ~[?:?]
at me.konsolas.aac.hJ.(hJ.java:529) ~[?:?]
at me.konsolas.aac.hD.(hD.java:32) ~[?:?]
at me.konsolas.aac.eb.a(eb.java:33) ~[?:?]
at me.konsolas.aac.eb.a(eb.java:12) ~[?:?]
at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:1) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

Also AAC tries to load chunks. Why? 
![image](https://user-images.githubusercontent.com/1339911/102693691-b948b700-421c-11eb-812f-489ec21ac774.png)

**Comment by kamcio96** [comment]
@konsolas chunk loading too?

**Comment by konsolas** [comment]
AAC needs to access the world around each player. This doesn't normally cause chunk loading unless the player is in an unloaded chunk.

**Comment by kamcio96** [comment]
[17:50:10 ERROR]: [AAC5] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC5
java.lang.IllegalArgumentException: Unknown enum constant RIDING_JUMP
at com.comphenix.protocol.wrappers.EnumWrappers$AliasedEnumConverter.lambda$getSpecific$0(EnumWrappers.java:749) ~[ProtocolLib.jar:4.5.1]
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_275]
at com.comphenix.protocol.wrappers.EnumWrappers$AliasedEnumConverter.getSpecific(EnumWrappers.java:734) ~[ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.wrappers.EnumWrappers$AliasedEnumConverter.getSpecific(EnumWrappers.java:720) ~[ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.5.1]
at me.konsolas.aac.r.a(r.java:562) ~[AAC-5.0.4.jar:5.0.4]
at me.konsolas.aac.e.a(e.java:2) ~[AAC-5.0.4.jar:5.0.4]
at me.konsolas.aac.a2.a(a2.java:3) ~[AAC-5.0.4.jar:5.0.4]
at me.konsolas.aac.timings.AACListener.onPacketReceiving(AACListener.java:50) ~[AAC-5.0.4.jar:5.0.4]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:350) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:315) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:538) [ProtocolLib.jar:4.5.1]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) [ProtocolLib.jar:4.5.1]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[17:50:10 ERROR]: Parameters:
net.minecraft.server.v1_8_R3.PacketPlayInEntityAction@8c93a9d[
a=8245
animation=RIDING_JUMP
c=10
]

[17:50:55 ERROR]: [AAC5] Unhandled exception number 32 occured in onPacketReceiving(PacketEvent) for AAC5
java.lang.IllegalArgumentException: Unknown enum constant RIDING_JUMP
at com.comphenix.protocol.wrappers.EnumWrappers$AliasedEnumConverter.lambda$getSpecific$0(EnumWrappers.java:749) ~[ProtocolLib.jar:4.5.1]
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_275]
at com.comphenix.protocol.wrappers.EnumWrappers$AliasedEnumConverter.getSpecific(EnumWrappers.java:734) ~[ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.wrappers.EnumWrappers$AliasedEnumConverter.getSpecific(EnumWrappers.java:720) ~[ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.5.1]
at me.konsolas.aac.r.a(r.java:562) ~[AAC-5.0.4.jar:5.0.4]
at me.konsolas.aac.e.a(e.java:2) ~[AAC-5.0.4.jar:5.0.4]
at me.konsolas.aac.a2.a(a2.java:3) ~[AAC-5.0.4.jar:5.0.4]
at me.konsolas.aac.timings.AACListener.onPacketReceiving(AACListener.java:50) ~[AAC-5.0.4.jar:5.0.4]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:350) [ProtocolLib.jar:4.5.1]

**Comment by kamcio96** [comment]
No mySQL reconnect

@konsolas add me on discord kamcio96#8278

[17:58:36 ERROR]: [AAC5] Failed to analyse player JET_Knoksix
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.Connection was implicitly closed by the driver.
at sun.reflect.GeneratedConstructorAccessor249.newInstance(Unknown Source) ~[?:?]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_275]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_275]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1213) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1200) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4203) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4169) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at me.konsolas.aac.gD.a(gD.java:126) ~[?:?]
at me.konsolas.aac.cd.lambda$generateReport$5(cd.java:142) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet successfully received from the server was 711 milliseconds ago. The last packet sent successfully to the server was 711 milliseconds ago.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_275]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_275]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_275]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_275]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d1]
at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d

**Comment by Janmm14** [comment]
its prefered that you open new issues on github for new issues you experience @kamcio96
