### ISSUE TITLE
PlayerItemConsumeEvent Error

### ISSUE THREAD

**Issue by Hyronymos1337** [konsolas/AAC-Issues#2090]
> [16:18:13 ERROR]: Could not pass event PlayerItemConsumeEvent to AAC5 v5.0.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-8fb8e031]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-PaperSpigot-8fb8e031]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-8fb8e031]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [spigot.jar:git-PaperSpigot-8fb8e031]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.EntityHuman.s(EntityHuman.java:298) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.EntityPlayer.s(EntityPlayer.java:902) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:143) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:293) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:385) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-8fb8e031]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:762) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:701) [spigot.jar:git-PaperSpigot-8fb8e031]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:604) [spigot.jar:git-PaperSpigot-8fb8e031]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoSuchFieldError: DRIED_KELP
        at me.konsolas.aac.hh.a(hh.java:95) ~[?:?]
        at me.konsolas.aac.hZ.a(hZ.java:34) ~[?:?]
        at me.konsolas.aac.iz.a(iz.java:9) ~[?:?]
        at me.konsolas.aac.timings.AACListener.a(AACListener.java:32) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot.jar:git-PaperSpigot-8fb8e031]
        ... 20 more

**Comment by Hyronymos1337** [comment]
fixed in the new hotfix version of 5.0.6
