### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Dartume** [konsolas/AAC-Issues#2103]
i have a lot of error massage in my logs

https://pastebin.com/K2XZUT7g

**Server version**:  1.16.4  Paper-354

**AAC version**:  5.0.6

**ProtocolLib version**:  Build #487

**Comment by Janmm14** [comment]
Please consult your log file from the top to find errors with a bunch of lines starting with "at" and send those in. The errors in your log are truncated by java.

**Comment by Dartume** [comment]
[16:16:03] [Server thread/WARN]: [AAC5] Task #10 for AAC5 v5.0.6 generated an exception
java.lang.NullPointerException: null
	at me.konsolas.aac.aR.a(aR.java:4) ~[?:?]
	at me.konsolas.aac.aR.a(aR.java:13) ~[?:?]
	at me.konsolas.aac.ee.<init>(ee.java:84) ~[?:?]
	at me.konsolas.aac.eG.<init>(eG.java:42) ~[?:?]
	at me.konsolas.aac.fL.a(fL.java:52) ~[?:?]
	at me.konsolas.aac.fL.a(fL.java:29) ~[?:?]
	at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:4) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[paper.jar:git-Paper-354]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[paper.jar:git-Paper-354]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[paper.jar:git-Paper-354]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[paper.jar:git-Paper-354]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[paper.jar:git-Paper-354]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[paper.jar:git-Paper-354]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[paper.jar:git-Paper-354]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by konsolas** [comment]
Reset your config.
