### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC5

### ISSUE THREAD

**Issue by Olexorus** [konsolas/AAC-Issues#2109]
### Issue description

I randomly get a bunch of these exceptions in console:
```
[15:30:32] [Netty Epoll Server IO #3/ERROR]: [AAC5] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC5
java.lang.NullPointerException: null
[15:30:32] [Netty Epoll Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook@41e50070[
    x=64312.5
    y=67.0
    z=35390.5
    yaw=89.99999
    pitch=0.0
    f=false
    hasPos=true
    hasLook=true
  ]
```
Not sure how frequent it is, happened twice successively within 20 minutes of starting the server.

### Core information
**Server version**: git-Tuinity-"f06591a" (MC: 1.16.4) (most recent version of Tuinity as of writing this)

**AAC version**: 5.0.7

**ProtocolLib version**: v4.6.0-SNAPSHOT-b492 (downloaded today)

**Plugin list**: AAC5, AntiVPN, CMI, CoreProtect, DiscordSRV, FarmLimiter, LuckPerms, PacketLimiter, PlaceholderAPI, PremiumVanish, ProtocolLib, RedProtect, ViewDistanceTweaks, VillagerOptimiser, Votifier

### Special environment information
**ViaVersion version**: /

**ProtocolSupport version**: /

**ViaBackwards version**: /

**BungeeCord plugins**: /

### Configuration
Completely disabled mitigation and automatic kicks (I want AAC to be silent and only notify staff), I don't think anything else that's significant.

**Comment by Olexorus** [comment]
Oh, I just saw it happened a third time, that time with a longer stacktrace:
```
[15:26:27] [Netty Epoll Server IO #3/ERROR]: [AAC5] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC5
java.lang.NullPointerException: null
	at me.konsolas.aac.K.<init>(K.java:32) ~[?:?]
	at me.konsolas.aac.dW.<init>(dW.java:22) ~[?:?]
	at me.konsolas.aac.eT.b(eT.java:144) ~[?:?]
	at me.konsolas.aac.eT.a(eT.java:176) ~[?:?]
	at me.konsolas.aac.e3.a(e3.java:81) ~[?:?]
	at me.konsolas.aac.f4.a(f4.java:14) ~[?:?]
	at me.konsolas.aac.timings.AACListener.onPacketReceiving(AACListener.java:43) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:348) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:313) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.16.4.jar:git-Tuinity-"f06591a"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[15:26:27] [Netty Epoll Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook@67ed8d26[
    x=-289.5
    y=139.0
    z=-10843.5
    yaw=89.99999
    pitch=0.0
    f=false
    hasPos=true
    hasLook=true
  ]
```
This happened before the other two.

**Comment by ChiboYen** [comment]
I am getting these errors as well, and I use the latest (5.0.7) version of AAC and the latest protocolLib (b492)
https://pastebin.com/X22P16f8
