### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by CharlyZhu** [konsolas/AAC-Issues#2135]
### Core information
**Server version**: 
1.16.4
**AAC version**: 
5.0.8
**ProtocolLib version**: 
4.5.1

### Special environment information
**ViaVersion version**: ??
N/A
**ProtocolSupport version**: ??
N/A
**ViaBackwards version**: ??
N/A
**BungeeCord plugins**: ??
N/A
### Configuration

[10:01:12 ERROR]: [AAC5] Unhandled exception occured in onPacketSending(PacketEvent) for AAC5
java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getSectionPositions()Lcom/comphenix/protocol/reflect/StructureModifier;
        at me.konsolas.aac.ag.b(ag.java:175) ~[?:?]
        at me.konsolas.aac.a6.a(a6.java:87) ~[?:?]
        at me.konsolas.aac.gd.a(gd.java:37) ~[?:?]
        at me.konsolas.aac.timings.AACListener.onPacketSending(AACListener.java:63) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1709) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:499) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:427) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:822) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[patched_1.16.4.jar:git-Paper-414]        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:816) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:734) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:460) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-414]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[10:01:12 ERROR]: Parameters:
  net.minecraft.server.v1_16_R3.PacketPlayOutMultiBlockChange@5f589d61[
    a=SectionPosition{x=-11, y=3, z=14}
    b={3754,4010,3738,3994,3482,3226,2970,2714}
    c={Block{minecraft:moving_piston}[facing=south,type=normal],Block{minecraft:pumpkin_stem}[age=7],Block{minecraft:piston}[extended=true,facing=south],Block{minecraft:piston}[extended=true,facing=north],Block{minecraft:piston}[extended=true,facing=north],Block{minecraft:piston}[extended=true,facing=south],Block{minecraft:piston}[extended=true,facing=north],Block{minecraft:piston}[extended=true,facing=south]}
    d=false
  ]

**Comment by konsolas** [comment]
Update ProtocolLib.

**Comment by CharlyZhu** [comment]
This is the latest version that I am able to get:
- https://dev.bukkit.org/projects/protocollib/files
- https://www.spigotmc.org/resources/protocollib.1997/

**Comment by konsolas** [comment]
Download the latest dev build which is needed for 1.16

**Comment by Janmm14** [comment]
Near the top on SpigotMC page of ProtocolLib:
> **If you're running 1.16, use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).**

**Comment by CharlyZhu** [comment]
Got it, cheers
