### ISSUE TITLE
1.16.4 NPE on Java 15

### ISSUE THREAD

**Issue by LogGits** [konsolas/AAC-Issues#2196]
Just got the M1, was testing aac on java 15 and found this error spamming console:
```
[18:35:16 WARN]: [AAC5] Task #4605 for AAC5 v5.0.11 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Number.floatValue()" because the return value of "java.util.Map.get(Object)" is null
	at me.konsolas.aac.f9.a(f9.java:6) ~[?:?]
	at me.konsolas.aac.f9.a(f9.java:15) ~[?:?]
	at me.konsolas.aac.hn.<init>(hn.java:95) ~[?:?]
	at me.konsolas.aac.hq.<init>(hq.java:46) ~[?:?]
	at me.konsolas.aac.Q.a(Q.java:51) ~[?:?]
	at me.konsolas.aac.Q.a(Q.java:119) ~[?:?]
	at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:2) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-409]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1289) ~[patched_1.16.4.jar:git-Paper-409]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-409]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-409]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-409]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-409]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
(P.S. gotta love those java 14+ useful npe's)
### Core information
**Server version**: 
1.16.4 paper build 409
**AAC version**: 
5.0.11
**ProtocolLib version**: 4.6.0

### Configuration
Cele's optimised config

**Comment by Janmm14** [comment]
Can you please try with default configuration. I think this error comes from an old config.

**Comment by LogGits** [comment]
Sure thing, ill try with a completely fresh aac install

**Comment by konsolas** [comment]
This is caused by an outdated configuration.
