### ISSUE TITLE
Async catch on getTargetBlock()

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#223]
>[15:36:55] [Netty Epoll Server IO #2/ERROR]: [AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC
>java.lang.IllegalStateException: Asynchronous entity world add!
>    at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
>    at net.minecraft.server.v1_8_R3.World.b(World.java:2633) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
>    at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:820) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
>   at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:158) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
>    at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
>    at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
>    at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
>    at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
    at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:72) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
    at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:233) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
    at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:268) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:160) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:195) ~[spigot.jar:git-Spigot-unknown-e1ebe52]
    at me.konsolas.aac.aO.onPacketReceiving(aO.java) ~[AAC.jar:3.0.0]

**Comment by konsolas** [comment]
Fix written.
