### ISSUE TITLE
Error aac 

### ISSUE THREAD

**Issue by Distolfix** [konsolas/AAC-Issues#2230]
[09:05:03 ERROR]: [AAC5] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC5
java.lang.IllegalArgumentException: Unknown enum constant RIDING_JUMP
        at com.comphenix.protocol.wrappers.EnumWrappers$AliasedEnumConverter.lambda$getSpecific$0(EnumWrappers.java:749) ~[ProtocolLib.jar:4.5.1]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_282]
        at com.comphenix.protocol.wrappers.EnumWrappers$AliasedEnumConverter.getSpecific(EnumWrappers.java:734) ~[ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.wrappers.EnumWrappers$AliasedEnumConverter.getSpecific(EnumWrappers.java:720) ~[ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.5.1]
        at me.konsolas.aac.aJ.a(aJ.java:6) ~[AAC-spigot-5.0.14-b1.jar:5.0.14]
        at me.konsolas.aac.eS.a(eS.java:9) ~[AAC-spigot-5.0.14-b1.jar:5.0.14]
        at me.konsolas.aac.timings.AACListener.onPacketReceiving(AACListener.java:22) ~[AAC-spigot-5.0.14-b1.jar:5.0.14]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:350) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:315) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:538) [ProtocolLib.jar:4.5.1]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) [ProtocolLib.jar:4.5.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
>
Minecraft server 1.8.8
protocol lib 4.5.1

**Comment by AppleMacOS** [comment]
I'd recommend updating your ProtocolLib to the latest version which is 4.6.0 at the moment.

**Comment by konsolas** [comment]
Update ProtocolLib.
