### ISSUE TITLE
[AAC5] Task #54379 for AAC5 v5.0.14 generated an exception

### ISSUE THREAD

**Issue by jnijland** [konsolas/AAC-Issues#2244]
### Issue description
Console is spammed with this error, can't use AAC5 on the server because of the console spam. 

```
[15:37:11 WARN]: [AAC5] Task #54379 for AAC5 v5.0.14 generated an exception
java.lang.NullPointerException: null
        at me.konsolas.aac.gr.a(gr.java:11) ~[?:?]
        at me.konsolas.aac.gr.a(gr.java:4) ~[?:?]
        at me.konsolas.aac.at.<init>(at.java:39) ~[?:?]
        at me.konsolas.aac.aJ.<init>(aJ.java:2) ~[?:?]
        at me.konsolas.aac.eS.a(eS.java:78) ~[?:?]
        at me.konsolas.aac.eS.a(eS.java:15) ~[?:?]
        at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:5) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1040]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1040]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Purpur-1040]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.16.5.jar:git-Purpur-1040]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1403) ~[patched_1.16.5.jar:git-Purpur-1040]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Purpur-1040]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1040]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Core information
**Server version**: 
This server is running Purpur version git-Purpur-1040 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 13 version(s) behind

**AAC version**: 
5.0.14-b1

**ProtocolLib version**: 
Build #499

**Plugin list**:
![image](https://user-images.githubusercontent.com/9889834/114404274-d75c6d80-9ba5-11eb-9290-6e1275851013.png)

### Special environment information
**ViaVersion version**:  Viaversion 3.2.1
**ViaBackwards version**: Viabackwards 3.2.0

### Configuration
No changes were made to the configuration.

**Comment by jnijland** [comment]
My bad, I used an old configuration file.
