### ISSUE TITLE
Paper spigot 1.17 bungee doesnt start AAC

### ISSUE THREAD

**Issue by Rawxdealz** [konsolas/AAC-Issues#2280]
28.06 17:42:13 [Server] INFO Enabling AAC5 v5.1.0
28.06 17:42:14 [Server] ERROR Error occurred while enabling AAC5 v5.1.0 (Is it up to date?)
28.06 17:42:14 [Server] INFO java.lang.NoSuchFieldError: FLYING
28.06 17:42:14 [Server] INFO at me.konsolas.aac.timings.AACListener.a(AACListener.java:8) ~[?:?]
28.06 17:42:14 [Server] INFO at me.konsolas.aac.timings.AACListener.<init>(AACListener.java:43) ~[?:?]
28.06 17:42:14 [Server] INFO at me.konsolas.aac.dO.<init>(dO.java:30) ~[?:?]
28.06 17:42:14 [Server] INFO at me.konsolas.aac.AAC.onEnable(AAC.java:44) ~[?:?]
28.06 17:42:14 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-55]
28.06 17:42:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-55]
28.06 17:42:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-55]
28.06 17:42:14 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-55]
28.06 17:42:14 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-55]
28.06 17:42:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.jar:git-Paper-55]
28.06 17:42:14 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-55]
28.06 17:42:14 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
28.06 17:42:14 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.06 17:42:14 [Server] INFO Disabling AAC5 v5.1.0

**Comment by Rawxdealz** [comment]
![afbeelding](https://user-images.githubusercontent.com/42896942/123682878-e02b1a00-d84b-11eb-92d6-a5c1258fb712.png)
Downloaded the newest protocollib and seemed to fix this.

Still some errors but it's running:
28.06 18:02:24 [Server] INFO Enabling AAC5 v5.1.0
28.06 18:02:25 [Server] WARN [PacketFilterManager] [AAC5] Unsupported client packet in current Minecraft version: FLYING[PLAY, CLIENT, 254, classNames: [net.minecraft.network.protocol.game.PacketPlayInFlying, net.minecraft.network.protocol.game.ServerboundFlyingPacket, net.minecraft.network.play.client.CPacketPlayer] (unregistered)]
28.06 18:02:25 [Server] WARN [PacketFilterManager] [AAC5] Unsupported client packet in current Minecraft version: FLYING[PLAY, CLIENT, 254, classNames: [net.minecraft.network.protocol.game.PacketPlayInFlying, net.minecraft.network.protocol.game.ServerboundFlyingPacket, net.minecraft.network.play.client.CPacketPlayer] (unregistered)]
28.06 18:02:25 [Server] INFO No stale entries to remove
28.06 18:02:26 [Server] INFO AAC is up to date

**Comment by Rawxdealz** [comment]
Get these errors while a hacker is playing:
28.06 18:51:31 [Server] WARN Task #11 for AAC5 v5.1.0 generated an exception
28.06 18:51:31 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.cj
28.06 18:51:31 [Server] INFO at me.konsolas.aac.de.<init>(de.java:82) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ab.<init>(ab.java:69) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ad.<init>(ad.java:71) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:131) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:36) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:2) ~[?:?]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.06 18:51:31 [Server] WARN Task #11 for AAC5 v5.1.0 generated an exception
28.06 18:51:31 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.cj
28.06 18:51:31 [Server] INFO at me.konsolas.aac.de.<init>(de.java:82) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ab.<init>(ab.java:69) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ad.<init>(ad.java:71) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:131) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:36) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:2) ~[?:?]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.06 18:51:31 [Server] WARN Task #11 for AAC5 v5.1.0 generated an exception
28.06 18:51:31 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.cj
28.06 18:51:31 [Server] INFO at me.konsolas.aac.de.<init>(de.java:82) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ab.<init>(ab.java:69) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ad.<init>(ad.java:71) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:131) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:36) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:2) ~[?:?]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.06 18:51:31 [Server] WARN Task #11 for AAC5 v5.1.0 generated an exception
28.06 18:51:31 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.cj
28.06 18:51:31 [Server] INFO at me.konsolas.aac.de.<init>(de.java:82) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ab.<init>(ab.java:69) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ad.<init>(ad.java:71) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:131) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:36) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:2) ~[?:?]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Rawxdealz** [comment]
Well the hacker left, but the messages are still coming, so my guess is it is not because of the hacker.

**Comment by Janmm14** [comment]
@Rawxdealz Please write that comment in the new issue I created for you.
