### ISSUE TITLE
Get these errors while a hacker is playing:

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#2281]
Get these errors while a hacker is playing:
```
28.06 18:51:31 [Server] WARN Task #11 for AAC5 v5.1.0 generated an exception
28.06 18:51:31 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.cj
28.06 18:51:31 [Server] INFO at me.konsolas.aac.de.<init>(de.java:82) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ab.<init>(ab.java:69) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ad.<init>(ad.java:71) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:131) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:36) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:2) ~[?:?]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.06 18:51:31 [Server] WARN Task #11 for AAC5 v5.1.0 generated an exception
28.06 18:51:31 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.cj
28.06 18:51:31 [Server] INFO at me.konsolas.aac.de.<init>(de.java:82) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ab.<init>(ab.java:69) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ad.<init>(ad.java:71) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:131) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:36) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:2) ~[?:?]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.06 18:51:31 [Server] WARN Task #11 for AAC5 v5.1.0 generated an exception
28.06 18:51:31 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.cj
28.06 18:51:31 [Server] INFO at me.konsolas.aac.de.<init>(de.java:82) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ab.<init>(ab.java:69) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ad.<init>(ad.java:71) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:131) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:36) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:2) ~[?:?]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.06 18:51:31 [Server] WARN Task #11 for AAC5 v5.1.0 generated an exception
28.06 18:51:31 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.cj
28.06 18:51:31 [Server] INFO at me.konsolas.aac.de.<init>(de.java:82) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ab.<init>(ab.java:69) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.ad.<init>(ad.java:71) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:131) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.dO.a(dO.java:36) ~[?:?]
28.06 18:51:31 [Server] INFO at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:2) ~[?:?]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
28.06 18:51:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
```
_Originally posted by @Rawxdealz in https://github.com/konsolas/AAC-Issues/issues/2280#issuecomment-869934914_

**Comment by Janmm14** [comment]
Every bug deserves its own issue.

**Comment by Rawxdealz** [comment]
The messages even appear when no hackers were online, so i dont think it is hacker related.
Removed the plugin because it made my console laggy.

**Comment by Janmm14** [comment]
I jsut noticed this bug happens because you run AAC on Minecraft 1.17, which is not yet supported.
