### ISSUE TITLE
[ERROR] `onPacketReceiving(PacketEvent)` No field with type boolean exists in class PacketPlayInVehicleMove.

### ISSUE THREAD

**Issue by Rollczi** [konsolas/AAC-Issues#2282]
![image](https://user-images.githubusercontent.com/49173834/123955367-ce5f8900-d9a9-11eb-8f6e-6ff00b5ff8d5.png)
![image](https://user-images.githubusercontent.com/49173834/123955562-0d8dda00-d9aa-11eb-95d0-35f4cd9d5a72.png)
ProtocolLib 4.6.1-SNAPSHOT-b505
```yml
[13:38:44 WARN]: [ProtocolLib] Loaded class me.konsolas.aac.ab from AAC5 v5.1.0 which is not a depend, softdepend or loadbefore of this plugin.
[13:38:44 ERROR]: [AAC5] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC5
com.comphenix.protocol.reflect.FieldAccessException: No field with type boolean exists in class PacketPlayInVehicleMove.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:218) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[?:?]
        at me.konsolas.aac.ab.b(ab.java:216) ~[?:?]
        at me.konsolas.aac.ab.a(ab.java:529) ~[?:?]
        at me.konsolas.aac.ad.a(ad.java:58) ~[?:?]
        at me.konsolas.aac.dO.a(dO.java:55) ~[?:?]
        at me.konsolas.aac.timings.AACListener.onPacketReceiving(AACListener.java:44) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.16.5.jar:git-Paper-e04368045]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[13:38:44 ERROR]: Parameters:
  net.minecraft.server.v1_16_R3.PacketPlayInVehicleMove@4ebef9e2[
    a=-3880.056679339329
    b=66.0
    c=-2411.8250289056814
    d=173.40508
    e=10.0
  ]
```

**Comment by Janmm14** [comment]
Sees like konsolas somehow unfixed #2029
