### ISSUE TITLE
AAC print error

### ISSUE THREAD

**Issue by SharkblackFr** [konsolas/AAC-Issues#2301]
### Issue description

Can you help me to resolve this error

### Core information
**Server version**: 

**AAC version**: 

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by SharkblackFr** [comment]
I have new error:
```
22:16:43 ERROR]: [AAC5] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC5
java.lang.NoClassDefFoundError: org/bukkit/util/BoundingBox
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2309) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.nd.d(Unknown Source) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.lq.<clinit>(lq.java) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:315) ~[?:?]
        at me.konsolas.aac.nd.b(Unknown Source) ~[?:?]
        at me.konsolas.aac.nd.d(Unknown Source) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.e5.lambda$static$0(e5.java) ~[?:?]
        at me.konsolas.aac.e5.a(e5.java:111) ~[?:?]
        at me.konsolas.aac.e5.<clinit>(e5.java:118) ~[?:?]
        at me.konsolas.aac.iS.a(iS.java:2) ~[?:?]
        at me.konsolas.aac.timings.AACListener.onPacketReceiving(AACListener.java:69) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) ~[patched_1.12.2.jar:git-Paper-1618]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.util.BoundingBox
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 61 more
[22:16:43 ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook@7e7cdaaa[
    x=1248.3900051947264
    y=63.0
    z=-154.39360255594312
    yaw=139.19897
    pitch=47.99996
    f=false
    hasPos=true
    hasLook=true
  ]
```
