### ISSUE TITLE
Error occurred while enabling AAC5 v5.2.0

### ISSUE THREAD

**Issue by Tazmyan** [konsolas/AAC-Issues#2302]
### Issue description
```
[ERROR] Error occurred while enabling AAC5 v5.2.0 (Is it up to date?)
java.lang.AbstractMethodError: java/sql/Connection.isValid(I)Z
at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
at me.konsolas.aac.kc.a(kc.java:8) ~[?:?]
at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
at me.konsolas.aac.jI.a(jI.java:28) ~[?:?]
at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
at me.konsolas.aac.jI.<init>(jI.java:140) ~[?:?]
at me.konsolas.aac.jI.a(jI.java:78) ~[?:?]
at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
at me.konsolas.aac.AAC.onEnable(AAC.java:83) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]
```

Core information
**Server version**: Spigot 1.8.8

**AAC version**: 5.2.0

**ProtocolLib version**: 4.7.0

**ViaVersion version**:  4.0.1

**ProtocolSupport version**:  none

**ViaBackwards version**: none

**BungeeCord plugins**: i don't use bungeecord

**Comment by UnnamedWarrior** [comment]
Bruh same

**Comment by Janmm14** [comment]
try to use 5.0.14 for non 1.17 servers

**Comment by TheAltening156** [comment]
you need to downgrade to java 14
