### ISSUE TITLE
AAC Crash

### ISSUE THREAD

**Issue by kh0mka** [konsolas/AAC-Issues#2318]
**The database was never connected, there were no problems for a month. Then such errors will pour in for all players + TPS drops to 0.**
How it works: starting the server. Half a minute passes = errors + TPS drops to 0. Removing database.db did not help.
Version: 1.16.5
AAC: 5.0.7
AACAdditinPro: 7.1.2

[15:15:03] [User Authenticator #1936/ERROR]: [AAC5] failed to retrieve login info for c1779ec3-6f42-3f27-9344-31e344b51357
java.sql.SQLTransientConnectionException: AACSQLitePool - Connection is not available, request timed out after 30000ms.
	at aacinternal.shaded.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695) ~[?:?]
	at aacinternal.shaded.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[?:?]
	at aacinternal.shaded.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[?:?]
	at aacinternal.shaded.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at me.konsolas.aac.d6.a(d6.java:13) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor272.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at me.konsolas.aac.d6.a(d6.java:67) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor270.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at me.konsolas.aac.AAC.a(AAC.java:65) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor269.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at me.konsolas.aac.AAC.a(AAC.java:63) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor40.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-12]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) [patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) [patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) [patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:337) [patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.LoginListener$1.run(LoginListener.java:228) [patched_1.16.5.jar:git-Airplane-12]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by Janmm14** [comment]
Update to 5.0.14-b1 at least
