### ISSUE TITLE
Error occurred while enabling AAC5 v5.2.0 (Is it up to date?)  How to fix it?

### ISSUE THREAD

**Issue by HerenYU2007** [konsolas/AAC-Issues#2320]
Error occurred while enabling AAC5 v5.2.0 (Is it up to date?)
java.lang.AbstractMethodError
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.kc.a(kc.java:8) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.jI.a(jI.java:28) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.jI.<init>(jI.java:140) ~[?:?]
        at me.konsolas.aac.jI.a(jI.java:78) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.AAC.onEnable(AAC.java:83) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
        
        
server:paper-1.8.8
ProtocolLib:4.8.0
AAC version: 5.2.0
        Plz help me to fix it!

**Comment by Janmm14** [comment]
5.1.0 and 5.2.0 only work good on 1.16 servers
use 5.0.14b1
OR BETTER: SWITCH ANTICHEAT
