### ISSUE TITLE
Error occurred while enabling AAC v3.5.0 (Is it up to date?)

### ISSUE THREAD

**Issue by LowIQWithAutism** [konsolas/AAC-Issues#2321]
### Issue description

[19:15:21] [Server thread/ERROR]: Error occurred while enabling AAC v3.5.0 (Is it up to date?)
java.lang.NullPointerException: null
	at me.konsolas.aac.cB.a(cB.java) ~[?:?]
	at me.konsolas.aac.cB.a(cB.java:56) ~[?:?]
	at me.konsolas.aac.AAC.a(AAC.java) ~[?:?]
	at me.konsolas.aac.AAC.onEnable(AAC.java:44) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

### Core information
**Server version**: 
1.12.2
**AAC version**: 
AAC v3.5.0
**ProtocolLib version**: 
4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by LowIQWithAutism** [comment]
.
