### ISSUE TITLE
Error occurred while enabling AAC v3.5.0 (Is it up to date?)

### ISSUE THREAD

**Issue by Andre60z** [konsolas/AAC-Issues#2322]
[AAC] Enabling AAC v3.5.0
[AAC] Error enabling AAC: 0x05
[AAC] Please report this to konsolas
[AAC] Disabling AAC v3.5.0
[AAC] Disabling checks...
Error occurred while enabling AAC v3.5.0 (Is it up to date?)
java.lang.NullPointerException: null
	at me.konsolas.aac.cB.a(cB.java) ~[?:?]
	at me.konsolas.aac.cB.a(cB.java:56) ~[?:?]
	at me.konsolas.aac.AAC.a(AAC.java) ~[?:?]
	at me.konsolas.aac.AAC.onEnable(AAC.java:44) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by Janmm14** [comment]
Plugin is abandoned. Errors will not be fixed.
This error is related to antipiracy server (api1.konsolas.net) timings out. Newer versions handle this differently. But of course newer versions have vastly different movement check.
