### ISSUE TITLE
Error v3.5.0

### ISSUE THREAD

**Issue by Reinhart221** [konsolas/AAC-Issues#2324]
Error occurred while enabling AAC v3.5.0 (Is it up to date?)
java.lang.NullPointerException: null
	at me.konsolas.aac.cB.a(cB.java) ~[?:?]
	at me.konsolas.aac.cB.a(cB.java:56) ~[?:?]
	at me.konsolas.aac.AAC.a(AAC.java) ~[?:?]
	at me.konsolas.aac.AAC.onEnable(AAC.java:44) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]

**Comment by Janmm14** [comment]
Switch anticheat to Grim or buy better, current anticheat like vulcan, karhu or how these newer and much better anticheats are all named.

if you have a bit more spare money,
and a bigger cheater problem, perhaps even using purcharsed cheat clients,
i would advice to choose a monthly plan of Intave, its cloud features catches many current killaura cheats.

Disclaimer: i am currently an unpaid volunteer supporter on Intave anticheat.

**Comment by Janmm14** [comment]
See #2322
