### ISSUE TITLE
java.lang.IllegalStateException: Start block missed in BlockIterator

### ISSUE THREAD

**Issue by Fluxty** [konsolas/AAC-Issues#288]
liquidbounce
Working: Ice speed

Wolfram & Liquidbounce
Working: Regen (minimal testing)

Error:
```
Could not pass event PlayerMoveEvent to AAC v3.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: Start block missed in BlockIterator
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:170) ~[PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:233) ~[PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:268) ~[PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:162) ~[PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:197) ~[PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	at me.konsolas.aac.a3.a(a3.java:22) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor362.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot-1.8.8dev.jar:git-PaperSpigot-"8b18730"]
	... 16 more
```

I understand errors like the above have been posted but the issue here is that on our production servers with over 100 concurrent players this error could become a big issue in console.

**Comment by CeIebrimbor** [comment]
AAC version? ProtocolLib Version? Were you using the default config or my config for this?

**Comment by Janmm14** [comment]
Can you format it using three ` in the line above the stacktrace and in the line below the stacktrace please? It makes the exception more reable as its then formatted as 
```
code block
```
instead of `inline code`.

**Comment by Janmm14** [comment]
@Fluxty Please create separate issues for those and include more details in those. I'll take this issue now as report of the console error.

**Comment by konsolas** [comment]
Completed.
