### ISSUE TITLE
nuker -no detect

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#306]
[17:29:04 INFO]: [AAC] Enabling AAC v3.0.0
[17:29:06 WARN]: Exception in thread "Craft Scheduler Thread - 18"
[17:29:06 WARN]: org.apache.commons.lang.UnhandledException: Plugin AAC v3.0.0 generated an exception while executing task 1686
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at me.konsolas.aac.d9.run(d9.java:2)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

v3.0.1 0 errors

### Core information
**Server version**: 1.8.x

**AAC version**: 3.0 / 3.0.1

**ProtocolLib version**: 4.1 and 4.2(testing)

**Plugin list**: maxbans/pex 1.23.4/essentials

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**:1.0.3

**ProtocolSupport version**: ----

**ViaBackwards version**:----

**BungeeCord plugins**: ---

### Reporting issues encountered on the test server has these additional rules:

https://youtu.be/du74ra4oVjg -films

**Comment by ProDash1998** [comment]
unauthorized player can enter / aac and check the versions of the plugin. in Version 3.0 and 3.0.1 do not detect nukers

**Comment by ProDash1998** [comment]
Please also to add that the plugin was checking players to the ping. for example, bans plugin / kick players having 250+ ping

**Comment by konsolas** [comment]
The nuker you're showing does not break blocks faster than normal, so it does not gain an advantage over normal players. 

AAC will block nukers that break blocks faster than normal.
