### ISSUE TITLE
bad dl wersion

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#312]
[14:50:17 ERROR]: Error occurred while disabling AAC v3.0.1 (Is it up to date?)
java.lang.NullPointerException
        at me.konsolas.aac.AAC.onDisable(AAC.java:15) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[acmc.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [acmc.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423) [acmc.jar:git-PaperSpigot-"8b18730"]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at me.konsolas.aac.bR.a(bR.java:94) [AAC%20(2).jar:3.0.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at me.konsolas.aac.c9.run(c9.java:44) [AAC%20(2).jar:3.0.1]

I've downloaded version 3.0.2 and spigot writes me that I have 3.0.1 please improvement download link

**Comment by Janmm14** [comment]
You did not downloaded `AAC v3.0.2` because there is no `AAC v3.0.2`. The current AAC version is `3.0.1-b2`.
