### ISSUE TITLE
IllegalArgumentException Exception 

### ISSUE THREAD

**Issue by klon5555** [konsolas/AAC-Issues#322]
```
[20:16:47] [Server thread/WARN]: [AAC] Task #61 for AAC v3.0.1 generated an exception
java.lang.IllegalArgumentException: java.lang.ClassCastException@2998af70
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_74]
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_74]
	at me.konsolas.aac.b4.a(b4.java:37) ~[?:?]
	at me.konsolas.aac.b4.a(b4.java:65) ~[?:?]
	at me.konsolas.aac.b4.a(b4.java:8) ~[?:?]
	at me.konsolas.aac.cl.b(cl.java:1) ~[?:?]
	at me.konsolas.aac.a5.run(a5.java:4) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
```

**Server version**: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 3.0.1

**ProtocolLib version**: 4.2.1

**Plugin list**: I am sure the error is not caused by conflict

**ViaVersion version**: 1.0.3

**Comment by klon5555** [comment]
Also we have crash log
`[20:17:55] [Spigot Watchdog Thread/ERROR]: Current Thread: Server thread
[20:17:55] [Spigot Watchdog Thread/ERROR]: 	PID: 16 | Suspended: false | Native: false | State: RUNNABLE
[20:17:55] [Spigot Watchdog Thread/ERROR]: 	Stack:
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.World.a(World.java:2514)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.World.getEntities(World.java:2503)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.World.getCubes(World.java:1214)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		java.lang.reflect.Method.invoke(Unknown Source)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		java.lang.reflect.Method.invoke(Unknown Source)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		me.konsolas.aac.b4.a(b4.java:26)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$DMH/1259302135.invokeStatic_LL_L(LambdaForm$DMH)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$BMH/1131679427.reinvoke(LambdaForm$BMH)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$MH/427591061.linkToTargetMethod(LambdaForm$MH)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		me.konsolas.aac.b4.a(b4.java:65)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$DMH/846657252.invokeStatic_L3D_I(LambdaForm$DMH)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$BMH/888545967.reinvoke(LambdaForm$BMH)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$MH/1254153067.linkToTargetMethod(LambdaForm$MH)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		me.konsolas.aac.b4.a(b4.java:8)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		me.konsolas.aac.cl.b(cl.java:1)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		me.konsolas.aac.a5.run(a5.java:4)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[20:17:55] [Spigot Watchdog Thread/ERROR]: 		java.lang.Thread.run(Unknown Source)`

**Comment by Photon-GitHub** [comment]
Is this still valid? If yes, please change to Protocollib version 4.2.0 as 4.2.1 is Minecraft 1.11 only.

**Comment by JampireX** [comment]
With 4.2.0 error has not been seen for a month.
I think the problem is solved.
