### ISSUE TITLE
Single exception at startup

### ISSUE THREAD

**Issue by klon5555** [konsolas/AAC-Issues#335]
```
[02:43:51 WARN]: [AAC] Task #63 for AAC v3.0.1 generated an exception
java.lang.IllegalStateException: REFLECTION ERROR
        at me.konsolas.aac.b4.a(b4.java:16) ~[?:?]
        at me.konsolas.aac.b4.a(b4.java:9) ~[?:?]
        at me.konsolas.aac.b4.a(b4.java:65) ~[?:?]
        at me.konsolas.aac.b4.a(b4.java:8) ~[?:?]
        at me.konsolas.aac.cl.b(cl.java:1) ~[?:?]
        at me.konsolas.aac.a5.run(a5.java:4) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodException: com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$6125c00.getHandle()
        at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_111]
        at me.konsolas.aac.b4.a(b4.java:94) ~[?:?]
        ... 11 more
```

**Server version**: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 3.0.1 b2

**ProtocolLib version**: 4.2.1

**ViaVersion version**: 1.0.3

**Comment by CeIebrimbor** [comment]
ProtocolLib 4.2.1 is for 1.11.x servers. Drop to 4.2.0.
