### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by kukubaczek** [konsolas/AAC-Issues#351]
[20:05:39] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.0.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:847) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:772) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:500) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1585) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at me.konsolas.aac.ao.a(ao.java:3) ~[?:?]
	at me.konsolas.aac.cD.a(cD.java:36) ~[?:?]
	at me.konsolas.aac.cJ.a(cJ.java:3) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor185.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	... 26 more

**Comment by CeIebrimbor** [comment]
ProtocolLib version?

Plugins with special entities?

**Comment by konsolas** [comment]
Closing due to insufficient info.
