### ISSUE TITLE
eroor in console

### ISSUE THREAD

**Issue by CloudeLecaw** [konsolas/AAC-Issues#353]
i found the error in the console whole the server was running normaly

errorlog:

> [09:24:03] [Thread-7/ERROR]: [AAC] Could not check version (1): null
[09:24:03] [Thread-7/WARN]: [AAC] Detected update checking problem. Disabling AAC
[09:24:03] [Thread-7/INFO]: [AAC] Disabling AAC v3.0.1
[09:24:03] [Thread-7/INFO]: [AAC] Disabling checks...
[09:24:03] [Thread-7/ERROR]: Error occurred while disabling AAC v3.0.1 (Is it up to date?)
java.lang.NullPointerException
	at me.konsolas.aac.AAC.onDisable(AAC.java:15) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot.jar:git-Spigot-7d78b81-613be0d]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-7d78b81-613be0d]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-7d78b81-613be0d]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at me.konsolas.aac.bR.a(bR.java:94) [AAC_3.0.1-b2.jar:3.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at me.konsolas.aac.c9.run(c9.java:44) [AAC_3.0.1-b2.jar:3.0.1]
[09:24:03] [Thread-7/INFO]: [AAC] Error enabling AAC: 0x02
[09:24:03] [Thread-7/INFO]: [AAC] Please report this to konsolas

**Comment by Rqcco** [comment]
Your lacking lots of information. Please use the overview template and label the versions.

**Comment by CeIebrimbor** [comment]
Did you have internet connection when starting server?

**Comment by Rqcco** [comment]
Closing due to no information
