### ISSUE TITLE
bug "new" version

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#362]
AAC version 3.0.1-b2
Spigot 1.8.8 (1.8_r3)
ViaVersion 1.0.3

>aacreload
[22:39:47 INFO]: [---] > Reload request has been registered.
[22:39:47 INFO]: [AAC] Beginning disable...
[22:39:47 INFO]: [AAC] Disabling AAC v3.0.1
[22:39:47 INFO]: [AAC] Disabling checks...
[22:39:47 INFO]: [AAC] Saving log file...
[22:39:47 INFO]: plist
[22:39:47 INFO]: [AAC] Enabling AAC v3.0.1
[22:39:49 INFO]: [INFO] ╗ Ranga Gracz to zamalo? Kup vip'a :) /vip.
[22:39:49 WARN]: Exception in thread "Craft Scheduler Thread - 1"
[22:39:49 WARN]: org.apache.commons.lang.UnhandledException: Plugin AAC v3.0.1 generated an exception while executing task 1150
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at me.konsolas.aac.da.run(da.java:6)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[22:39:49 WARN]: Exception in thread "Craft Scheduler Thread - 3"
[22:39:49 WARN]: org.apache.commons.lang.UnhandledException: Plugin AAC v3.0.1 generated an exception while executing task 1150
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at me.konsolas.aac.da.run(da.java:6)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

 When reload plugins shows:
[22:39:49 INFO]: ž6[---] žr> ž6A new version of AAC is available!
[22:39:50 INFO]: [AAC] Beginning Enable...
[22:39:50 INFO]: [AAC] Checking config file...
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check chat.Spam
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check combat.Hitbox
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check combat.Criticals
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check combat.Fastbow
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check combat.FightSpeed
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check combat.Knockback
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check combat.Regen
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check combat.FastUse
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check combat.Killaura
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check combat.Heuristics
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check movement.BadPackets
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check movement.Speed
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check movement.Phase
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check movement.Fly
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check movement.NoFall
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check movement.Climb
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check movement.Jesus
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check movement.Derp
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check world.FastBreak
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check world.FastPlace
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check world.Nuker
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check world.NoSwing
[22:39:50 INFO]: [AAC] (CheckManager) Enabling check world.Interact
[22:39:50 INFO]: [AAC] Starting API...
[22:39:50 INFO]: [AAC] AAC has been enabled.

**Comment by ProDash1998** [comment]
protocollib 4.2
