### ISSUE TITLE
Could not check version ERROR

### ISSUE THREAD

**Issue by XiaoLin0815** [konsolas/AAC-Issues#364]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
https://oss.yun.xiaolinc.cc/o_1b6fkqq171u7urud1g6b10ff1fgha.zip
* Video of the bug / bypass, best with verbose chat output

`[20:30:23 ERROR]: [AAC] Could not check version (1): null
[20:30:23 WARN]: §6[AAC] §r>§6 Could not check AAC version
[20:30:23 WARN]: [AAC] Detected update checking problem. Disabling AAC
[20:30:23 INFO]: [AAC] Disabling AAC v3.0.1
[20:30:23 INFO]: [AAC] Disabling checks...
[20:30:23 ERROR]: Error occurred while disabling AAC v3.0.1 (Is it up to date?)
java.lang.NullPointerException
at me.konsolas.aac.AAC.onDisable(AAC.java:15) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[s
pigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoade
r.java:364) [spigot.jar:git-Spigot-db6de12-18fbb24]
at pw.yumc.Yum.inject.YumPluginLoader.disablePlugin(YumPluginLoader.java
:105) [Yum.jar:?]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManag
er.java:424) [spigot.jar:git-Spigot-db6de12-18fbb24]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_111]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_111]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_111]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
at me.konsolas.aac.bR.a(bR.java:94) [AAC.jar:3.0.1]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_111]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_111]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_111]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_111]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_111]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_111]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
at me.konsolas.aac.c9.run(c9.java:44) [AAC.jar:3.0.1]
[20:30:23 INFO]: [AAC] Error enabling AAC: 0x02
[20:30:23 INFO]: [AAC] Please report this to konsolas`

* The ingame name of the involved players

### Core information
**Server version**: insert

**AAC version**: insert

**ProtocolLib version**: 4.2

**Plugin list**: 
`[07:22:23 INFO]: [Yum仓库]服务器已安装插件:
[07:22:23 INFO]: [TellRawLib] 使用ProtocolLib序列化类处理...
[07:22:23 INFO]: - OreBroadcast (1.3.4)           更新 卸载 重载 删除
[07:22:23 INFO]: - TerrainControl (2.7.2)         更新 卸载 重载 删除
[07:22:23 INFO]: - iConomy_Recreation (8.0)       更新 卸载 重载 删除
[07:22:23 INFO]: - GroupManager (2.2-SNAPSHOT)    更新 卸载 重载 删除
[07:22:23 INFO]: - ArmorStandTools (2.1.4)        更新 卸载 重载 删除
[07:22:23 INFO]: - warfare (1)                    更新 卸载 重载 删除
[07:22:23 INFO]: - SuperTrails (9.5.5)            更新 卸载 重载 删除
[07:22:23 INFO]: - RandomPlacer (2.0)             更新 卸载 重载 删除
[07:22:23 INFO]: - Yum (2.7.7-git-1ef47)          更新 卸载 重载 删除
[07:22:23 INFO]: - AT (6.0)                       更新 卸载 重载 删除
[07:22:23 INFO]: - Skins (1.8.3)                  更新 卸载 重载 删除
[07:22:23 INFO]: - GereksizMesajKapama (1.0)      更新 卸载 重载 删除
[07:22:23 INFO]: - CoreProtect (2.12.0)           更新 卸载 重载 删除
[07:22:23 INFO]: - WorldEdit (6.1.3;7a097ca)      更新 卸载 重载 删除
[07:22:23 INFO]: - PlayerCommands (1.0.0)         更新 卸载 重载 删除
[07:22:23 INFO]: - Essentials (TeamCity)          更新 卸载 重载 删除
[07:22:23 INFO]: - EasyCommand (1.0)              更新 卸载 重载 删除
[07:22:23 INFO]: - JoinClearScreen (1.0)          更新 卸载 重载 删除
[07:22:23 INFO]: - CommandSay (1.0)               更新 卸载 重载 删除
[07:22:23 INFO]: - BungeeSuitePortals (0.5b-9)    更新 卸载 重载 删除
[07:22:23 INFO]: - PacketListenerApi (3.4.4)      更新 卸载 重载 删除
[07:22:23 INFO]: - DecoHeads (1.2)                更新 卸载 重载 删除
[07:22:23 INFO]: - Multiverse-Core (2.5.0-SNAPSHOT-) 更新 卸载 重载 删除
[07:22:23 INFO]: - SignEdit (0.1)                 更新 卸载 重载 删除
[07:22:23 INFO]: - Title (1.0.1)                  更新 卸载 重载 删除
[07:22:23 INFO]: - SimpleORM (0.3.2)              更新 卸载 重载 删除
[07:22:23 INFO]: - CommandCode (1.0)              更新 卸载 重载 删除
[07:22:23 INFO]: - EffectLib (4.2)                更新 卸载 重载 删除
[07:22:23 INFO]: - ConditionalCommands (1.1)      更新 卸载 重载 删除
[07:22:23 INFO]: - APC (1.0beta)                  更新 卸载 重载 删除
[07:22:23 INFO]: - Vault (1.5.6-b49)              更新 卸载 重载 删除
[07:22:23 INFO]: - ChairStairs (1.1)              更新 卸载 重载 删除
[07:22:23 INFO]: - MultiKillW (3.1)               更新 卸载 重载 删除
[07:22:23 INFO]: - QuickShop (0.9.29)             更新 卸载 重载 删除
[07:22:23 INFO]: - AncientGatesReloaded (1.8.4)   更新 卸载 重载 删除
[07:22:23 INFO]: - ServerSigns (4.5.1)            更新 卸载 重载 删除
[07:22:23 INFO]: - ViaVersion (1.0.3)             更新 卸载 重载 删除
[07:22:23 INFO]: - BossShop (2.7.0)               更新 卸载 重载 删除
[07:22:23 INFO]: - EssentialsSpawn (TeamCity)     更新 卸载 重载 删除
[07:22:23 INFO]: - ParticleHats (3.0.2)           更新 卸载 重载 删除
[07:22:23 INFO]: - ProtocolLib (3.7-SNAPSHOT-b2)  更新 卸载 重载 删除
[07:22:23 INFO]: - Cdkey (1.3)                    更新 卸载 重载 删除
[07:22:23 INFO]: - BannerMaker (1.4.5)            更新 卸载 重载 删除
[07:22:23 INFO]: - Citizens (2.0.16-SNAPSHOT)     更新 卸载 重载 删除
[07:22:23 INFO]: - Residence (4.5.9.0)            更新 卸载 重载 删除
[07:22:23 INFO]: - HolographicDisplays (2.2)      更新 卸载 重载 删除
[07:22:23 INFO]: - AAC (3.0.1)                    更新 卸载 重载 删除
[07:22:23 INFO]: - SkinsRestorer (9.3)            更新 卸载 重载 删除
[07:22:23 INFO]: - LockettePro (2.1.8)            更新 卸载 重载 删除
[07:22:23 INFO]: - ProtectionLib (0.5.4)          更新 卸载 重载 删除
[07:22:23 INFO]: - PerPlayerBlood (1.9.2)         更新 卸载 重载 删除
[07:22:23 INFO]: - LiteBans (2.1.21)              更新 卸载 重载 删除
>`

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.03

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**:  ![image](https://oss.yun.xiaolinc.cc/o_1b6fkn1sqfol1s801j3b93g1j83a.png)

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by Photon-GitHub** [comment]
You probably don't have a proper internet connection to spigot and konsolas servers.

**Comment by XiaoLin0815** [comment]
https://oss.yun.xiaolinc.cc/o_1b6fmq9iq22k18leutb19c7j9ma.png
But i can sufe it???

**Comment by SnakeDaoust1232** [comment]
Make sure your firewall isn't preventing outgoing connections.

**Comment by CeIebrimbor** [comment]
You said ProtocolLib 4.2 but your log says: **ProtocolLib (3.7-SNAPSHOT-b2)**
