### ISSUE TITLE
Compatibility issue with Sentinel (Detects NPCs cheating?)

### ISSUE THREAD

**Issue by PsychoLynx** [konsolas/AAC-Issues#365]
### Issue description

AAC generates a ton of the same kind of error in the console when Sentinel NPCs (Citizens addon) attack mobs, which in excess can crash the server (the NPCs can kill the mobs just fine, though). Tested in my own test server environment with only Citizens, Sentinel, AAC and ProtocolLib.

AAC log: (For the record, Paavo is the name of the NPC)

```
[15-01-2017 09:21:02.976] (CheckManager) Enabled check chat.Spam
[15-01-2017 09:21:02.998] (CheckManager) Enabled check combat.Hitbox
[15-01-2017 09:21:03.015] (CheckManager) Enabled check combat.Criticals
[15-01-2017 09:21:03.027] (CheckManager) Enabled check combat.Fastbow
[15-01-2017 09:21:03.046] (CheckManager) Enabled check combat.FightSpeed
[15-01-2017 09:21:03.069] (CheckManager) Enabled check combat.Knockback
[15-01-2017 09:21:03.097] (CheckManager) Enabled check combat.Regen
[15-01-2017 09:21:03.110] (CheckManager) Enabled check combat.FastUse
[15-01-2017 09:21:03.152] (CheckManager) Enabled check combat.Killaura
[15-01-2017 09:21:03.238] (CheckManager) Enabled check combat.Heuristics
[15-01-2017 09:21:03.298] (CheckManager) Enabled check movement.BadPackets
[15-01-2017 09:21:03.365] (CheckManager) Enabled check movement.Speed
[15-01-2017 09:21:03.390] (CheckManager) Enabled check movement.Phase
[15-01-2017 09:21:03.472] (CheckManager) Enabled check movement.Fly
[15-01-2017 09:21:03.494] (CheckManager) Enabled check movement.NoFall
[15-01-2017 09:21:03.507] (CheckManager) Enabled check movement.Climb
[15-01-2017 09:21:03.518] (CheckManager) Enabled check movement.Jesus
[15-01-2017 09:21:03.523] (CheckManager) Enabled check movement.Derp
[15-01-2017 09:21:03.538] (CheckManager) Enabled check world.FastBreak
[15-01-2017 09:21:03.550] (CheckManager) Enabled check world.FastPlace
[15-01-2017 09:21:03.564] (CheckManager) Enabled check world.Nuker
[15-01-2017 09:21:03.577] (CheckManager) Enabled check world.NoSwing
[15-01-2017 09:21:03.613] (CheckManager) Enabled check world.Interact
[15-01-2017 09:21:03.654] AAC has been enabled
[15-01-2017 09:21:05.303] (TPSManager) TPS dropped to 15.048908954100828
[15-01-2017 09:21:05.324] (CheckManager) Disabled check movement.BadPackets
[15-01-2017 09:21:05.331] (CheckManager) Disabled check combat.FightSpeed
[15-01-2017 09:21:05.337] (CheckManager) Disabled check combat.Hitbox
[15-01-2017 09:21:05.445] (TPSManager) TPS dropped to 18.39926402943882
[15-01-2017 09:21:06.116] (CheckManager) Enabled check movement.BadPackets
[15-01-2017 09:21:06.117] (CheckManager) Enabled check combat.Hitbox
[15-01-2017 09:21:06.119] (CheckManager) Enabled check combat.FightSpeed
[15-01-2017 09:22:53.961] (TPSManager) TPS dropped to 18.35704451583295
[15-01-2017 09:23:00.649] (TPSManager) TPS dropped to 17.38374619730552
[15-01-2017 09:23:00.651] (CheckManager) Disabled check movement.BadPackets
[15-01-2017 09:23:00.652] (CheckManager) Disabled check combat.FightSpeed
[15-01-2017 09:23:01.226] (TPSManager) TPS dropped to 17.84121320249777
[15-01-2017 09:23:01.771] (CheckManager) Enabled check movement.BadPackets
[15-01-2017 09:23:01.774] (CheckManager) Enabled check combat.FightSpeed
[15-01-2017 09:23:10.440] Paavo failed Knockback: didn't move away from his attacker when hit [ping:1 tps:19.59] VL:3
```

(For the record, Paavo is the name of the NPC)

Full console error:

```
[09:23:07] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.0.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:90) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:575) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:480) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:607) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1309) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:855) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.EntityZombie.damageEntity(EntityZombie.java:163) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:238) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.mcmonkey.sentinel.SentinelTrait.punch(SentinelTrait.java:725) [sentinel-1.0.jar:?]
	at org.mcmonkey.sentinel.SentinelTrait.tryAttack(SentinelTrait.java:1188) [sentinel-1.0.jar:?]
	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1551) [sentinel-1.0.jar:?]
	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1658) [sentinel-1.0.jar:?]
	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430) [citizens-2.0.21-SNAPSHOT.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268) [citizens-2.0.21-SNAPSHOT.jar:?]
	at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:140) [citizens-2.0.21-SNAPSHOT.jar:?]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:980) [citizens-2.0.21-SNAPSHOT.jar:?]
	at net.citizensnpcs.util.NMS.tick(NMS.java:270) [citizens-2.0.21-SNAPSHOT.jar:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [citizens-2.0.21-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.RuntimeException: FAILED TO GET ITEM USE STATE
	at me.konsolas.aac.aT.a(aT.java:11) ~[?:?]
	at me.konsolas.aac.cG.a(cG.java:65) ~[?:?]
	at me.konsolas.aac.cJ.a(cJ.java:3) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	... 30 more
Caused by: java.lang.NoSuchFieldException: activeItem
	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_92]
	at me.konsolas.aac.aT.a(aT.java:20) ~[?:?]
	at me.konsolas.aac.cG.a(cG.java:65) ~[?:?]
	at me.konsolas.aac.cJ.a(cJ.java:3) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-7d78b81-f709362]
	... 30 more

```

It only seems to happen when the NPC is equipped with an item (I tested with a diamond sword only, so I dont know if other items trigger it). Bare hands does not.

### Core information
**Server version**: CraftBukkit version git-Spigot-7d78b81-f709362 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**AAC version**: 3.0.1-b2

**ProtocolLib version**: v4.2.1-SNAPSHOT-b346

**Plugin list**: Citizens v2.0.21-SNAPSHOT (build 1465), Sentinel v1.0 (build 98)

All plugins are latest as of January 15 2017

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**:  none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
The appropriate approach to compatibility with an anti-cheat is typically a one-way street. Sounds conceited, but it's based in practicality. The 3-5 major anti-cheats(AAC, NCP, etc) can try to hook **hundreds or thousands** of non-vanilla (conflicting) plugins **or** the handful of non-vanilla plugin developers can take a minute to tie into the major anti-cheats so plugins like AAC are no muddied up trying to be all things to all people.

AAC's API is public on AAC's [Overview Page](https://www.spigotmc.org/resources/aac-advanced-anti-cheat-hack-kill-aura-blocker.6442/) on Spigot. Developers should revel at the opportunity to say their plugins are compatible with all public anti-cheat plugins. Like [this plugin](https://www.spigotmc.org/resources/vein-miner.12038/). That way, only the servers with conflicting plugins have a special hook when it notices an anti-cheat being used instead of AAC taking longer to startup and increasing download size testing for hundreds of plugins on each startup or reload.

**Comment by Janmm14** [comment]
Is not causing any harm except possible spam.

**Comment by CeIebrimbor** [comment]
Additional Note:
I talked to the dev and he has decided it's AAC's problem and that anti-cheats should hook his plugin.

**Comment by Janmm14** [comment]
Yeah as your text does not apply here at all, because the dev can't prevent this exception.
Still its just an exception and shouldn't harm.

**Comment by CeIebrimbor** [comment]
Got it. We will just leave this compatibility request on the tracker for the rest of time considering it was requested back in AAC v3.0.1

**Comment by konsolas** [comment]
No longer valid because AAC now handles move checks at the packet level.

**Comment by Janmm14** [comment]
@konsolas This was not about movement, but about combat which is handled via events.
