### ISSUE TITLE
Error IllegalArgumentException: ClassCastException AAC 3.0.3 dv.a:85

### ISSUE THREAD

**Issue by Reeferx7** [konsolas/AAC-Issues#421]
I have a lot spam on my console with that error:

[14:00:06] [Server thread/WARN]: [AAC] Task #164650 for AAC v3.0.3 generated an exception
java.lang.IllegalArgumentException: java.lang.ClassCastException@ 6a8a5b3f
	at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
	at me.konsolas.aac.dv.a(dv.java:85) ~[?:?]
	at me.konsolas.aac.dv.a(dv.java:69) ~[?:?]
	at me.konsolas.aac.dv.a(dv.java:98) ~[?:?]
	at me.konsolas.aac.a_.a(a_.java:17) ~[?:?]
	at me.konsolas.aac.bb.run(bb.java:7) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

**Server version**:  1.8.8

**AAC version**:  3.0.3

**ProtocolLib version**: 4.2.0

**Comment by konsolas** [comment]
This issue was closed because the code has changed so much, it is no longer likely to be valid. The stack trace no longer points to useful information.
