### ISSUE TITLE
PlayerMoveEvent  error

### ISSUE THREAD

**Issue by arturek1666** [konsolas/AAC-Issues#423]
Paperspigot 1.11.2

Error: 
[13:33:31] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AAC v3.0.3
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1045]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:617) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.2.jar:git-Paper-1045]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1045]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance between world and spawn
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.Location.distance(Location.java:439) ~[patched_1.11.2.jar:git-Paper-1045]
	at me.konsolas.aac.dw.a(dw.java:113) ~[?:?]
	at me.konsolas.aac.dw.a(dw.java:33) ~[?:?]
	at me.konsolas.aac.y.a(y.java:108) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor608.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1045]
	... 16 more

**Comment by CeIebrimbor** [comment]
Please use the [issue template](https://github.com/konsolas/AAC-Issues/blob/master/ISSUE_TEMPLATE.md)

**Comment by Janmm14** [comment]
Harmless error btw

**Comment by Fluxty** [comment]
Same thing, just bothersome spamming console: http://pastebin.com/yjwKvmcd

TacoSpigot 1.8.8 & appropriate protocollib

**Comment by Janmm14** [comment]
@Fluxty please create another issue for that. Your error is completely different.

**Comment by Fluxty** [comment]
My bad Janmm14, I guess I was being lazy

**Comment by CeIebrimbor** [comment]
Closing after a week waiting for more info
