### ISSUE TITLE
Bug new Version

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#445]
AAC version 3.0.4
Server ver 1.10
Via version 1.0.4
ProtocolLib 4.0.2
`[12:00:58] [Server thread/INFO]: [AAC] Enabling AAC v3.0.4
[12:00:59] [Craft Scheduler Thread - 48/WARN]: Exception in thread "Craft Scheduler Thread - 48" 
[12:00:59] [Craft Scheduler Thread - 48/WARN]: org.apache.commons.lang.UnhandledException: Plugin AAC v3.0.4 generated an exception while executing task 8100
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at me.konsolas.aac.y.run(y.java:3)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[12:01:00] [Craft Scheduler Thread - 50/WARN]: Exception in thread "Craft Scheduler Thread - 50" 
[12:01:00] [Craft Scheduler Thread - 50/WARN]: org.apache.commons.lang.UnhandledException: Plugin AAC v3.0.4 generated an exception while executing task 8100
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at me.konsolas.aac.y.run(y.java:3)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[12:01:01] [Craft Scheduler Thread - 51/WARN]: Exception in thread "Craft Scheduler Thread - 51" 
[12:01:01] [Craft Scheduler Thread - 51/WARN]: org.apache.commons.lang.UnhandledException: Plugin AAC v3.0.4 generated an exception while executing task 8100
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at me.konsolas.aac.y.run(y.java:3)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[12:01:01] [Server thread/INFO]: ProDash issued server command: /aacadmin
[12:01:01] [Server thread/WARN]: [AAC] Task #8101 for AAC v3.0.4 generated an exception
java.lang.NullPointerException
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at me.konsolas.aac.api.a.isEnabled(a.java:3) ~[?:?]
	at me.konsolas.aac.dQ.a(dQ.java:24) ~[?:?]
	at me.konsolas.aac.dQ.a(dQ.java:29) ~[?:?]
	at me.konsolas.aac.b1.a(b1.java:58) ~[?:?]
	at me.konsolas.aac.bC.run(bC.java:1) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[acmc1.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [acmc1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [acmc1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [acmc1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [acmc1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [acmc1.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
[12:01:01] [Thread-32/INFO]: §6[---] §r> §6AAC is up to date!`

**Comment by Photon-GitHub** [comment]
ProtocolLib 4.0.2 is completely outdated. Use 4.2.0.
