### ISSUE TITLE
Various exceptions at startup

### ISSUE THREAD

**Issue by sebastianbinder** [konsolas/AAC-Issues#471]
### Issue description
On startup, loading AAC sometimes results in an error and blocks people connecting to the server. 

```
[04:02:54 INFO]: [AAC] A new version of AAC is available!
[04:02:54 INFO]: [AAC] Beginning Enable...
[04:02:54 INFO]: [AAC] Checking config file...
[04:02:54 INFO]: [AAC] (CheckManager) Enabling check chat.Spam
[04:02:54 WARN]: java.lang.reflect.InvocationTargetException
[04:02:54 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:02:54 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[04:02:54 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:02:54 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[04:02:54 WARN]:        at me.konsolas.aac.y.a(y.java:20)
[04:02:54 WARN]:        at me.konsolas.aac.x.run(x.java:7)
[04:02:54 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[04:02:54 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[04:02:54 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820)
[04:02:54 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[04:02:54 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
[04:02:54 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
[04:02:54 WARN]:        at java.lang.Thread.run(Thread.java:745)
[04:02:54 WARN]: Caused by: java.lang.NullPointerException
[04:02:54 WARN]:        at me.konsolas.aac.a1.<init>(a1.java:60)
[04:02:54 WARN]:        at me.konsolas.aac.a2.<init>(a2.java:61)
[04:02:54 WARN]:        ... 13 more
[04:02:54 WARN]: [AAC] Task #19 for AAC v3.0.5 generated an exception
java.lang.NullPointerException
        at me.konsolas.aac.y.a(y.java:78) ~[?:?]
        at me.konsolas.aac.x.run(x.java:7) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1060]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.jar:git-Paper-1060]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.11.2.jar:git-Paper-1060]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1060]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1060]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1060]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[08:38:29 INFO]: UUID of player <CENSORED> is <CENSORED>
[08:38:29 INFO]: Disconnecting GameProfile(id=<CENSORED>,name=<CENSORED>) (/<CENSORED>:37558): Server still starting up
[08:38:29 INFO]: GameProfile(id=<CENSORED>,name=<CENSORED>) (/<CENSORED>:37558) lost connection: Server still starting up
```

### Core information
**Server version**: `This server is running Paper version git-Paper-1060 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`

**AAC version**: `AAC version 3.0.5`

**ProtocolLib version**: `ProtocolLib version 4.2.1-SNAPSHOT-b347`

**Plugin list**:
```
AAC,
BedwarsNetwork-Bedwars,
BedwarsNetwork-Core,
BedwarsNetwork-Nick,
BedwarsRel,
LuckyBlocks,
Multiverse-Core,
PowerfulPerms,
ProtocolLib,
ProtocolSupport
```
### Special environment information

**ViaVersion version**: `none`

**ProtocolSupport version**: `ProtocolSupport version 4.25.dev`

**ViaBackwards version**: `none`

**BungeeCord plugins**: `will be provided on request`

**Comment by UnderdarkTerms** [comment]
`[16:35:45] [Server thread/INFO]: [AAC] Checking config file...
[16:35:45] [Server thread/INFO]: [AAC] (CheckManager) Check chat.Spam is disabled
[16:35:45] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Hitbox
[16:35:46] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[16:35:46] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:35:46] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[16:35:46] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:35:46] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[16:35:46] [Server thread/WARN]: 	at me.konsolas.aac.y.a(y.java:20)
[16:35:46] [Server thread/WARN]: 	at me.konsolas.aac.x.run(x.java:7)
[16:35:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[16:35:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[16:35:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[16:35:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:35:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:35:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:35:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:35:46] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[16:35:46] [Server thread/WARN]: 	at me.konsolas.aac.a1.<init>(a1.java:60)
[16:35:46] [Server thread/WARN]: 	at me.konsolas.aac.a8.<init>(a8.java:11)
[16:35:46] [Server thread/WARN]: 	... 13 more
[16:35:46] [Server thread/WARN]: [AAC] Task #16 for AAC v3.0.5 generated an exception
java.lang.NullPointerException
	at me.konsolas.aac.y.a(y.java:78) ~[?:?]
	at me.konsolas.aac.x.run(x.java:7) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[16:38:03] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[16:38:03] [Server thread/INFO]: Checking version, please wait...
[16:38:04] [Thread-23/INFO]: You are 603 version(s) behind
[16:38:11] [Server thread/INFO]: AAC version 3.0.5
[16:38:11] [Server thread/INFO]: AAC prevents and kicks suspected hackers from your server.
[16:38:11] [Server thread/INFO]: Author: konsolas
[16:38:14] [Server thread/INFO]: ProtocolLib version 4.2.0
[16:38:14] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[16:38:14] [Server thread/INFO]: Authors: dmulloy2 and comphenix`

Having the save issue. Log provided

**Comment by konsolas** [comment]
Appears to be file corruption. Redownloading will likely fix the issue.

**Comment by sebastianbinder** [comment]
Error is still randomly showing up.
```
[23:49:44 INFO]: [AAC] Beginning Enable...
[23:49:44 INFO]: [AAC] Checking config file...
[23:49:44 INFO]: [AAC] (CheckManager) Enabling check chat.Spam
[23:49:44 WARN]: java.lang.reflect.InvocationTargetException
[23:49:44 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:49:44 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[23:49:44 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:49:44 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[23:49:44 WARN]:        at me.konsolas.aac.bM.a(bM.java:12)
[23:49:44 WARN]:        at me.konsolas.aac.dN.run(dN.java:4)
[23:49:44 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[23:49:44 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[23:49:44 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820)
[23:49:44 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[23:49:44 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
[23:49:44 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
[23:49:44 WARN]:        at java.lang.Thread.run(Thread.java:745)
[23:49:44 WARN]: Caused by: java.lang.NullPointerException
[23:49:44 WARN]:        at me.konsolas.aac.cI.<init>(cI.java:38)
[23:49:44 WARN]:        at me.konsolas.aac.cP.<init>(cP.java:76)
[23:49:44 WARN]:        ... 13 more
[23:49:44 WARN]: [AAC] Task #15 for AAC v3.0.5 generated an exception
java.lang.NullPointerException
        at me.konsolas.aac.bM.a(bM.java:1) ~[?:?]
        at me.konsolas.aac.dN.run(dN.java:4) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1060]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.jar:git-Paper-1060]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.11.2.jar:git-Paper-1060]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1060]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1060]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1060]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by sebastianbinder** [comment]
@konsolas @Photon-GitHub please reopen this issue.

**Comment by sebastianbinder** [comment]
anyone able to help me?

**Comment by UnderdarkTerms** [comment]
Having the same issue and it's affecting our server's performance, beacuse realms need to restart when they fail to load and this results in big CPU overhead

**Comment by sebastianbinder** [comment]
```
[20:29:53 INFO]: [AAC] Beginning Enable...
[20:29:53 WARN]: [AAC] Task #14 for AAC v3.0.5 generated an exception
java.lang.IllegalArgumentException: Listener can not be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.11.2.jar:git-Paper-1063]
        at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:226) ~[patched_1.11.2.jar:git-Paper-1063]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:548) ~[patched_1.11.2.jar:git-Paper-1063]
        at me.konsolas.aac.dN.run(dN.java:12) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1063]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1063]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
Still happening here...

**Comment by sebastianbinder** [comment]
Just saw this one again:
```
[19:36:01 INFO]: [AAC] Beginning Enable...
[19:36:01 INFO]: [AAC] Checking config file...
[19:36:01 INFO]: [AAC] (CheckManager) Enabling check chat.Spam
[19:36:01 WARN]: java.lang.reflect.InvocationTargetException
[19:36:01 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:36:01 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:36:01 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:36:01 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:36:01 WARN]:        at me.konsolas.aac.bM.a(bM.java:12)
[19:36:01 WARN]:        at me.konsolas.aac.dN.run(dN.java:4)
[19:36:01 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[19:36:01 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[19:36:01 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820)
[19:36:01 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[19:36:01 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
[19:36:01 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
[19:36:01 WARN]:        at java.lang.Thread.run(Thread.java:745)
[19:36:01 WARN]: Caused by: java.lang.NullPointerException
[19:36:01 WARN]:        at me.konsolas.aac.cI.<init>(cI.java:38)
[19:36:01 WARN]:        at me.konsolas.aac.cP.<init>(cP.java:76)
[19:36:01 WARN]:        ... 13 more
[19:36:01 WARN]: [AAC] Task #15 for AAC v3.0.5 generated an exception
java.lang.NullPointerException
        at me.konsolas.aac.bM.a(bM.java:1) ~[?:?]
        at me.konsolas.aac.dN.run(dN.java:4) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1063]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1063]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by Janmm14** [comment]
We're getting spammed with such exceptions, but the problem is that konsolas is moving house, so updates are even more rare than usual.

**Comment by sebastianbinder** [comment]
Okay. Thanks for your feedback @Janmm14
Just wanted to make sure that this issue is being acknowledged and not being treated as a simple "corrupted file" like @konsolas said before.

**Comment by MedicOP** [comment]
Are you still experiencing these errors in 3.1.x?

**Comment by konsolas** [comment]
This issue was closed because the code has changed so much, it is no longer likely to be valid. The stack trace no longer points to useful information.
