### ISSUE TITLE
NullPointerException Task every second 3.0.5b1 - cn.a:14

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#498]
```java
[18-03-2017 16:38:23] [Server thread/WARN]: [AAC] Task #50 for AAC v3.0.5 generated an exception
java.lang.NullPointerException
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at me.konsolas.aac.cn.a(cn.java:14) ~[?:?]
	at me.konsolas.aac.cT.run(cT.java:4) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

### Core information
**Server version**: 1.8.8

**AAC version**: 3.0.5-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: Custom

**ViaVersion version**: 1.0.3

**Comment by konsolas** [comment]
Edge case fixed.
