### ISSUE TITLE
AAC error

### ISSUE THREAD

**Issue by tade159SK** [konsolas/AAC-Issues#523]
### Core information
**Server version**: Spigot 1.8.8 last version

**AAC version**: 3.1.1

**ProtocolLib version**: latest for spigot 1.8.8

**Plugin list**: Custom Plugins

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: latest version

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: Custom Plugins

Error: 
`AAC v3.1.1 generated an exception
java.lang.NullPointerException
    at me.konsolas.aac.be.a(be.java:8) ~[?:?]
    at me.konsolas.aac.a5.run(a5.java:3) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-21fe707-e1ebe52]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]`

**Comment by Photon-GitHub** [comment]
Wrong version of Protocollib.

**Comment by Photon-GitHub** [comment]
(Use 4.2.0)

**Comment by tade159SK** [comment]
We are using 4.2.0

**Comment by Janmm14** [comment]
http://ci.dmulloy2.net/job/ProtocolLib/ says:
> **Recommended Builds**
> * Latest: 4.2.1 for MC 1.11.x
> * 341: 4.2.0 for MC 1.8 thru 1.10.x
> * v3.7.0 for MC 1.0 thru 1.7.10
