### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#525]
Crash Report: https://hastebin.com/zanimabolu.php

Core information

Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.2
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/c17cf3dda13667a2bd5e5bb29c1b8271

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by MedicOP** [comment]
Getting the same problem

```java
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 4/2/17 12:47 AM
Description: Exception ticking world entities

java.util.NoSuchElementException
	at org.bukkit.craftbukkit.v1_8_R3.util.UnsafeList$Itr.next(UnsafeList.java:248)
	at org.spigotmc.ActivationRange.activateChunkEntities(ActivationRange.java:148)
	at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:131)
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1400)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MedicOP** [comment]
Similar crash with a different stack trace, but once again caused by NoSuchElementException while iterating through entity slices.

```java
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 4/3/17 8:28 PM
Description: Ticking block entity

java.util.NoSuchElementException
	at org.bukkit.craftbukkit.v1_8_R3.util.UnsafeList$Itr.next(UnsafeList.java:248)
	at net.minecraft.server.v1_8_R3.Chunk.a(Chunk.java:930)
	at net.minecraft.server.v1_8_R3.World.a(World.java:2569)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:543)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:373)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:193)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:177)
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
	at java.lang.Thread.run(Thread.java:745)
```

I strongly suspect AAC is causing these crashes, as they only started happening recently while I have not changed anything about my setup besides installing AAC.

**Comment by MedicOP** [comment]
Any updates on this? I'm getting crashes now on all of my servers, even though they never crashed before installing AAC.

**Comment by cssoz111** [comment]
Yes same, Can you fix that? MedicOP and SnakeDaoust1232

**Comment by konsolas** [comment]
#551 has more info
