### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Summerfeeling** [konsolas/AAC-Issues#554]
### Issue description

Appearing NullPointerException:
`[18:11:38] [Server thread/WARN]: [AAC] Task #31 for AAC v3.1.3 generated an exception
java.lang.NullPointerException
	at me.konsolas.aac.cW.a(cW.java:61) ~[?:?]
	at me.konsolas.aac.Q.run(Q.java:1) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-afc6f4a-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-afc6f4a-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-afc6f4a-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:372) [spigot.jar:git-Spigot-afc6f4a-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-afc6f4a-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-afc6f4a-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121].`

### Core information
**Server version**: Spigot 1.8.8
**AAC version**: 3.1.3
**ProtocolLib version**: 4.2.0
**Plugin list**: AAC, AACAdditionPro, ProtocolLib + own plugins

### Special environment information
**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: own, which shouldn't affect AAC in anyway

**Comment by konsolas** [comment]
Caused when a player lands before the scheduler tick.

**Comment by konsolas** [comment]
(NoFall check)
