### ISSUE TITLE
AAC Firework Activation Console Errors (Users who bypass AAC don't get console error)

### ISSUE THREAD

**Issue by MatheweB** [konsolas/AAC-Issues#589]
Whenever a player who isn't bypassing AAC activates a firework, the console gets spammed with an error message. I was under the assumption that this message only happened to people flying with an elytra and activating a firework, but this error happens every time a player activates a firework rocket (In this case a duration 3 rocket)

There are no false positives, but the console gets spammed with this specific message EVERY instance that a player activates a firework rocket.

* AAC logs / Full console error (User Deathsipher Activated a firework):
```
17.04 00:34:34 [Server] INFO hi
17.04 00:34:37 [Server] WARN java.lang.IllegalArgumentException: java.lang.ClassCastException@5d543b23
17.04 00:34:37 [Server] WARN at sun.reflect.GeneratedMethodAccessor288.invoke(Unknown Source)
17.04 00:34:37 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17.04 00:34:37 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
17.04 00:34:37 [Server] WARN at me.konsolas.aac.cv.c(cv.java:148)
17.04 00:34:37 [Server] WARN at me.konsolas.aac.cj.a(cj.java:106)
17.04 00:34:37 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17.04 00:34:37 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17.04 00:34:37 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17.04 00:34:37 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
17.04 00:34:37 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
17.04 00:34:37 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
17.04 00:34:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
17.04 00:34:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
17.04 00:34:37 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:912)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
17.04 00:34:37 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17.04 00:34:37 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
17.04 00:34:37 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
17.04 00:34:37 [Server] WARN at java.lang.Thread.run(Thread.java:745)
17.04 00:34:51 [Server] WARN java.lang.IllegalArgumentException: java.lang.ClassCastException@6e0d97ab
17.04 00:34:51 [Server] WARN at sun.reflect.GeneratedMethodAccessor288.invoke(Unknown Source)
17.04 00:34:51 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17.04 00:34:51 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
17.04 00:34:51 [Server] WARN at me.konsolas.aac.cv.c(cv.java:148)
17.04 00:34:51 [Server] WARN at me.konsolas.aac.cj.a(cj.java:106)
17.04 00:34:51 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17.04 00:34:51 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17.04 00:34:51 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17.04 00:34:51 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
17.04 00:34:51 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
17.04 00:34:51 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
17.04 00:34:51 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
17.04 00:34:51 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
17.04 00:34:51 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:912)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
17.04 00:34:51 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17.04 00:34:51 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
17.04 00:34:51 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
17.04 00:34:51 [Server] WARN at java.lang.Thread.run(Thread.java:745)
```
### Core information
**Server version**:  Spigot 1.11.2

**AAC version**: 3.1.5 (latest b3)

**ProtocolLib version**: Latest

**Plugin list**: AAC, No citizens plugin!

Date and time when the issue occurred: April 16th, 6:43 PM EST

**Comment by MatheweB** [comment]
I activated a firework two times in a row here, and it created the console error twice!

**Comment by MatheweB** [comment]
I found out the reason why this was happening!

I had OpGuard installed as a plugin on my server, and the player and command injections were causing errors that reached much farther than just AAC. 

I uninstalled OpGuard, and everything is working perfectly now!!
