### ISSUE TITLE
NPE every second

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#591]
Using latest AAC 3.1.5. I also have Citizens in this particular server, unsure if related.

```java
[16-04-2017 20:51:59] [Server thread/WARN]: [AAC] Task #42 for AAC v3.1.5 generated an exception
java.lang.NullPointerException
	at me.konsolas.aac.cQ.a(cQ.java:2) ~[?:?]
	at me.konsolas.aac.bp.lambda$new$0(bp.java:68) ~[?:?]
	at me.konsolas.aac.bp$$Lambda$28/2003389864.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by Pluginsel** [comment]
You have using AAC 3.1.5-b3 version? Citizens error is fixed on version -b3.

**Comment by MedicOP** [comment]
That was ClassCastException, not NullPointerException.

**Comment by MedicOP** [comment]
Another NPE happening for PlayerMoveEvent, no Citizens installed

```java
[13:30:53 ERROR]: Could not pass event PlayerMoveEvent to AAC v3.1.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at me.konsolas.aac.cV.a(cV.java:325) ~[?:?]
        at me.konsolas.aac.bp.a(bp.java:97) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        ... 15 more
```

**Comment by SnakeDaoust1232** [comment]
@konsolas @MedicOP Im getting these errors. Same thing, 3.1.5b3.

One: https://gyazo.com/0a634ffb36c5b69994c1f909a44759d4
Two: https://gyazo.com/2576b718b56d956e45bfffd29ffb017d

**Comment by MedicOP** [comment]
May I know why this is still marked as "insufficient info" ?
