### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by tomasmessing** [konsolas/AAC-Issues#674]
**world** is world for players (survival)
**novyspawn** is world for spawn city (spawn only)

```
[15:15:06 INFO]: FarexCZE issued server command: /spawn
[15:15:09 WARN]: [AAC] Task #265 for AAC v3.1.6 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and novyspawn
at org.bukkit.Location.distanceSquared(Location.java:456) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.Location.distance(Location.java:439) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at me.konsolas.aac.aP.a(aP.java:82) ~[?:?]
at me.konsolas.aac.aP.a(aP.java:70) ~[?:?]
at me.konsolas.aac.bK.a(bK.java:58) ~[?:?]
at me.konsolas.aac.a0.lambda$new$4(a0.java:28) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

another exception
```
[15:17:22 ERROR]: Could not pass event BlockBreakEvent to AAC v3.1.6
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:850) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
[15:17:22 INFO]: Sl1mer_ issued server command: /money
[15:17:23 ERROR]: Could not pass event BlockBreakEvent to AAC v3.1.6
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:850) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
[15:17:23 ERROR]: Could not pass event BlockBreakEvent to AAC v3.1.6
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:850) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
[15:17:23 ERROR]: Could not pass event BlockBreakEvent to AAC v3.1.6
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:850) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
[15:17:23 WARN]: [AAC] Task #1379327 for AAC v3.1.6 generated an exception
java.lang.NullPointerException
at me.konsolas.aac.cw.b(cw.java:8) ~[?:?]
at me.konsolas.aac.cy.b(cy.java:304) ~[?:?]
at me.konsolas.aac.b4.lambda$onPacketSending$0(b4.java:25) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[15:17:23 INFO]: SpringBonie173 issued server command: /ah sell 100
[15:17:23 INFO]: NPCdeal issued server command: /warp PVNST
[15:17:23 ERROR]: Could not pass event BlockBreakEvent to AAC v3.1.6
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:850) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
[15:17:24 ERROR]: Could not pass event BlockBreakEvent to AAC v3.1.6
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:850) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-54ec0b8-473febc]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
```

**Comment by CeIebrimbor** [comment]
Use ProtocolLib 4.2.1 (not latest) for 1.11 servers. Request reopen if you find that the same issue occurs after the downgrade/upgrade.

Also...use the reporting template when you report so you don't get an Insufficient Info tag.

**Comment by tomasmessing** [comment]
I'm not using latest version. I tested several versions of ProtocolLib. I think that I'll downgrade because speed and fly check is worse.

**Comment by CeIebrimbor** [comment]
Please open an issue using the reporting template so we don't need to guess :p

**Comment by Janmm14** [comment]
BTW: Second exception is truncated by java itself, scroll up your logs and find the exception with something after"caused by"
