### ISSUE TITLE
Task issue with tp between worlds.

### ISSUE THREAD

**Issue by JamieSinn** [konsolas/AAC-Issues#678]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Task throws an illegalargumentexception.

```2017-05-26 21:31:14 [WARN] [AAC] Task #99 for AAC v3.1.6 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between rising and legacy
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-6e3cec8]
	at me.konsolas.aac.bK.a(bK.java:172) ~[?:?]
	at me.konsolas.aac.a0.lambda$new$4(a0.java:28) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

This also came up - 
```
2017-05-26 21:32:11 [WARN] [ProtocolLib] [PacketFilterManager] [AAC] Unsupported server packet ID in current Minecraft version: REL_ENTITY_MOVE_LOOK[PLAY, SERVER, 39, classNames: [PacketPlayOutRelEntityMoveLook] (unregistered)]
2017-05-26 21:32:11 [WARN] [ProtocolLib] [PacketFilterManager] [AAC] Unsupported server packet ID in current Minecraft version: REL_ENTITY_MOVE_LOOK[PLAY, SERVER, 39, classNames: [PacketPlayOutRelEntityMoveLook] (unregistered)]
```

### Core information
**Server version**:  1.11.2

**AAC version**: AAC 3.1.6|B5, AACAdditionPro 1.9.3, ConditionalCommands 1.3.1

**ProtocolLib**: 367

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: n/a

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: none

**Comment by andrewkm** [comment]
Can confirm this was an issue.
Rolling back ProtocolLib however to 354 seems to fix it. I believe versions past 354+ have changed quite a lot due to 1.12?(guessing here) - Perhaps this was the problem.

**Comment by CeIebrimbor** [comment]
Build 354 of ProtocolLib until further notice. 355+ are pre-builds for 1.12
