### ISSUE TITLE
keep spam error

### ISSUE THREAD

**Issue by cwken10** [konsolas/AAC-Issues#696]
### Issue description

keep spamming this error

```
java.lang.IllegalArgumentException: Cannot measure distance between world_the_end and spawn
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.Location.distance(Location.java:439) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	at me.konsolas.aac.aP.a(aP.java:82) ~[?:?]
	at me.konsolas.aac.aP.a(aP.java:70) ~[?:?]
	at me.konsolas.aac.bK.a(bK.java:58) ~[?:?]
	at me.konsolas.aac.a0.lambda$new$4(a0.java:28) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

### Core information
**Server version**: latest

**AAC version**: latest

**ProtocolLib version**: insert

**Plugin list**: cant tell (around 55)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: latest

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by cwken10** [comment]
monitor more 1st
