### ISSUE TITLE
ERROR? - Killaura not work

### ISSUE THREAD

**Issue by crimilo** [konsolas/AAC-Issues#729]
[07:07:01] [Server thread/INFO]: [AAC] Enabling AAC v3.1.7
[07:07:01] [Thread-159/WARN]: [AAC] (Punisher) WARN: Failed to get thresholds for check MovementManager
[07:07:01] [Thread-159/INFO]: [AAC] A new version of AAC is available!
[07:07:02] [Server thread/INFO]: [AAC] Beginning Enable...
[07:07:02] [Server thread/INFO]: [AAC] Checking config file...
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check chat.Spam
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Hitbox
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Fastbow
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.FightSpeed
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Check combat.Knockback is disabled
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Regen
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.FastUse
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Killaura
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Heuristics
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.BadPackets
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.Speed
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.Phase
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.Fly
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.NoFall
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Check movement.Jesus is disabled
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.Derp
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Criticals
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.FastBreak
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.FastPlace
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.Nuker
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.NoSwing
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.Interact
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.Velocity
[07:07:02] [Server thread/INFO]: [AAC] (CheckManager) Enabling check MovementManager
[07:07:02] [Server thread/INFO]: [AAC] Starting API...
[07:07:02] [Server thread/INFO]: [AAC] AAC has been enabled.
[07:09:20] [Server thread/WARN]: [AAC] Task #10073 for AAC v3.1.7 generated an exception
java.lang.NullPointerException
	at me.konsolas.aac.a2.a(a2.java:72) ~[?:?]
	at me.konsolas.aac.a2.a(a2.java:61) ~[?:?]
	at me.konsolas.aac.aN.a(aN.java:39) ~[?:?]
	at me.konsolas.aac.aC.lambda$new$0(aC.java:41) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

Killaura  not work!
config: https://pastebin.com/13cv40hH
versions/plugins: http://imgur.com/a/L01BR
video: https://youtu.be/wR61Ooid2c0

**Comment by CeIebrimbor** [comment]
Please set `duration` back to 20. You basically turned off the check with your 2 setting. Also, `max_reach` is not a safe value to just drop. Rely on Hitbox to catch reach clients under 4.5 blocks.

**Comment by konsolas** [comment]
@crimilo the problem here is that you have broken the killaura check with your configuration, it is not a problem with the check itself.
