### ISSUE TITLE
Exception on Teleport | 3.1.7

### ISSUE THREAD

**Issue by Phreag** [konsolas/AAC-Issues#740]
It throws this exception:

### Core information
**Server version**: 1.11.2 latest Paper build before 1.12

**AAC version**: 3.1.7

**ProtocolLib version**: latest

Error:
[08:44:13 ERROR]: Could not pass event PlayerTeleportEvent to AAC v3.1.7
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[spigot.jar:git-Paper-1
084]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-
Paper-1084]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:g
it-Paper-1084]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [spigot.jar
:git-Paper-1084]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [spigot.jar
:git-Paper-1084]
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.teleport(CraftPlayer.java:571) [spigot
.jar:git-Paper-1084]
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.teleport(CraftEntity.java:265) [spigot
.jar:git-Paper-1084]
        at Phreag.listeners.TeleportsListener$1.run(TeleportsListener.java:45) [JenoTeleportBungeeSu
ite.jar:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) [spigot.jar:gi
t-Paper-1084]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spi
got.jar:git-Paper-1084]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapp
er.java:22) [spigot.jar:git-Paper-1084]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.IllegalStateException: Must be called from the main thread
        at me.konsolas.aac.V.a(V.java:9) ~[?:?]
        at me.konsolas.aac.V.a(V.java:23) ~[?:?]
        at me.konsolas.aac.V.a(V.java:87) ~[?:?]
        at me.konsolas.aac.aN.a(aN.java:107) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor764.execute(Un
known Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[spigot.jar:git-Paper-1
084]
        ... 13 more

**Comment by Phreag** [comment]
Sorry, have seen that there is alerady an update adressing this issue.
