### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by Fages1** [konsolas/AAC-Issues#762]
I'm having an error while booting the server.
Because of this error, people can not log in to the server because of: 
Server still starting up
```
[22:35:38 WARN]: Exception in thread "Thread-36"
[22:35:38 WARN]: java.lang.LinkageError: loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "com/comphenix/protocol/events/ListenerPriority"
[22:35:38 WARN]:        at java.lang.ClassLoader.defineClass1(Native Method)
[22:35:38 WARN]:        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[22:35:38 WARN]:        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[22:35:38 WARN]:        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[22:35:38 WARN]:        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[22:35:38 WARN]:        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[22:35:38 WARN]:        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[22:35:38 WARN]:        at java.security.AccessController.doPrivileged(Native Method)
[22:35:38 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[22:35:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[22:35:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193)
[22:35:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98)
[22:35:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[22:35:38 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[22:35:38 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:35:38 WARN]:        at java.lang.Class.forName0(Native Method)
[22:35:38 WARN]:        at java.lang.Class.forName(Class.java:264)
[22:35:38 WARN]:        at me.konsolas.iaac.kc.y(Unknown Source)
[22:35:38 WARN]:        at me.konsolas.iaac.kc.S(Unknown Source)
[22:35:38 WARN]:        at me.konsolas.iaac.kc.p(Unknown Source)
[22:35:38 WARN]:        at me.konsolas.iaac.kc.S(Unknown Source)
[22:35:38 WARN]:        at me.konsolas.iaac.kc.e(Unknown Source)
[22:35:38 WARN]:        at me.konsolas.iaac.i.<init>(i.java:132)
[22:35:38 WARN]:        at me.konsolas.iaac.f.run(f.java:13)
```
server version: paper 1.8
ProtocolLib: latest

**Comment by SnakeDaoust1232** [comment]
Cracked version?

**Comment by Janmm14** [comment]
@Fages1 Please provide output of /aac in a private message on spigotmc to me: https://www.spigotmc.org/conversations/add?to=Janmm14

**Comment by Janmm14** [comment]
seems valid for now

did you tried updating aac to 3.2.0? another user with a similar issue says that it fixed things for him

**Comment by konsolas** [comment]
Closing due to insufficient information.
