### ISSUE TITLE
Not detect killaura and antikb in 1.8?

### ISSUE THREAD

**Issue by pepiillo99** [konsolas/AAC-Issues#805]
Hello, I have updated AAC after many versions and it does not detect almost anything ... I use spigot 1.8 and it even gives errors ...

`[15:38:05 ERROR]: [AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC
java.util.NoSuchElementException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721) ~[?:1.8.0_131]
        at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747) ~[?:1.8.0_131]
        at me.konsolas.aac.cz.a(cz.java:3) ~[AAC.jar:3.2.1]
        at me.konsolas.aac.aE.remove(aE.java:133) ~[AAC.jar:3.2.1]
        at me.konsolas.aac.c0.onPacketReceiving(c0.java:14) ~[AAC.jar:3.2.1]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.3.1-SNAPSHOT-b376]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.3.1-SNAPSHOT-b376]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.3.1-SNAPSHOT-b376]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.3.1-SNAPSHOT-b376]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.3.1-SNAPSHOT-b376]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.3.1-SNAPSHOT-b376]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib.jar:4.3.1-SNAPSHOT-b376]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.1-SNAPSHOT-b376]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [uhcmeetup-solo-1-1.8.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[15:38:05 ERROR]: Parameters:
  net.minecraft.server.v1_8_R3.PacketPlayInUseEntity@2dce2ea4[
    a=3598
    action=ATTACK
    c=<null>
  ]`

**Comment by CeIebrimbor** [comment]
It looks like ProtocolLib is going through some issues with 4.3.1 development. Revert to the stable 4.3.0. Or 4.2.0 since it was built on 1.8.8.

4.3.0 - http://ci.dmulloy2.net/job/ProtocolLib/373/
4.2.0 - http://ci.dmulloy2.net/job/ProtocolLib/341/

**Comment by pepiillo99** [comment]
1.8.8
