### ISSUE TITLE
Feature Request: KitBattle Advanced Compatibility

### ISSUE THREAD

**Issue by MatheweB** [konsolas/AAC-Issues#826]
Hello! I have extensive errors with KitBattle every time I reload my server. The logs are below. What happens is that any time a player attempts to click a join kit battle sign, they get kicked for sending unusual packets, and the error below shows up. I need to then reset the spawn of the arena in kitbattle for this glitch not to occur.

```
14.07 22:38:58 [Server] WARN [AAC] Task #1734 for AAC v3.2.1 generated an exception
14.07 22:38:58 [Server] INFO java.lang.IllegalArgumentException: Cannot use null location with null world!
14.07 22:38:58 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 22:38:58 [Server] INFO at org.bukkit.event.player.PlayerMoveEvent.validateLocation(PlayerMoveEvent.java:92) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 22:38:58 [Server] INFO at org.bukkit.event.player.PlayerMoveEvent.setTo(PlayerMoveEvent.java:86) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 22:38:58 [Server] INFO at me.konsolas.aac.D.a(D.java:76) ~[AAC.jar:3.2.1]
14.07 22:38:58 [Server] INFO at me.konsolas.aac.bp.lambda$new$2(bp.java:8) ~[AAC.jar:3.2.1]
14.07 22:38:58 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 22:38:58 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 22:38:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 22:38:58 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 22:38:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 22:38:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 22:38:58 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

If there is any way you could add compatibility for this issue, it would be greatly appreciated!

_Running the Latest 3.2.1-b1 AAC, and The latest KitBattle, with Spigot 1.12_

**Comment by Janmm14** [comment]
Please also include AAC Logs of Players getting kicked.

**Comment by Games4k** [comment]
Then just dont reload it... Its much better to use plugman to reload one plugin, you really dont need to reload whole server

**Comment by konsolas** [comment]
Seems to be a strange, compatibility/reload issue. 

Reloading is generally unsafe when you have a lot of plugins, please restart your server.
