### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by smartmadio** [konsolas/AAC-Issues#860]
### Issue description
```
[07:56:03] [Server thread/ERROR]: [AAC] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for AAC
java.lang.NoSuchMethodError: com.comphenix.protocol.wrappers.EnumWrappers.getGenericConverter(Ljava/lang/Class;)Lcom/comphenix/protocol/reflect/EquivalentConverter;
	at me.konsolas.aac.aJ.i(aJ.java:17) ~[?:?]
	at me.konsolas.aac.aJ.a(aJ.java:29) ~[?:?]
	at me.konsolas.aac.A.onPacketSending(A.java:89) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:176) ~[patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) ~[patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1141) ~[patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.PlayerConnection.internalTeleport(PlayerConnection.java:794) ~[patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.PlayerConnection.teleport(PlayerConnection.java:750) ~[patched_1.12.1.jar:git-Paper-1173]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:633) ~[patched_1.12.1.jar:git-Paper-1173]
	at me.konsolas.aac.ap.lambda$new$2(ap.java:6) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.1.jar:git-Paper-1173]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1173]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
```[07:38:58] [Server thread/ERROR]: [AAC] Unhandled exception occured in onPacketSending(PacketEvent) for AAC
java.lang.NoSuchMethodError: com.comphenix.protocol.wrappers.EnumWrappers.getGenericConverter(Ljava/lang/Class;)Lcom/comphenix/protocol/reflect/EquivalentConverter;
	at me.konsolas.aac.aJ.i(aJ.java:17) ~[AAC.jar:3.2.2]
	at me.konsolas.aac.aJ.a(aJ.java:29) ~[AAC.jar:3.2.2]
	at me.konsolas.aac.A.onPacketSending(A.java:89) ~[AAC.jar:3.2.2]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.4.0-SNAPSHOT-b381]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:176) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1141) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.PlayerConnection.internalTeleport(PlayerConnection.java:794) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.PlayerConnection.teleport(PlayerConnection.java:750) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:713) [patched_1.12.1.jar:git-Paper-1173]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:636) [patched_1.12.1.jar:git-Paper-1173]
	at com.earth2me.essentials.Teleport.now(Teleport.java:139) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Teleport.now(Teleport.java:104) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$NewPlayerTeleport.run(EssentialsSpawnPlayerListener.java:153) [EssentialsXSpawn-2.0.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.1.jar:git-Paper-1173]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1173]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1173]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[07:38:58] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayOutPosition@70688ef9[
    a=-1.5
    b=86.0
    c=0.5
    d=-88.54089
    e=0.29978025
    f=[]
    g=3
  ]
```
### Core information
**Server version**: 1.12.1

**AAC version**: 3.2.2-b1

**ProtocolLib version**: 4.3.0 #381

**Plugin list**: insert

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: 4.26

**ViaBackwards version**: N/A

**BungeeCord plugins**:  N/A

### Configuration
default config

**Comment by Janmm14** [comment]
ProtocolLib b381 is not 4.3.0, but 4.4.0-SNAPSHOT

**Comment by Janmm14** [comment]
ProtocolLib b381 is not 4.3.0, but 4.4.0-SNAPSHOT

Duplicate of #855
