### ISSUE TITLE
Cannot measure distance to a null world

### ISSUE THREAD

**Issue by FreakySlimeHD** [konsolas/AAC-Issues#874]
```[15:24:47 WARN]: [AAC] Task #32 for AAC v3.3.0 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance to a null world
        at org.bukkit.Location.distanceSquared(Location.java:458) ~[spigot.jar:git-Spigot-5340a52-e1f296d]
        at me.konsolas.aac.cV.a(cV.java:150) ~[?:?]
        at me.konsolas.aac.br.lambda$new$2(br.java:58) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5340a52-e1f296d]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-5340a52-e1f296d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:736) [spigot.jar:git-Spigot-5340a52-e1f296d]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:391) [spigot.jar:git-Spigot-5340a52-e1f296d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:676) [spigot.jar:git-Spigot-5340a52-e1f296d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-5340a52-e1f296d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by CeIebrimbor** [comment]
Please use the issue report format.

**Comment by konsolas** [comment]
Closing due to insufficient information.
