### ISSUE TITLE
Could not pass event PlayerInteractEvent to AAC v3.3.0

### ISSUE THREAD

**Issue by polarcn** [konsolas/AAC-Issues#875]
[09:48:00 ERROR]: Could not pass event PlayerInteractEvent to AAC v3.3.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[mc.jar:git-Spigot-65e8124-357b573]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-65e8124-357b573]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [mc.jar:git-Spigot-65e8124-357b573]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [mc.jar:git-Spigot-65e8124-357b573]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [mc.jar:git-Spigot-65e8124-357b573]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [mc.jar:git-Spigot-65e8124-357b573]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:945) [mc.jar:git-Spigot-65e8124-357b573]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [mc.jar:git-Spigot-65e8124-357b573]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [mc.jar:git-Spigot-65e8124-357b573]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [mc.jar:git-Spigot-65e8124-357b573]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [mc.jar:git-Spigot-65e8124-357b573]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [mc.jar:git-Spigot-65e8124-357b573]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-65e8124-357b573]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-65e8124-357b573]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-65e8124-357b573]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
        at me.konsolas.aac.b6.d(b6.java:70) ~[?:?]
        at me.konsolas.aac.b_.b(b_.java:47) ~[?:?]
        at me.konsolas.aac.b_.a(b_.java:33) ~[?:?]
        at me.konsolas.aac.b_.a(b_.java:89) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor270.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[mc.jar:git-Spigot-65e8124-357b573]
        ... 17 more
### Core information
**Server version**: 1.12.1

**AAC version**: 3.3.0-b1

**ProtocolLib version**: lateset

**Plugin list**: [09:53:37 INFO]: Plugins (101): RPGDrop, TigerSigns, GrItemTags, ItemExpireDate, NoSellLoreItemToGlobalShop, OnJoinCommand, TwDungeonEX, Itemizer, DisplayItem, EasyCommand, AutoFood, DecoHeads, Multiverse-Core, ProtocolLib, MVdWPlaceholderAPI, RPLPermission, FastAsyncWorldEdit, ImageOnMap, AirBar, Captcha, AntiCropTrample, RandomTp, CustomJoinItems, ProtocolSupport, SimpleSit, SlimefunBugFixer, GroupManager, PlaceholderAPI, VoidWorld, PorteCoulissante, AntiWorldFly, WorldCommandBlock, GuoItemLoreCommand, Multikills, BanItem, Yum, NoteBlockAPI, EpicWorldGenerator, Soulbound, LoginLocation, CoreProtect, WorldEdit, CustomEnderChest, Essentials, CreeperTitleAPI, ClearLag, ArmorStandEditor, Itembound, BukkitInjectedTools, WorldBorder, ParticleAPI, Fly_And_Creative_Timer, AutoSaveWorld, LibsDisguises, disintegrate, DeluxeMenus, CommandCode, xiaohao, CS-CoreLib, GlobalShop, Vault, JumpPads, HolographicDisplays, BlueShop, PlayerPoints, VipSystem, AAC, RandomLocation, BreakableWalls, TitleManager, HolographicScoreboard, CreeperMarriage, MessageAnnouncer, ActionHealth, Citizens, EasyKits, Shopkeepers, EssentialsChat, CrazyCrates, MiaoMenu, NpcShop, QuickShop, WorldGuard, Slimefun, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, BuyName, LiteBans, TreasureChest, Residence, AncientGates, ScriptBlockPlus, TouchscreenHolograms, WhitePay, LockettePro, MythicMobs, CommandNPC, SignShop, RPGPlayerLeveling, DeluxeChat

### Special environment information
**ViaVersion version**: no

**ProtocolSupport version**: yes

**ViaBackwards version**: no

**BungeeCord plugins**: AntifakePlayers colormotd bungeekick

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by CeIebrimbor** [comment]
Closed in favor of #880
