### ISSUE TITLE
PlayerMoveEvent#setTo tried with location with null world

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#882]
### Issue description

Report by 임정훈#6832 (244741665540014080)
```
[20:24:58 WARN]: [AAC] Task #110 for AAC v3.2.2 generated an exception
java.lang.IllegalArgumentException: Cannot use null location with null world!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.event.player.PlayerMoveEvent.validateLocation(PlayerMoveEvent.java:92) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.event.player.PlayerMoveEvent.setTo(PlayerMoveEvent.java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at me.konsolas.aac.aa.a(aa.java:11) ~[?:?]
        at me.konsolas.aac.ap.lambda$new$2(ap.java:93) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
```
### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.2.2

**ProtocolLib version**: 4.3.0

**Comment by konsolas** [comment]
outdated stacktrace :(
