### ISSUE TITLE
AAC v3.3.1+ fails to start on Debian 8.8/Java 1.8.0-b132

### ISSUE THREAD

**Issue by Prunt** [konsolas/AAC-Issues#894]
### Issue description
It seems that the newest versions of AAC (v3.3.1+) don't start on my rented dedicated Debian 8 machine with Java 1.8.0-b132, but work perfectly on my personal Windows 10 machine with Java 1.8.0_144-b01. I copied the exact same setup and it worked in one machine and failed in another. Switching from Paper 1.12.1 to Spigot 1.12 (git-Spigot-596221b-9a1fc1e) didn't help either.

Version 3.3.1 (and 3.3.1-b1) fails to start on server startup:
```
[07:03:04 INFO]: [AAC] Enabling AAC v3.3.1
[07:03:05 ERROR]: Error occurred while enabling AAC v3.3.1 (Is it up to date?)
java.lang.RuntimeException: java.lang.ClassNotFoundException: me/konsolas/iaac/l
        at me.konsolas.iaac.l.b(l.java) ~[?:?]
        at me.konsolas.iaac.l.c(l.java) ~[?:?]
        at me.konsolas.iaac.l.a(l.java) ~[?:?]
        at me.konsolas.aac.AAC.onEnable(AAC.java:29) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.1.jar:git-Paper-1176]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.1.jar:git-Paper-1176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.1.jar:git-Paper-1176]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [patched_1.12.1.jar:git-Paper-1176]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [patched_1.12.1.jar:git-Paper-1176]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.1.jar:git-Paper-1176]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.1.jar:git-Paper-1176]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.1.jar:git-Paper-1176]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.1.jar:git-Paper-1176]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.1.jar:git-Paper-1176]
        at java.lang.Thread.run(Thread.java:744) [?:1.8.0]
[07:03:05 INFO]: [AAC] Disabling AAC v3.3.1
[07:03:05 INFO]: [AAC] Disabling checks...
```
AAC v3.3.0-b1 (and lower) works fine with the same setup, though.

### Core information
**Server version**: Paper version git-Paper-1195 (MC: 1.12.1)
**AAC version**: AAC version 3.3.1
**ProtocolLib version**: ProtocolLib version 4.3.0
**Plugin list**: Plugins (2): AAC, ProtocolLib

### Special environment information
**ViaVersion version**: N/A
**ProtocolSupport version**: N/A
**ViaBackwards version**: N/A
**BungeeCord plugins**: N/A

### Configuration
Doesn't even generate a default config.

**Comment by ItzSomebody** [comment]
Did you try downloading?

**Comment by Prunt** [comment]
Still the same result.

**Comment by ItzSomebody** [comment]
What is the size of your file? It should be 1.3MB

**Comment by Janmm14** [comment]
Just mentioning that your ProtocolLib version is not supported by AAC, that will however not cause this issue likely.
See #855 for more information about that.

Try to use ProtocolLib 4.3.0, maybe that magically fixes it.

**Comment by Prunt** [comment]
@ItzSomebody Yup, it's 1.3MB.

@Janmm14 I tested with both the latest stable and latest development version of ProtocolLib, nothing changed. For the sake of using a supported version, I changed the tested ProtocolLib version to 4.3.0.

**Comment by CeIebrimbor** [comment]
@Prunt Is this still happening after downgrading to the recommended ProtocolLib 4.3.0? Your comments are unclear. We know it's not compatible with ProtocolLib 4.4.x+

**Comment by Prunt** [comment]
Yes, the error is the same with ProtocolLib 4.3.0.

**Comment by CeIebrimbor** [comment]
@Prunt 
I have users with _latest_ PaperSpigot for 1.12.1 that do not have this issue. Seeing as how you are almost 20 builds behind and using a build from the early development days of 1.12.1, you should consider updating your server jar. 

Please report back with any new discoveries. This issue will be closed within a couple days if you do not confirm the same issue occurring on the latest build (of Paper).

**Comment by Prunt** [comment]
I updated my Paper build to 1195, but the same error persists.

To rule out any possible variables I created a simple Paper server on my Windows 10 machine and everything worked fine. I'm closing the issue for now, but I'll let you know why it didn't work for me.

**Comment by Prunt** [comment]
Okay, I reopened the issue and changed the original comment to reflect my new findings.

**Comment by Janmm14** [comment]
Can you try with the jvm of the server on your machine as a test? maybe there is some error in that jvm version, because the error shows that the jvm can't load a class but it is actually executing code exactly from that class

**Comment by Prunt** [comment]
If you could point me to where I can download JDK 1.8.0-b132 for Windows, I would test it. Closest I could find was jdk8u131 on [this page](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html), but downloading it requires a company account and I really don't see the point in creating one just for this occasion.

**Comment by konsolas** [comment]
Google JDK, it's the first result.

**Comment by Prunt** [comment]
I know how to download the latest JVM, but that's not what @Janmm14 suggested.

I'll update Java on my server then, maybe that helps.

**Comment by Prunt** [comment]
Yup, updating from 1.8.0-b132 to 1.8.0_144-b01 helped.

**Comment by Janmm14** [comment]
I guess getting java 8u132 is not possible easily.
Maybe because there is a bug in that version.
