### ISSUE TITLE
ServerSings & Denizen: PlayerInteractEvent Error 1.11.2

### ISSUE THREAD

**Issue by DerSebiii** [konsolas/AAC-Issues#895]
### Issue description
On using a sign via ServerSign the Plugin throws an exception
ServerSign action: Essentials Warp and Denizen Command

```
[15:58:46 ERROR]: Could not pass event PlayerInteractEvent to AAC v3.3.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-283de8b-2ad21b8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-283de8b-2ad21b8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-283de8b-2ad21b8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-283de8b-2ad21b8]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [server.jar:git-Spigot-283de8b-2ad21b8]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [server.jar:git-Spigot-283de8b-2ad21b8]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904) [server.jar:git-Spigot-283de8b-2ad21b8]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [server.jar:git-Spigot-283de8b-2ad21b8]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [server.jar:git-Spigot-283de8b-2ad21b8]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-283de8b-2ad21b8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-283de8b-2ad21b8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-283de8b-2ad21b8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-283de8b-2ad21b8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-283de8b-2ad21b8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-283de8b-2ad21b8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
```

### Core information
**Server version**: 1.11.2

**AAC version**: 3.3.0

**ProtocolLib version**: 4.2.1-SNAPSHOT-b351pl

**Plugin list**: 

Plugins (79): HiveJumpPads, LazyChat, LazyTownChat, JoinMessagePlus, Craftconomy3, NametagEdit, Countdown, CPCameraStudioReborn, RogueParkour, SkinsRestorer, TitleAPI, Sudo, Reloader, VoxelSniper, LazyBasics, NoteBlockAPI, BetterClearInventory, CorpNation, ZavAutoMessager, BetterAlias, dynmap, XRayDetector, ChestShopDeny, LazyCorp, Erfolge, AdvancedBan, Chairs, Handschellen, WorldBorder, Votifier, EasyBackup, ProtocolLib, FastAsyncWorldEdit, iDisguise, Votesystem, RedstoneClockDetector, PermissionsEx, SuperbVote, SkyblockOres, Vault, xInventories, AdviEffects, SimpleRename, LWC, FamoustLottery, PlayerPoints, iBank, AAC, ASkyBlock, ChestCommands, WorldEdit, Essentials, MarriageMaster, ScoreboardStats, Multiverse-Core, Citizens, OnTime, Shopkeepers, HeavySpleef, EssentialsChat, LogBlock, HolographicDisplays, WorldGuard, GangsPlus, ServerSigns, EssentialsSpawn, TitleManager, Denizen, AreaShop, Towny, BlockBall, CraftBook, GriefPrevention, ArtMap, ChestShop, AuthMe, MCJukebox, Dynmap-Towny, MyPet

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**:  N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: 

- BungeeServerSignsPremium
- SkinsRestorer-v12.7-SNAPSHOT-4

### Configuration
Just changing some things about the issue tracker. So dont call an action after 10 seconds. Call it after 5 seconds or something like this.

**Comment by DerSebiii** [comment]
Update: Also other signs using ServerSigns WITHOUT Denizen thows the same error

**Comment by CeIebrimbor** [comment]
Can you give ProtocolLib 4.3.0 a try?

**Comment by DerSebiii** [comment]
Update to 3.3.1 fixed this problem! Thanks.

**Comment by Janmm14** [comment]
#881
