### ISSUE TITLE
Console error spam.

### ISSUE THREAD

**Issue by redfalcon5** [konsolas/AAC-Issues#902]
Hey, I keep getting this error spams in my console and I don't know why... The spam begin when a player joins the server and stops when there's none online.
Spigot 1.12.1

[00:01:22 ERROR]: [AAC] Unhandled exception occured in onPacketSending(PacketEvent) for AAC
java.lang.NoSuchMethodError: com.comphenix.protocol.wrappers.EnumWrappers.getGenericConverter(Ljava/lang/Class;)Lcom/comphenix/protocol/reflect/EquivalentConverter;
at me.konsolas.aac.bH.g(bH.java:27) ~[AAC.jar:3.3.1]
at me.konsolas.aac.bH.c(bH.java:20) ~[AAC.jar:3.3.1]
at me.konsolas.aac.aD.onPacketSending(aD.java:16) ~[AAC.jar:3.3.1]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1132) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerConnection.internalTeleport(PlayerConnection.java:792) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:744) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:701) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:692) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:169) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-65e8124-79e55b6]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[00:01:22 ERROR]: Parameters:
net.minecraft.server.v1_12_R1.PacketPlayOutPosition@29f401a4[
a=445.7911154164487
b=40.0
c=1094.0468334348293
d=17.920898
e=-3.2999845
f=[]
g=1
]

[00:01:22 INFO]: redfalcon225[/127.0.0.1:63093] logged in with entity id 1 at ([world]445.7911154164487, 40.0, 1094.0468334348293)
[00:01:23 ERROR]: [AAC] Unhandled exception occured in onPacketSending(PacketEvent) for AAC
java.lang.NoSuchMethodError: com.comphenix.protocol.wrappers.EnumWrappers.getGenericConverter(Ljava/lang/Class;)Lcom/comphenix/protocol/reflect/EquivalentConverter;
at me.konsolas.aac.bH.g(bH.java:27) ~[AAC.jar:3.3.1]
at me.konsolas.aac.bH.c(bH.java:20) ~[AAC.jar:3.3.1]
at me.konsolas.aac.aD.onPacketSending(aD.java:16) ~[AAC.jar:3.3.1]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.4.0-SNAPSHOT-b385]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1132) [spigot.jar:git-Spigot-65e8124-79e55b6]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
at skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:148) [SkinsRestorer-v13.1.3.jar:?]
at skinsrestorer.bukkit.skinfactory.UniversalSkinFactory.sendPacket(UniversalSkinFactory.java:81) [SkinsRestorer-v13.1.3.jar:?]
at skinsrestorer.bukkit.skinfactory.UniversalSkinFactory.updateSkin(UniversalSkinFactory.java:248) [SkinsRestorer-v13.1.3.jar:?]
at skinsrestorer.bukkit.SkinsRestorer$1$1.run(SkinsRestorer.java:159) [SkinsRestorer-v13.1.3.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-65e8124-79e55b6]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-65e8124-79e55b6]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[00:01:23 ERROR]: Parameters:
net.minecraft.server.v1_12_R1.PacketPlayOutPosition@1b00027c[
a=445.7911154164487
b=40.0
c=1094.0468334348293
d=17.920898
e=-3.2999845
f=[]
g=0
]

[00:01:29 INFO]: redfalcon225 issued server command: /tps
[00:01:34 INFO]: redfalcon225 issued server command: /plugins
[00:02:08 INFO]: redfalcon225 issued server command: /aacadmin
[00:03:11 ERROR]: [AAC] Unhandled exception occured in onPacketSending(PacketEvent) for AAC
java.lang.NoSuchMethodError: com.comphenix.protocol.wrappers.EnumWrappers.getGenericConverter(Ljava/lang/Class;)Lcom/comphenix/protocol/reflect/EquivalentConverter;
at me.konsolas.aac.bH.g(bH.java:27) ~[?:?]
at me.konsolas.aac.bH.c(bH.java:20) ~[?:?]
at me.konsolas.aac.aD.onPacketSending(aD.java:16) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1132) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerConnection.internalTeleport(PlayerConnection.java:792) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.PlayerConnection.teleport(PlayerConnection.java:748) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:537) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:271) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
at me.konsolas.aac.b7.lambda$createMenu$1(b7.java:44) ~[AAC.jar:3.3.1]
at me.konsolas.aac.a7.run(a7.java:4) [AAC.jar:3.3.1]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-65e8124-79e55b6]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-65e8124-79e55b6]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-65e8124-79e55b6]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[00:03:11 ERROR]: Parameters:
net.minecraft.server.v1_12_R1.PacketPlayOutPosition@77f623c2[
a=445.05952970741794
b=41.0
c=1095.507176318687
d=355.12085
e=15.750024
f=[]
g=2
]

**Comment by CeIebrimbor** [comment]
of #855
