### ISSUE TITLE
Citizens Conflict

### ISSUE THREAD

**Issue by DrNer0** [konsolas/AAC-Issues#925]
### Issue description
On server start, or after a short while, AAC gets an error and shuts the server

```
[Craft Scheduler Thread - 6/ERROR]: Could not pass event PlayerTeleportEvent to AAC v3.3.1
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:512) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:271) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:209) ~[?:?]
    at net.citizensnpcs.EventListen.spawn(EventListen.java:580) ~[?:?]
    at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:550) ~[?:?]
    at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:140) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:910) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:53) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:131) ~[spigot.jar:git-Spigot-65e8124-357b573]
    at net.redstoneore.legacyfactions.FLocation.getChunk(FLocation.java:102) ~[?:?]
    at net.redstoneore.legacyfactions.integration.dynmap.DynmapEngine.lambda$null$5(DynmapEngine.java:229) ~[?:?]
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_141]
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_141]
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548) ~[?:1.8.0_141]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_141]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_141]
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_141]
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_141]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_141]
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_141]
    at net.redstoneore.legacyfactions.integration.dynmap.DynmapEngine.lambda$null$6(DynmapEngine.java:229) ~[?:?]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_141]
    at net.redstoneore.legacyfactions.integration.dynmap.DynmapEngine.lambda$createWorldFactionChunks$7(DynmapEngine.java:219) ~[?:?]
    at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_141]
    at net.redstoneore.legacyfactions.integration.dynmap.DynmapEngine.createWorldFactionChunks(DynmapEngine.java:210) [LegacyFactions.jar:?]
    at net.redstoneore.legacyfactions.integration.dynmap.DynmapEngine.createAreas(DynmapEngine.java:203) [LegacyFactions.jar:?]
    at net.redstoneore.legacyfactions.integration.dynmap.DynmapEngine.run(DynmapEngine.java:76) [LegacyFactions.jar:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-65e8124-357b573]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-65e8124-357b573]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.IllegalStateException: Must be called from the main thread
    at me.konsolas.aac.B.a(B.java:114) ~[?:?]
    at me.konsolas.aac.cp.a(cp.java:115) ~[?:?]
    at me.konsolas.aac.B.a(B.java:89) ~[?:?]
    at me.konsolas.aac.B.a(B.java:59) ~[?:?]
    at me.konsolas.aac.bQ.a(bQ.java:83) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-65e8124-357b573]
    ... 49 more
```

### Core information
**Server version**: CraftBukkit version git-Spigot-65e8124-bde2a93 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: 3.3.2

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC
ArmorStandEditor
AsyncWorldEdit
BetterSleep
BossShop
BuycraftX
ChatItem
Citizens 2.0.22 SNAPSHOT
craftbook 3.9
DecoHeads
DeluxeChat
Denizen
DiscordSRV
Dynmap
EnchantsPlus
EssentialsX
EssentialsXGroupManager
EssentialsXSpawn
ezAuctions
HealthBar
Holograms
Jobs
LegacyFactions
MobArena
MVdWPlaceholderAPI
MyPet
MythicDrops
MythicMobs
OldCombatMechanics
PhatLoots
PlaceholderAPI
PlugMan
ProtocolLib
Quests
Rankup
Sentinel 1.3.1
Shrug
SilkSpawners
SpigotLib
TreeAssist
Vault
viabackwards
ViaVersion
WildTp
WirelessRedstone
WorldEdit
WorldGuard

### Special environment information
**ViaVersion version**: 1.2.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.2.0

**BungeeCord plugins**: N/A

**Comment by Janmm14** [comment]
Functionality of AAC is not affected.

Plugin `net.redstoneore.legacyfactions` seems to asynchroniously teleport citizens players and invoking chunk loads - this is risky, as it could crash servers.

AAC is reporting such behaviour and is not doing any asynchronous operations to internal minecraft stuff which should only be called only synchroniously. With AAC doing such internal operations, the frequency of crashes would increase.
