### ISSUE TITLE
FATAL: FAILED TO PULL ENTITY HITBOXES FROM NMS

### ISSUE THREAD

**Issue by Reeferx7** [konsolas/AAC-Issues#926]
### Core information
**Server version**: 
This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 
3.3.2-b1

**ProtocolLib version**: 
ProtocolLib version 4.2.0

Error:
```
[00:37:06] [Server thread/INFO]: [AAC] FATAL: FAILED TO PULL ENTITY HITBOXES FROM NMS
[00:37:06] [Server thread/INFO]: [AAC] Translation: Your server version has different NMS bindings than the ones AAC has on record. Please use official Spigot
[00:37:06] [Server thread/WARN]: [AAC] Task #440 for AAC v3.3.2 generated an exception
java.lang.IllegalStateException: NMS ERROR PULLING ENTITY HITBOXES
	at me.konsolas.aac.aI.<init>(aI.java:9) ~[?:?]
	at me.konsolas.aac.b1.a(b1.java:82) ~[?:?]
	at me.konsolas.aac.bn.a(bn.java:11) ~[?:?]
	at me.konsolas.aac.bn.a(bn.java:81) ~[?:?]
	at me.konsolas.aac.cK.a(cK.java:42) ~[?:?]
	at me.konsolas.aac.cR.lambda$new$0(cR.java:168) ~[?:?]
	at me.konsolas.aac.cR$$Lambda$10/41811903.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Singspigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NoSuchMethodException: com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$e5df76df.getHandle()
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_40]
	at me.konsolas.aac.aI.<init>(aI.java:37) ~[?:?]
	... 13 more
```

I use the lasted 1.8.8 spigot version with timings fix.
https://www.spigotmc.org/threads/spigot-hotfix-updates-1-8-8-1-9-4.171999/

I get this error like in 3-4 lasted aac versions.

This is happening like 60-70 times per day on my logs. As far i can see the error come on player login but no always.

**Comment by CeIebrimbor** [comment]
ProtocolSupport? ViaVersion? ViaBackwards?

Anything else that allows more than 1 client version to join?

Is this error tied to a specific client(s) if you have any of the above?

**Comment by Reeferx7** [comment]
Same error with or without ViaVersion in my plugin.

**Comment by Janmm14** [comment]
Error should not be a big problem and should only occurr shortly around logins.

**Comment by CeIebrimbor** [comment]
@Reeferx7 
Can you confirm if this is happening on super rare occasions (maybe test hitting within 1 second of login) or if this is persistent and common? It may just be something to overlook if it only happens in an incredibly small window.

**Comment by Reeferx7** [comment]
This happening like 60-70 times per day on my logs. As far i can see the error come on player login but no always.
