### ISSUE TITLE
BlockBreakEvent Console Spam (Player digging blocks)

### ISSUE THREAD

**Issue by Gonfonix** [konsolas/AAC-Issues#928]
### Issue description
When ever a player starts digging blocks, this error is spammed in the console:

https://pastebin.com/WWMxB9c1

** same error since first occurrence **

### Core information
**Server version**: Paper Spigot 1.12.1

**AAC version**: 3.3.2-b1

**ProtocolLib version**: 4.3.0 (Latest)

**Plugin list**: 
![image](https://user-images.githubusercontent.com/5055478/30043042-3d03a1e4-91c3-11e7-8031-d50ef29cf3e1.png)

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Currently using Celebrimbor's latest configuration (AAC 3.3.2 | 1)

**Comment by tomasmessing** [comment]
Same problem 
` [11:26:48 ERROR]: Could not pass event BlockBreakEvent to AAC v3.3.2
java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.a5
at me.konsolas.aac.c9.a(c9.java:65) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1106.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[paperspigot.jar:git-Paper-1104]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperspigot.jar:git-Paper-1104]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot.jar:git-Paper-1104]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[paperspigot.jar:git-Paper-1104]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:854) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paperspigot.jar:git-Paper-1104]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [paperspigot.jar:git-Paper-1104]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

**Comment by Sikatsu** [comment]
Same here

**Comment by CeIebrimbor** [comment]
Please download AAC 3.3.2-b2 (should fix)
