### ISSUE TITLE
Could not pass EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by MrEpic123** [konsolas/AAC-Issues#937]
### Issue description
When using killaura, critical etc on mobs the console will show the following error: 
[21:53:24 ERROR]: Could not pass event EntityDamageByEntityEvent to AAC v3.3.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1112) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:748) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1382) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
        at me.konsolas.aac.U.b(U.java:61) ~[?:?]
        at me.konsolas.aac.aF.a(aF.java:54) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor293.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 25 more

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.2

**ProtocolLib version**: 4.3.0

**Plugin list**: http://imgur.com/a/kWKKO

### Special environment information
**ViaVersion version**: 1.2.0

**ViaBackwards version**: 2.2.0

### Configuration
None, even generated a new config.

**Comment by CeIebrimbor** [comment]
Please try version 4.2.0 of ProtocolLib. It is currently recommended for 1.8 servers.

**Comment by MrEpic123** [comment]
This solved my problem, thankyou.

**Comment by MrEpic123** [comment]
Hello,

Sorry, this didnt fix the issue. 

Getting the error again.

**Comment by CeIebrimbor** [comment]
Are you using AAC 3.2.2-b2? Downgrade to 3.2.2 (b0) and report back.

**Comment by MrEpic123** [comment]
Using 3.2.2-b2 now.

But i just saw on spigot that 1.8.8 needs to use: AAC v1.9.10 is this right? 

I quote: 
Prior to AAC v3.0, each version of Minecraft had a unique resource jar. If you choose to stick with older builds (not recommended or supported), find your unique build download in AAC's Version History.
1.8.8: AAC v1.9.10
1.9.4: AAC v2.0.1
1.10: AAC v2.1.1
1.11: None, use v3.0+

**Comment by CeIebrimbor** [comment]
No, those are for obsolete versions of AAC.

Use:
Spigot 1.8.8
AAC 3.2.2 (b0)
ProtocolLib 4.2.0

**Comment by MrEpic123** [comment]
3.2.2-b1 *

**Comment by CeIebrimbor** [comment]
Avoid b1. It will be 🔥

**Comment by MrEpic123** [comment]
Ok using 3.2.2 now then will report back.
