### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Cobwebster** [konsolas/AAC-Issues#989]
Crash:
https://pastebin.com/XFdacNe5

PaperSpigot 1.12.1

30.09 14:23:20 [Server] INFO Enabling AAC v3.3.2

30.09 14:23:15 [Server] INFO Loading ProtocolLib v4.4.0-SNAPSHOT-b385

We're a version behind but thought i'd report just encase it wasn't addressed in 3.3.3, we'll update tonight.

We get this error,

```
30.09 14:25:39 [Server] ERROR Unhandled exception occured in onPacketSending(PacketEvent) for AAC
30.09 14:25:39 [Server] INFO java.lang.NoSuchMethodError: com.comphenix.protocol.wrappers.EnumWrappers.getGenericConverter(Ljava/lang/Class;)Lcom/comphenix/protocol/reflect/EquivalentConverter;
30.09 14:25:39 [Server] INFO at me.konsolas.aac.A.f(A.java:7) ~[?:?]
30.09 14:25:39 [Server] INFO at me.konsolas.aac.A.g(A.java:11) ~[?:?]
30.09 14:25:39 [Server] INFO at me.konsolas.aac.aq.onPacketSending(aq.java:79) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
30.09 14:25:39 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
30.09 14:25:39 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:176) ~[patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) ~[patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1141) ~[patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.internalTeleport(PlayerConnection.java:794) ~[patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.teleport(PlayerConnection.java:750) ~[patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:633) ~[patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at me.konsolas.aac.b0.lambda$new$2(b0.java:37) ~[?:?]
30.09 14:25:39 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1195]
30.09 14:25:39 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
30.09 14:25:39 [Server] ERROR Parameters: 
30.09 14:25:39 [Server] INFO net.minecraft.server.v1_12_R1.PacketPlayOutPosition@207081a5[
30.09 14:25:39 [Server] INFO a=133259.31525816646
30.09 14:25:39 [Server] INFO b=4.0
30.09 14:25:39 [Server] INFO c=-22091.91507155653
30.09 14:25:39 [Server] INFO d=131.23155
30.09 14:25:39 [Server] INFO e=13.0643635
30.09 14:25:39 [Server] INFO f=[]
30.09 14:25:39 [Server] INFO g=2
30.09 14:25:39 [Server] INFO ]
```

**Comment by Janmm14** [comment]
Either use ProtocolLib 4.3.0 or the latest protocollib snapshot to address the protocollib stack trace.

**Comment by CeIebrimbor** [comment]
Since this is using an unsupported version of ProtocolLib, this will be closed.

If you update to the [latest stable dev build](http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/) (which is supported) and have an issue, please open up a new issue or request reopen after submitting new findings.
