### ISSUE TITLE
Error spams console

### ISSUE THREAD

**Issue by marint94** [konsolas/AAC-Issues#997]
### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.2

**ProtocolLib version**: 4.4.0 (b389)

**Plugin list**: WorldEdit, WorldGuard, AAC

### Special environment information
**ViaVersion version**: (1.3.0)

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

```
[14:49:07 WARN]: [AAC] Task #17 for AAC v3.3.2 generated an exception
java.lang.IllegalStateException: Duplicate key 44.10601474610294,12.0,-310.2224041630102
at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) ~[?:1.8.0_101]
at java.util.HashMap.merge(HashMap.java:1253) ~[?:1.8.0_101]
at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[?:1.8.0_101]
at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_101]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_101]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_101]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_101]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_101]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_101]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_101]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_101]
at me.konsolas.aac.b1.a(b1.java:2) ~[?:?]
at me.konsolas.aac.k.lambda$new$0(k.java:22) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by Rerd** [comment]
“Latest” isn’t a version.

**Comment by CeIebrimbor** [comment]
#984
